// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file olvid/daemon/command/v1/call_commands.proto (package olvid.daemon.command.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file olvid/daemon/command/v1/call_commands.proto.
 */
export const file_olvid_daemon_command_v1_call_commands: GenFile = /*@__PURE__*/
  fileDesc("CitvbHZpZC9kYWVtb24vY29tbWFuZC92MS9jYWxsX2NvbW1hbmRzLnByb3RvEhdvbHZpZC5kYWVtb24uY29tbWFuZC52MSI3Ch5DYWxsU3RhcnREaXNjdXNzaW9uQ2FsbFJlcXVlc3QSFQoNZGlzY3Vzc2lvbl9pZBgBIAEoBCI6Ch9DYWxsU3RhcnREaXNjdXNzaW9uQ2FsbFJlc3BvbnNlEhcKD2NhbGxfaWRlbnRpZmllchgBIAEoCSJfChpDYWxsU3RhcnRDdXN0b21DYWxsUmVxdWVzdBITCgtjb250YWN0X2lkcxgBIAMoBBIaCg1kaXNjdXNzaW9uX2lkGAIgASgESACIAQFCEAoOX2Rpc2N1c3Npb25faWQiNgobQ2FsbFN0YXJ0Q3VzdG9tQ2FsbFJlc3BvbnNlEhcKD2NhbGxfaWRlbnRpZmllchgBIAEoCUI1CiBpby5vbHZpZC5kZXNrdG9wLmRhZW1vbi5wcm90b2J1ZlABWg9vbHZpZC5pby9kYWVtb25iBnByb3RvMw");

/**
 *
 * * CallStartDiscussionCall
 * * Start a call with one discussion member(s).
 * * This will start a one to one call or a group call depending on discussion type.
 * * You can use *call_identifier* to filter later call notifications.
 * *
 * * **Error codes**:
 * * `NOT_FOUND`: discussion not found.
 * * `INVALID_ARGUMENT`: cannot start a call in an empty group.
 * * `INTERNAL`
 * * `UNAUTHENTICATED`: client key is invalid.
 *
 * @generated from message olvid.daemon.command.v1.CallStartDiscussionCallRequest
 */
export type CallStartDiscussionCallRequest = Message<"olvid.daemon.command.v1.CallStartDiscussionCallRequest"> & {
  /**
   * @generated from field: uint64 discussion_id = 1;
   */
  discussionId: bigint;
};

/**
 * Describes the message olvid.daemon.command.v1.CallStartDiscussionCallRequest.
 * Use `create(CallStartDiscussionCallRequestSchema)` to create a new message.
 */
export const CallStartDiscussionCallRequestSchema: GenMessage<CallStartDiscussionCallRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_call_commands, 0);

/**
 * @generated from message olvid.daemon.command.v1.CallStartDiscussionCallResponse
 */
export type CallStartDiscussionCallResponse = Message<"olvid.daemon.command.v1.CallStartDiscussionCallResponse"> & {
  /**
   * @generated from field: string call_identifier = 1;
   */
  callIdentifier: string;
};

/**
 * Describes the message olvid.daemon.command.v1.CallStartDiscussionCallResponse.
 * Use `create(CallStartDiscussionCallResponseSchema)` to create a new message.
 */
export const CallStartDiscussionCallResponseSchema: GenMessage<CallStartDiscussionCallResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_call_commands, 1);

/**
 *
 * * CallStartCustomCall
 * * Start a call with any contacts, even if they do not belong to the same discussion.
 * * You can use *call_identifier* to filter later call notifications.
 * *
 * * **Error codes**:
 * * `NOT_FOUND`: discussion or contact not found.
 * * `UNAUTHENTICATED`: client key is invalid.
 *
 * @generated from message olvid.daemon.command.v1.CallStartCustomCallRequest
 */
export type CallStartCustomCallRequest = Message<"olvid.daemon.command.v1.CallStartCustomCallRequest"> & {
  /**
   * @generated from field: repeated uint64 contact_ids = 1;
   */
  contactIds: bigint[];

  /**
   * specify in which discussion other contacts will log call
   *
   * @generated from field: optional uint64 discussion_id = 2;
   */
  discussionId?: bigint;
};

/**
 * Describes the message olvid.daemon.command.v1.CallStartCustomCallRequest.
 * Use `create(CallStartCustomCallRequestSchema)` to create a new message.
 */
export const CallStartCustomCallRequestSchema: GenMessage<CallStartCustomCallRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_call_commands, 2);

/**
 * @generated from message olvid.daemon.command.v1.CallStartCustomCallResponse
 */
export type CallStartCustomCallResponse = Message<"olvid.daemon.command.v1.CallStartCustomCallResponse"> & {
  /**
   * @generated from field: string call_identifier = 1;
   */
  callIdentifier: string;
};

/**
 * Describes the message olvid.daemon.command.v1.CallStartCustomCallResponse.
 * Use `create(CallStartCustomCallResponseSchema)` to create a new message.
 */
export const CallStartCustomCallResponseSchema: GenMessage<CallStartCustomCallResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_call_commands, 3);

