// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file olvid/daemon/command/v1/call_commands.proto (package olvid.daemon.command.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 *
 * * CallStartDiscussionCall
 *
 * @generated from message olvid.daemon.command.v1.CallStartDiscussionCallRequest
 */
export class CallStartDiscussionCallRequest extends Message<CallStartDiscussionCallRequest> {
  /**
   * @generated from field: uint64 discussion_id = 1;
   */
  discussionId = protoInt64.zero;

  constructor(data?: PartialMessage<CallStartDiscussionCallRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.CallStartDiscussionCallRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "discussion_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CallStartDiscussionCallRequest {
    return new CallStartDiscussionCallRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CallStartDiscussionCallRequest {
    return new CallStartDiscussionCallRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CallStartDiscussionCallRequest {
    return new CallStartDiscussionCallRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CallStartDiscussionCallRequest | PlainMessage<CallStartDiscussionCallRequest> | undefined, b: CallStartDiscussionCallRequest | PlainMessage<CallStartDiscussionCallRequest> | undefined): boolean {
    return proto3.util.equals(CallStartDiscussionCallRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.CallStartDiscussionCallResponse
 */
export class CallStartDiscussionCallResponse extends Message<CallStartDiscussionCallResponse> {
  /**
   * @generated from field: string call_identifier = 1;
   */
  callIdentifier = "";

  constructor(data?: PartialMessage<CallStartDiscussionCallResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.CallStartDiscussionCallResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "call_identifier", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CallStartDiscussionCallResponse {
    return new CallStartDiscussionCallResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CallStartDiscussionCallResponse {
    return new CallStartDiscussionCallResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CallStartDiscussionCallResponse {
    return new CallStartDiscussionCallResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CallStartDiscussionCallResponse | PlainMessage<CallStartDiscussionCallResponse> | undefined, b: CallStartDiscussionCallResponse | PlainMessage<CallStartDiscussionCallResponse> | undefined): boolean {
    return proto3.util.equals(CallStartDiscussionCallResponse, a, b);
  }
}

/**
 *
 * * CallStartCustomCall
 *
 * @generated from message olvid.daemon.command.v1.CallStartCustomCallRequest
 */
export class CallStartCustomCallRequest extends Message<CallStartCustomCallRequest> {
  /**
   * @generated from field: repeated uint64 contact_ids = 1;
   */
  contactIds: bigint[] = [];

  /**
   * @generated from field: optional uint64 discussion_id = 2;
   */
  discussionId?: bigint;

  constructor(data?: PartialMessage<CallStartCustomCallRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.CallStartCustomCallRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "contact_ids", kind: "scalar", T: 4 /* ScalarType.UINT64 */, repeated: true },
    { no: 2, name: "discussion_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CallStartCustomCallRequest {
    return new CallStartCustomCallRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CallStartCustomCallRequest {
    return new CallStartCustomCallRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CallStartCustomCallRequest {
    return new CallStartCustomCallRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CallStartCustomCallRequest | PlainMessage<CallStartCustomCallRequest> | undefined, b: CallStartCustomCallRequest | PlainMessage<CallStartCustomCallRequest> | undefined): boolean {
    return proto3.util.equals(CallStartCustomCallRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.CallStartCustomCallResponse
 */
export class CallStartCustomCallResponse extends Message<CallStartCustomCallResponse> {
  /**
   * @generated from field: string call_identifier = 1;
   */
  callIdentifier = "";

  constructor(data?: PartialMessage<CallStartCustomCallResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.CallStartCustomCallResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "call_identifier", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CallStartCustomCallResponse {
    return new CallStartCustomCallResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CallStartCustomCallResponse {
    return new CallStartCustomCallResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CallStartCustomCallResponse {
    return new CallStartCustomCallResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CallStartCustomCallResponse | PlainMessage<CallStartCustomCallResponse> | undefined, b: CallStartCustomCallResponse | PlainMessage<CallStartCustomCallResponse> | undefined): boolean {
    return proto3.util.equals(CallStartCustomCallResponse, a, b);
  }
}

