// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file olvid/daemon/command/v1/identity_commands.proto (package olvid.daemon.command.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Identity, Identity_ApiKey, IdentityDetails } from "../../datatypes/v1/identity_pb.js";

/**
 *
 * * IdentityGet
 *
 * @generated from message olvid.daemon.command.v1.IdentityGetRequest
 */
export class IdentityGetRequest extends Message<IdentityGetRequest> {
  constructor(data?: PartialMessage<IdentityGetRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentityGetRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentityGetRequest {
    return new IdentityGetRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentityGetRequest {
    return new IdentityGetRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentityGetRequest {
    return new IdentityGetRequest().fromJsonString(jsonString, options);
  }

  static equals(a: IdentityGetRequest | PlainMessage<IdentityGetRequest> | undefined, b: IdentityGetRequest | PlainMessage<IdentityGetRequest> | undefined): boolean {
    return proto3.util.equals(IdentityGetRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.IdentityGetResponse
 */
export class IdentityGetResponse extends Message<IdentityGetResponse> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Identity identity = 1;
   */
  identity?: Identity;

  constructor(data?: PartialMessage<IdentityGetResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentityGetResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "identity", kind: "message", T: Identity },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentityGetResponse {
    return new IdentityGetResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentityGetResponse {
    return new IdentityGetResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentityGetResponse {
    return new IdentityGetResponse().fromJsonString(jsonString, options);
  }

  static equals(a: IdentityGetResponse | PlainMessage<IdentityGetResponse> | undefined, b: IdentityGetResponse | PlainMessage<IdentityGetResponse> | undefined): boolean {
    return proto3.util.equals(IdentityGetResponse, a, b);
  }
}

/**
 *
 * * IdentityGetBytesIdentifier
 *
 * @generated from message olvid.daemon.command.v1.IdentityGetBytesIdentifierRequest
 */
export class IdentityGetBytesIdentifierRequest extends Message<IdentityGetBytesIdentifierRequest> {
  constructor(data?: PartialMessage<IdentityGetBytesIdentifierRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentityGetBytesIdentifierRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentityGetBytesIdentifierRequest {
    return new IdentityGetBytesIdentifierRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentityGetBytesIdentifierRequest {
    return new IdentityGetBytesIdentifierRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentityGetBytesIdentifierRequest {
    return new IdentityGetBytesIdentifierRequest().fromJsonString(jsonString, options);
  }

  static equals(a: IdentityGetBytesIdentifierRequest | PlainMessage<IdentityGetBytesIdentifierRequest> | undefined, b: IdentityGetBytesIdentifierRequest | PlainMessage<IdentityGetBytesIdentifierRequest> | undefined): boolean {
    return proto3.util.equals(IdentityGetBytesIdentifierRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.IdentityGetBytesIdentifierResponse
 */
export class IdentityGetBytesIdentifierResponse extends Message<IdentityGetBytesIdentifierResponse> {
  /**
   * @generated from field: bytes identifier = 1;
   */
  identifier = new Uint8Array(0);

  constructor(data?: PartialMessage<IdentityGetBytesIdentifierResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentityGetBytesIdentifierResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "identifier", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentityGetBytesIdentifierResponse {
    return new IdentityGetBytesIdentifierResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentityGetBytesIdentifierResponse {
    return new IdentityGetBytesIdentifierResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentityGetBytesIdentifierResponse {
    return new IdentityGetBytesIdentifierResponse().fromJsonString(jsonString, options);
  }

  static equals(a: IdentityGetBytesIdentifierResponse | PlainMessage<IdentityGetBytesIdentifierResponse> | undefined, b: IdentityGetBytesIdentifierResponse | PlainMessage<IdentityGetBytesIdentifierResponse> | undefined): boolean {
    return proto3.util.equals(IdentityGetBytesIdentifierResponse, a, b);
  }
}

/**
 *
 * * IdentityGetInvitationLink
 *
 * @generated from message olvid.daemon.command.v1.IdentityGetInvitationLinkRequest
 */
export class IdentityGetInvitationLinkRequest extends Message<IdentityGetInvitationLinkRequest> {
  constructor(data?: PartialMessage<IdentityGetInvitationLinkRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentityGetInvitationLinkRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentityGetInvitationLinkRequest {
    return new IdentityGetInvitationLinkRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentityGetInvitationLinkRequest {
    return new IdentityGetInvitationLinkRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentityGetInvitationLinkRequest {
    return new IdentityGetInvitationLinkRequest().fromJsonString(jsonString, options);
  }

  static equals(a: IdentityGetInvitationLinkRequest | PlainMessage<IdentityGetInvitationLinkRequest> | undefined, b: IdentityGetInvitationLinkRequest | PlainMessage<IdentityGetInvitationLinkRequest> | undefined): boolean {
    return proto3.util.equals(IdentityGetInvitationLinkRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.IdentityGetInvitationLinkResponse
 */
export class IdentityGetInvitationLinkResponse extends Message<IdentityGetInvitationLinkResponse> {
  /**
   * @generated from field: string invitation_link = 1;
   */
  invitationLink = "";

  constructor(data?: PartialMessage<IdentityGetInvitationLinkResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentityGetInvitationLinkResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "invitation_link", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentityGetInvitationLinkResponse {
    return new IdentityGetInvitationLinkResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentityGetInvitationLinkResponse {
    return new IdentityGetInvitationLinkResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentityGetInvitationLinkResponse {
    return new IdentityGetInvitationLinkResponse().fromJsonString(jsonString, options);
  }

  static equals(a: IdentityGetInvitationLinkResponse | PlainMessage<IdentityGetInvitationLinkResponse> | undefined, b: IdentityGetInvitationLinkResponse | PlainMessage<IdentityGetInvitationLinkResponse> | undefined): boolean {
    return proto3.util.equals(IdentityGetInvitationLinkResponse, a, b);
  }
}

/**
 *
 * * IdentityUpdateDetails
 *
 * @generated from message olvid.daemon.command.v1.IdentityUpdateDetailsRequest
 */
export class IdentityUpdateDetailsRequest extends Message<IdentityUpdateDetailsRequest> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.IdentityDetails new_details = 2;
   */
  newDetails?: IdentityDetails;

  constructor(data?: PartialMessage<IdentityUpdateDetailsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentityUpdateDetailsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "new_details", kind: "message", T: IdentityDetails },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentityUpdateDetailsRequest {
    return new IdentityUpdateDetailsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentityUpdateDetailsRequest {
    return new IdentityUpdateDetailsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentityUpdateDetailsRequest {
    return new IdentityUpdateDetailsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: IdentityUpdateDetailsRequest | PlainMessage<IdentityUpdateDetailsRequest> | undefined, b: IdentityUpdateDetailsRequest | PlainMessage<IdentityUpdateDetailsRequest> | undefined): boolean {
    return proto3.util.equals(IdentityUpdateDetailsRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.IdentityUpdateDetailsResponse
 */
export class IdentityUpdateDetailsResponse extends Message<IdentityUpdateDetailsResponse> {
  constructor(data?: PartialMessage<IdentityUpdateDetailsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentityUpdateDetailsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentityUpdateDetailsResponse {
    return new IdentityUpdateDetailsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentityUpdateDetailsResponse {
    return new IdentityUpdateDetailsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentityUpdateDetailsResponse {
    return new IdentityUpdateDetailsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: IdentityUpdateDetailsResponse | PlainMessage<IdentityUpdateDetailsResponse> | undefined, b: IdentityUpdateDetailsResponse | PlainMessage<IdentityUpdateDetailsResponse> | undefined): boolean {
    return proto3.util.equals(IdentityUpdateDetailsResponse, a, b);
  }
}

/**
 *
 * * IdentityRemovePhoto
 *
 * @generated from message olvid.daemon.command.v1.IdentityRemovePhotoRequest
 */
export class IdentityRemovePhotoRequest extends Message<IdentityRemovePhotoRequest> {
  constructor(data?: PartialMessage<IdentityRemovePhotoRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentityRemovePhotoRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentityRemovePhotoRequest {
    return new IdentityRemovePhotoRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentityRemovePhotoRequest {
    return new IdentityRemovePhotoRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentityRemovePhotoRequest {
    return new IdentityRemovePhotoRequest().fromJsonString(jsonString, options);
  }

  static equals(a: IdentityRemovePhotoRequest | PlainMessage<IdentityRemovePhotoRequest> | undefined, b: IdentityRemovePhotoRequest | PlainMessage<IdentityRemovePhotoRequest> | undefined): boolean {
    return proto3.util.equals(IdentityRemovePhotoRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.IdentityRemovePhotoResponse
 */
export class IdentityRemovePhotoResponse extends Message<IdentityRemovePhotoResponse> {
  constructor(data?: PartialMessage<IdentityRemovePhotoResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentityRemovePhotoResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentityRemovePhotoResponse {
    return new IdentityRemovePhotoResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentityRemovePhotoResponse {
    return new IdentityRemovePhotoResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentityRemovePhotoResponse {
    return new IdentityRemovePhotoResponse().fromJsonString(jsonString, options);
  }

  static equals(a: IdentityRemovePhotoResponse | PlainMessage<IdentityRemovePhotoResponse> | undefined, b: IdentityRemovePhotoResponse | PlainMessage<IdentityRemovePhotoResponse> | undefined): boolean {
    return proto3.util.equals(IdentityRemovePhotoResponse, a, b);
  }
}

/**
 *
 * * IdentitySetPhoto
 *
 * @generated from message olvid.daemon.command.v1.IdentitySetPhotoRequestMetadata
 */
export class IdentitySetPhotoRequestMetadata extends Message<IdentitySetPhotoRequestMetadata> {
  /**
   * @generated from field: string filename = 1;
   */
  filename = "";

  /**
   * @generated from field: uint64 file_size = 2;
   */
  fileSize = protoInt64.zero;

  constructor(data?: PartialMessage<IdentitySetPhotoRequestMetadata>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentitySetPhotoRequestMetadata";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "file_size", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentitySetPhotoRequestMetadata {
    return new IdentitySetPhotoRequestMetadata().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentitySetPhotoRequestMetadata {
    return new IdentitySetPhotoRequestMetadata().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentitySetPhotoRequestMetadata {
    return new IdentitySetPhotoRequestMetadata().fromJsonString(jsonString, options);
  }

  static equals(a: IdentitySetPhotoRequestMetadata | PlainMessage<IdentitySetPhotoRequestMetadata> | undefined, b: IdentitySetPhotoRequestMetadata | PlainMessage<IdentitySetPhotoRequestMetadata> | undefined): boolean {
    return proto3.util.equals(IdentitySetPhotoRequestMetadata, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.IdentitySetPhotoRequest
 */
export class IdentitySetPhotoRequest extends Message<IdentitySetPhotoRequest> {
  /**
   * @generated from oneof olvid.daemon.command.v1.IdentitySetPhotoRequest.request
   */
  request: {
    /**
     * @generated from field: olvid.daemon.command.v1.IdentitySetPhotoRequestMetadata metadata = 1;
     */
    value: IdentitySetPhotoRequestMetadata;
    case: "metadata";
  } | {
    /**
     * @generated from field: bytes payload = 2;
     */
    value: Uint8Array;
    case: "payload";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<IdentitySetPhotoRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentitySetPhotoRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "metadata", kind: "message", T: IdentitySetPhotoRequestMetadata, oneof: "request" },
    { no: 2, name: "payload", kind: "scalar", T: 12 /* ScalarType.BYTES */, oneof: "request" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentitySetPhotoRequest {
    return new IdentitySetPhotoRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentitySetPhotoRequest {
    return new IdentitySetPhotoRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentitySetPhotoRequest {
    return new IdentitySetPhotoRequest().fromJsonString(jsonString, options);
  }

  static equals(a: IdentitySetPhotoRequest | PlainMessage<IdentitySetPhotoRequest> | undefined, b: IdentitySetPhotoRequest | PlainMessage<IdentitySetPhotoRequest> | undefined): boolean {
    return proto3.util.equals(IdentitySetPhotoRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.IdentitySetPhotoResponse
 */
export class IdentitySetPhotoResponse extends Message<IdentitySetPhotoResponse> {
  constructor(data?: PartialMessage<IdentitySetPhotoResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentitySetPhotoResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentitySetPhotoResponse {
    return new IdentitySetPhotoResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentitySetPhotoResponse {
    return new IdentitySetPhotoResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentitySetPhotoResponse {
    return new IdentitySetPhotoResponse().fromJsonString(jsonString, options);
  }

  static equals(a: IdentitySetPhotoResponse | PlainMessage<IdentitySetPhotoResponse> | undefined, b: IdentitySetPhotoResponse | PlainMessage<IdentitySetPhotoResponse> | undefined): boolean {
    return proto3.util.equals(IdentitySetPhotoResponse, a, b);
  }
}

/**
 *
 * * IdentityDownloadPhoto
 *
 * @generated from message olvid.daemon.command.v1.IdentityDownloadPhotoRequest
 */
export class IdentityDownloadPhotoRequest extends Message<IdentityDownloadPhotoRequest> {
  constructor(data?: PartialMessage<IdentityDownloadPhotoRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentityDownloadPhotoRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentityDownloadPhotoRequest {
    return new IdentityDownloadPhotoRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentityDownloadPhotoRequest {
    return new IdentityDownloadPhotoRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentityDownloadPhotoRequest {
    return new IdentityDownloadPhotoRequest().fromJsonString(jsonString, options);
  }

  static equals(a: IdentityDownloadPhotoRequest | PlainMessage<IdentityDownloadPhotoRequest> | undefined, b: IdentityDownloadPhotoRequest | PlainMessage<IdentityDownloadPhotoRequest> | undefined): boolean {
    return proto3.util.equals(IdentityDownloadPhotoRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.IdentityDownloadPhotoResponse
 */
export class IdentityDownloadPhotoResponse extends Message<IdentityDownloadPhotoResponse> {
  /**
   * @generated from field: bytes photo = 1;
   */
  photo = new Uint8Array(0);

  constructor(data?: PartialMessage<IdentityDownloadPhotoResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentityDownloadPhotoResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "photo", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentityDownloadPhotoResponse {
    return new IdentityDownloadPhotoResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentityDownloadPhotoResponse {
    return new IdentityDownloadPhotoResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentityDownloadPhotoResponse {
    return new IdentityDownloadPhotoResponse().fromJsonString(jsonString, options);
  }

  static equals(a: IdentityDownloadPhotoResponse | PlainMessage<IdentityDownloadPhotoResponse> | undefined, b: IdentityDownloadPhotoResponse | PlainMessage<IdentityDownloadPhotoResponse> | undefined): boolean {
    return proto3.util.equals(IdentityDownloadPhotoResponse, a, b);
  }
}

/**
 *
 * * IdentityKeycloakBind
 *
 * @generated from message olvid.daemon.command.v1.IdentityKeycloakBindRequest
 */
export class IdentityKeycloakBindRequest extends Message<IdentityKeycloakBindRequest> {
  /**
   * @generated from field: string configuration_link = 1;
   */
  configurationLink = "";

  constructor(data?: PartialMessage<IdentityKeycloakBindRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentityKeycloakBindRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "configuration_link", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentityKeycloakBindRequest {
    return new IdentityKeycloakBindRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentityKeycloakBindRequest {
    return new IdentityKeycloakBindRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentityKeycloakBindRequest {
    return new IdentityKeycloakBindRequest().fromJsonString(jsonString, options);
  }

  static equals(a: IdentityKeycloakBindRequest | PlainMessage<IdentityKeycloakBindRequest> | undefined, b: IdentityKeycloakBindRequest | PlainMessage<IdentityKeycloakBindRequest> | undefined): boolean {
    return proto3.util.equals(IdentityKeycloakBindRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.IdentityKeycloakBindResponse
 */
export class IdentityKeycloakBindResponse extends Message<IdentityKeycloakBindResponse> {
  constructor(data?: PartialMessage<IdentityKeycloakBindResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentityKeycloakBindResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentityKeycloakBindResponse {
    return new IdentityKeycloakBindResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentityKeycloakBindResponse {
    return new IdentityKeycloakBindResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentityKeycloakBindResponse {
    return new IdentityKeycloakBindResponse().fromJsonString(jsonString, options);
  }

  static equals(a: IdentityKeycloakBindResponse | PlainMessage<IdentityKeycloakBindResponse> | undefined, b: IdentityKeycloakBindResponse | PlainMessage<IdentityKeycloakBindResponse> | undefined): boolean {
    return proto3.util.equals(IdentityKeycloakBindResponse, a, b);
  }
}

/**
 *
 * * IdentityKeycloakUnbind
 *
 * @generated from message olvid.daemon.command.v1.IdentityKeycloakUnbindRequest
 */
export class IdentityKeycloakUnbindRequest extends Message<IdentityKeycloakUnbindRequest> {
  constructor(data?: PartialMessage<IdentityKeycloakUnbindRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentityKeycloakUnbindRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentityKeycloakUnbindRequest {
    return new IdentityKeycloakUnbindRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentityKeycloakUnbindRequest {
    return new IdentityKeycloakUnbindRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentityKeycloakUnbindRequest {
    return new IdentityKeycloakUnbindRequest().fromJsonString(jsonString, options);
  }

  static equals(a: IdentityKeycloakUnbindRequest | PlainMessage<IdentityKeycloakUnbindRequest> | undefined, b: IdentityKeycloakUnbindRequest | PlainMessage<IdentityKeycloakUnbindRequest> | undefined): boolean {
    return proto3.util.equals(IdentityKeycloakUnbindRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.IdentityKeycloakUnbindResponse
 */
export class IdentityKeycloakUnbindResponse extends Message<IdentityKeycloakUnbindResponse> {
  constructor(data?: PartialMessage<IdentityKeycloakUnbindResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentityKeycloakUnbindResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentityKeycloakUnbindResponse {
    return new IdentityKeycloakUnbindResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentityKeycloakUnbindResponse {
    return new IdentityKeycloakUnbindResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentityKeycloakUnbindResponse {
    return new IdentityKeycloakUnbindResponse().fromJsonString(jsonString, options);
  }

  static equals(a: IdentityKeycloakUnbindResponse | PlainMessage<IdentityKeycloakUnbindResponse> | undefined, b: IdentityKeycloakUnbindResponse | PlainMessage<IdentityKeycloakUnbindResponse> | undefined): boolean {
    return proto3.util.equals(IdentityKeycloakUnbindResponse, a, b);
  }
}

/**
 *
 * * IdentitySetApiKey
 *
 * @generated from message olvid.daemon.command.v1.IdentitySetApiKeyRequest
 */
export class IdentitySetApiKeyRequest extends Message<IdentitySetApiKeyRequest> {
  /**
   * @generated from field: string api_key = 1;
   */
  apiKey = "";

  constructor(data?: PartialMessage<IdentitySetApiKeyRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentitySetApiKeyRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "api_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentitySetApiKeyRequest {
    return new IdentitySetApiKeyRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentitySetApiKeyRequest {
    return new IdentitySetApiKeyRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentitySetApiKeyRequest {
    return new IdentitySetApiKeyRequest().fromJsonString(jsonString, options);
  }

  static equals(a: IdentitySetApiKeyRequest | PlainMessage<IdentitySetApiKeyRequest> | undefined, b: IdentitySetApiKeyRequest | PlainMessage<IdentitySetApiKeyRequest> | undefined): boolean {
    return proto3.util.equals(IdentitySetApiKeyRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.IdentitySetApiKeyResponse
 */
export class IdentitySetApiKeyResponse extends Message<IdentitySetApiKeyResponse> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Identity.ApiKey api_key = 1;
   */
  apiKey?: Identity_ApiKey;

  constructor(data?: PartialMessage<IdentitySetApiKeyResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentitySetApiKeyResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "api_key", kind: "message", T: Identity_ApiKey },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentitySetApiKeyResponse {
    return new IdentitySetApiKeyResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentitySetApiKeyResponse {
    return new IdentitySetApiKeyResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentitySetApiKeyResponse {
    return new IdentitySetApiKeyResponse().fromJsonString(jsonString, options);
  }

  static equals(a: IdentitySetApiKeyResponse | PlainMessage<IdentitySetApiKeyResponse> | undefined, b: IdentitySetApiKeyResponse | PlainMessage<IdentitySetApiKeyResponse> | undefined): boolean {
    return proto3.util.equals(IdentitySetApiKeyResponse, a, b);
  }
}

/**
 *
 * * IdentitySetConfigurationLink
 *
 * @generated from message olvid.daemon.command.v1.IdentitySetConfigurationLinkRequest
 */
export class IdentitySetConfigurationLinkRequest extends Message<IdentitySetConfigurationLinkRequest> {
  /**
   * @generated from field: string configuration_link = 1;
   */
  configurationLink = "";

  constructor(data?: PartialMessage<IdentitySetConfigurationLinkRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentitySetConfigurationLinkRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "configuration_link", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentitySetConfigurationLinkRequest {
    return new IdentitySetConfigurationLinkRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentitySetConfigurationLinkRequest {
    return new IdentitySetConfigurationLinkRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentitySetConfigurationLinkRequest {
    return new IdentitySetConfigurationLinkRequest().fromJsonString(jsonString, options);
  }

  static equals(a: IdentitySetConfigurationLinkRequest | PlainMessage<IdentitySetConfigurationLinkRequest> | undefined, b: IdentitySetConfigurationLinkRequest | PlainMessage<IdentitySetConfigurationLinkRequest> | undefined): boolean {
    return proto3.util.equals(IdentitySetConfigurationLinkRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.IdentitySetConfigurationLinkResponse
 */
export class IdentitySetConfigurationLinkResponse extends Message<IdentitySetConfigurationLinkResponse> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Identity.ApiKey api_key = 1;
   */
  apiKey?: Identity_ApiKey;

  constructor(data?: PartialMessage<IdentitySetConfigurationLinkResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.IdentitySetConfigurationLinkResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "api_key", kind: "message", T: Identity_ApiKey },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IdentitySetConfigurationLinkResponse {
    return new IdentitySetConfigurationLinkResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IdentitySetConfigurationLinkResponse {
    return new IdentitySetConfigurationLinkResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IdentitySetConfigurationLinkResponse {
    return new IdentitySetConfigurationLinkResponse().fromJsonString(jsonString, options);
  }

  static equals(a: IdentitySetConfigurationLinkResponse | PlainMessage<IdentitySetConfigurationLinkResponse> | undefined, b: IdentitySetConfigurationLinkResponse | PlainMessage<IdentitySetConfigurationLinkResponse> | undefined): boolean {
    return proto3.util.equals(IdentitySetConfigurationLinkResponse, a, b);
  }
}

