// @generated by protoc-gen-es v2.6.0 with parameter "target=ts"
// @generated from file olvid/daemon/command/v1/identity_commands.proto (package olvid.daemon.command.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Identity, Identity_ApiKey, IdentityDetails } from "../../datatypes/v1/identity_pb";
import { file_olvid_daemon_datatypes_v1_identity } from "../../datatypes/v1/identity_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file olvid/daemon/command/v1/identity_commands.proto.
 */
export const file_olvid_daemon_command_v1_identity_commands: GenFile = /*@__PURE__*/
  fileDesc("Ci9vbHZpZC9kYWVtb24vY29tbWFuZC92MS9pZGVudGl0eV9jb21tYW5kcy5wcm90bxIXb2x2aWQuZGFlbW9uLmNvbW1hbmQudjEiFAoSSWRlbnRpdHlHZXRSZXF1ZXN0IkwKE0lkZW50aXR5R2V0UmVzcG9uc2USNQoIaWRlbnRpdHkYASABKAsyIy5vbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxLklkZW50aXR5IiMKIUlkZW50aXR5R2V0Qnl0ZXNJZGVudGlmaWVyUmVxdWVzdCI4CiJJZGVudGl0eUdldEJ5dGVzSWRlbnRpZmllclJlc3BvbnNlEhIKCmlkZW50aWZpZXIYASABKAwiIgogSWRlbnRpdHlHZXRJbnZpdGF0aW9uTGlua1JlcXVlc3QiPAohSWRlbnRpdHlHZXRJbnZpdGF0aW9uTGlua1Jlc3BvbnNlEhcKD2ludml0YXRpb25fbGluaxgBIAEoCSJfChxJZGVudGl0eVVwZGF0ZURldGFpbHNSZXF1ZXN0Ej8KC25ld19kZXRhaWxzGAIgASgLMioub2x2aWQuZGFlbW9uLmRhdGF0eXBlcy52MS5JZGVudGl0eURldGFpbHMiHwodSWRlbnRpdHlVcGRhdGVEZXRhaWxzUmVzcG9uc2UiHAoaSWRlbnRpdHlSZW1vdmVQaG90b1JlcXVlc3QiHQobSWRlbnRpdHlSZW1vdmVQaG90b1Jlc3BvbnNlIkYKH0lkZW50aXR5U2V0UGhvdG9SZXF1ZXN0TWV0YWRhdGESEAoIZmlsZW5hbWUYASABKAkSEQoJZmlsZV9zaXplGAIgASgEIoUBChdJZGVudGl0eVNldFBob3RvUmVxdWVzdBJMCghtZXRhZGF0YRgBIAEoCzI4Lm9sdmlkLmRhZW1vbi5jb21tYW5kLnYxLklkZW50aXR5U2V0UGhvdG9SZXF1ZXN0TWV0YWRhdGFIABIRCgdwYXlsb2FkGAIgASgMSABCCQoHcmVxdWVzdCIaChhJZGVudGl0eVNldFBob3RvUmVzcG9uc2UiHgocSWRlbnRpdHlEb3dubG9hZFBob3RvUmVxdWVzdCIuCh1JZGVudGl0eURvd25sb2FkUGhvdG9SZXNwb25zZRINCgVwaG90bxgBIAEoDCI5ChtJZGVudGl0eUtleWNsb2FrQmluZFJlcXVlc3QSGgoSY29uZmlndXJhdGlvbl9saW5rGAEgASgJIh4KHElkZW50aXR5S2V5Y2xvYWtCaW5kUmVzcG9uc2UiHwodSWRlbnRpdHlLZXljbG9ha1VuYmluZFJlcXVlc3QiIAoeSWRlbnRpdHlLZXljbG9ha1VuYmluZFJlc3BvbnNlIisKGElkZW50aXR5U2V0QXBpS2V5UmVxdWVzdBIPCgdhcGlfa2V5GAEgASgJIlgKGUlkZW50aXR5U2V0QXBpS2V5UmVzcG9uc2USOwoHYXBpX2tleRgBIAEoCzIqLm9sdmlkLmRhZW1vbi5kYXRhdHlwZXMudjEuSWRlbnRpdHkuQXBpS2V5IkEKI0lkZW50aXR5U2V0Q29uZmlndXJhdGlvbkxpbmtSZXF1ZXN0EhoKEmNvbmZpZ3VyYXRpb25fbGluaxgBIAEoCSJjCiRJZGVudGl0eVNldENvbmZpZ3VyYXRpb25MaW5rUmVzcG9uc2USOwoHYXBpX2tleRgBIAEoCzIqLm9sdmlkLmRhZW1vbi5kYXRhdHlwZXMudjEuSWRlbnRpdHkuQXBpS2V5QjUKIGlvLm9sdmlkLmRlc2t0b3AuZGFlbW9uLnByb3RvYnVmUAFaD29sdmlkLmlvL2RhZW1vbmIGcHJvdG8z", [file_olvid_daemon_datatypes_v1_identity]);

/**
 *
 * * IdentityGet
 *
 * @generated from message olvid.daemon.command.v1.IdentityGetRequest
 */
export type IdentityGetRequest = Message<"olvid.daemon.command.v1.IdentityGetRequest"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityGetRequest.
 * Use `create(IdentityGetRequestSchema)` to create a new message.
 */
export const IdentityGetRequestSchema: GenMessage<IdentityGetRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 0);

/**
 * @generated from message olvid.daemon.command.v1.IdentityGetResponse
 */
export type IdentityGetResponse = Message<"olvid.daemon.command.v1.IdentityGetResponse"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Identity identity = 1;
   */
  identity?: Identity;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityGetResponse.
 * Use `create(IdentityGetResponseSchema)` to create a new message.
 */
export const IdentityGetResponseSchema: GenMessage<IdentityGetResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 1);

/**
 *
 * * IdentityGetBytesIdentifier
 *
 * @generated from message olvid.daemon.command.v1.IdentityGetBytesIdentifierRequest
 */
export type IdentityGetBytesIdentifierRequest = Message<"olvid.daemon.command.v1.IdentityGetBytesIdentifierRequest"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityGetBytesIdentifierRequest.
 * Use `create(IdentityGetBytesIdentifierRequestSchema)` to create a new message.
 */
export const IdentityGetBytesIdentifierRequestSchema: GenMessage<IdentityGetBytesIdentifierRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 2);

/**
 * @generated from message olvid.daemon.command.v1.IdentityGetBytesIdentifierResponse
 */
export type IdentityGetBytesIdentifierResponse = Message<"olvid.daemon.command.v1.IdentityGetBytesIdentifierResponse"> & {
  /**
   * @generated from field: bytes identifier = 1;
   */
  identifier: Uint8Array;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityGetBytesIdentifierResponse.
 * Use `create(IdentityGetBytesIdentifierResponseSchema)` to create a new message.
 */
export const IdentityGetBytesIdentifierResponseSchema: GenMessage<IdentityGetBytesIdentifierResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 3);

/**
 *
 * * IdentityGetInvitationLink
 *
 * @generated from message olvid.daemon.command.v1.IdentityGetInvitationLinkRequest
 */
export type IdentityGetInvitationLinkRequest = Message<"olvid.daemon.command.v1.IdentityGetInvitationLinkRequest"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityGetInvitationLinkRequest.
 * Use `create(IdentityGetInvitationLinkRequestSchema)` to create a new message.
 */
export const IdentityGetInvitationLinkRequestSchema: GenMessage<IdentityGetInvitationLinkRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 4);

/**
 * @generated from message olvid.daemon.command.v1.IdentityGetInvitationLinkResponse
 */
export type IdentityGetInvitationLinkResponse = Message<"olvid.daemon.command.v1.IdentityGetInvitationLinkResponse"> & {
  /**
   * @generated from field: string invitation_link = 1;
   */
  invitationLink: string;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityGetInvitationLinkResponse.
 * Use `create(IdentityGetInvitationLinkResponseSchema)` to create a new message.
 */
export const IdentityGetInvitationLinkResponseSchema: GenMessage<IdentityGetInvitationLinkResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 5);

/**
 *
 * * IdentityUpdateDetails
 *
 * @generated from message olvid.daemon.command.v1.IdentityUpdateDetailsRequest
 */
export type IdentityUpdateDetailsRequest = Message<"olvid.daemon.command.v1.IdentityUpdateDetailsRequest"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.IdentityDetails new_details = 2;
   */
  newDetails?: IdentityDetails;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityUpdateDetailsRequest.
 * Use `create(IdentityUpdateDetailsRequestSchema)` to create a new message.
 */
export const IdentityUpdateDetailsRequestSchema: GenMessage<IdentityUpdateDetailsRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 6);

/**
 * @generated from message olvid.daemon.command.v1.IdentityUpdateDetailsResponse
 */
export type IdentityUpdateDetailsResponse = Message<"olvid.daemon.command.v1.IdentityUpdateDetailsResponse"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityUpdateDetailsResponse.
 * Use `create(IdentityUpdateDetailsResponseSchema)` to create a new message.
 */
export const IdentityUpdateDetailsResponseSchema: GenMessage<IdentityUpdateDetailsResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 7);

/**
 *
 * * IdentityRemovePhoto
 *
 * @generated from message olvid.daemon.command.v1.IdentityRemovePhotoRequest
 */
export type IdentityRemovePhotoRequest = Message<"olvid.daemon.command.v1.IdentityRemovePhotoRequest"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityRemovePhotoRequest.
 * Use `create(IdentityRemovePhotoRequestSchema)` to create a new message.
 */
export const IdentityRemovePhotoRequestSchema: GenMessage<IdentityRemovePhotoRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 8);

/**
 * @generated from message olvid.daemon.command.v1.IdentityRemovePhotoResponse
 */
export type IdentityRemovePhotoResponse = Message<"olvid.daemon.command.v1.IdentityRemovePhotoResponse"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityRemovePhotoResponse.
 * Use `create(IdentityRemovePhotoResponseSchema)` to create a new message.
 */
export const IdentityRemovePhotoResponseSchema: GenMessage<IdentityRemovePhotoResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 9);

/**
 *
 * * IdentitySetPhoto
 *
 * @generated from message olvid.daemon.command.v1.IdentitySetPhotoRequestMetadata
 */
export type IdentitySetPhotoRequestMetadata = Message<"olvid.daemon.command.v1.IdentitySetPhotoRequestMetadata"> & {
  /**
   * @generated from field: string filename = 1;
   */
  filename: string;

  /**
   * @generated from field: uint64 file_size = 2;
   */
  fileSize: bigint;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentitySetPhotoRequestMetadata.
 * Use `create(IdentitySetPhotoRequestMetadataSchema)` to create a new message.
 */
export const IdentitySetPhotoRequestMetadataSchema: GenMessage<IdentitySetPhotoRequestMetadata> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 10);

/**
 * @generated from message olvid.daemon.command.v1.IdentitySetPhotoRequest
 */
export type IdentitySetPhotoRequest = Message<"olvid.daemon.command.v1.IdentitySetPhotoRequest"> & {
  /**
   * @generated from oneof olvid.daemon.command.v1.IdentitySetPhotoRequest.request
   */
  request: {
    /**
     * @generated from field: olvid.daemon.command.v1.IdentitySetPhotoRequestMetadata metadata = 1;
     */
    value: IdentitySetPhotoRequestMetadata;
    case: "metadata";
  } | {
    /**
     * @generated from field: bytes payload = 2;
     */
    value: Uint8Array;
    case: "payload";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message olvid.daemon.command.v1.IdentitySetPhotoRequest.
 * Use `create(IdentitySetPhotoRequestSchema)` to create a new message.
 */
export const IdentitySetPhotoRequestSchema: GenMessage<IdentitySetPhotoRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 11);

/**
 * @generated from message olvid.daemon.command.v1.IdentitySetPhotoResponse
 */
export type IdentitySetPhotoResponse = Message<"olvid.daemon.command.v1.IdentitySetPhotoResponse"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentitySetPhotoResponse.
 * Use `create(IdentitySetPhotoResponseSchema)` to create a new message.
 */
export const IdentitySetPhotoResponseSchema: GenMessage<IdentitySetPhotoResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 12);

/**
 *
 * * IdentityDownloadPhoto
 *
 * @generated from message olvid.daemon.command.v1.IdentityDownloadPhotoRequest
 */
export type IdentityDownloadPhotoRequest = Message<"olvid.daemon.command.v1.IdentityDownloadPhotoRequest"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityDownloadPhotoRequest.
 * Use `create(IdentityDownloadPhotoRequestSchema)` to create a new message.
 */
export const IdentityDownloadPhotoRequestSchema: GenMessage<IdentityDownloadPhotoRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 13);

/**
 * @generated from message olvid.daemon.command.v1.IdentityDownloadPhotoResponse
 */
export type IdentityDownloadPhotoResponse = Message<"olvid.daemon.command.v1.IdentityDownloadPhotoResponse"> & {
  /**
   * @generated from field: bytes photo = 1;
   */
  photo: Uint8Array;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityDownloadPhotoResponse.
 * Use `create(IdentityDownloadPhotoResponseSchema)` to create a new message.
 */
export const IdentityDownloadPhotoResponseSchema: GenMessage<IdentityDownloadPhotoResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 14);

/**
 *
 * * IdentityKeycloakBind
 *
 * @generated from message olvid.daemon.command.v1.IdentityKeycloakBindRequest
 */
export type IdentityKeycloakBindRequest = Message<"olvid.daemon.command.v1.IdentityKeycloakBindRequest"> & {
  /**
   * @generated from field: string configuration_link = 1;
   */
  configurationLink: string;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityKeycloakBindRequest.
 * Use `create(IdentityKeycloakBindRequestSchema)` to create a new message.
 */
export const IdentityKeycloakBindRequestSchema: GenMessage<IdentityKeycloakBindRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 15);

/**
 * @generated from message olvid.daemon.command.v1.IdentityKeycloakBindResponse
 */
export type IdentityKeycloakBindResponse = Message<"olvid.daemon.command.v1.IdentityKeycloakBindResponse"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityKeycloakBindResponse.
 * Use `create(IdentityKeycloakBindResponseSchema)` to create a new message.
 */
export const IdentityKeycloakBindResponseSchema: GenMessage<IdentityKeycloakBindResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 16);

/**
 *
 * * IdentityKeycloakUnbind
 *
 * @generated from message olvid.daemon.command.v1.IdentityKeycloakUnbindRequest
 */
export type IdentityKeycloakUnbindRequest = Message<"olvid.daemon.command.v1.IdentityKeycloakUnbindRequest"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityKeycloakUnbindRequest.
 * Use `create(IdentityKeycloakUnbindRequestSchema)` to create a new message.
 */
export const IdentityKeycloakUnbindRequestSchema: GenMessage<IdentityKeycloakUnbindRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 17);

/**
 * @generated from message olvid.daemon.command.v1.IdentityKeycloakUnbindResponse
 */
export type IdentityKeycloakUnbindResponse = Message<"olvid.daemon.command.v1.IdentityKeycloakUnbindResponse"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityKeycloakUnbindResponse.
 * Use `create(IdentityKeycloakUnbindResponseSchema)` to create a new message.
 */
export const IdentityKeycloakUnbindResponseSchema: GenMessage<IdentityKeycloakUnbindResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 18);

/**
 *
 * * IdentitySetApiKey
 *
 * @generated from message olvid.daemon.command.v1.IdentitySetApiKeyRequest
 */
export type IdentitySetApiKeyRequest = Message<"olvid.daemon.command.v1.IdentitySetApiKeyRequest"> & {
  /**
   * @generated from field: string api_key = 1;
   */
  apiKey: string;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentitySetApiKeyRequest.
 * Use `create(IdentitySetApiKeyRequestSchema)` to create a new message.
 */
export const IdentitySetApiKeyRequestSchema: GenMessage<IdentitySetApiKeyRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 19);

/**
 * @generated from message olvid.daemon.command.v1.IdentitySetApiKeyResponse
 */
export type IdentitySetApiKeyResponse = Message<"olvid.daemon.command.v1.IdentitySetApiKeyResponse"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Identity.ApiKey api_key = 1;
   */
  apiKey?: Identity_ApiKey;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentitySetApiKeyResponse.
 * Use `create(IdentitySetApiKeyResponseSchema)` to create a new message.
 */
export const IdentitySetApiKeyResponseSchema: GenMessage<IdentitySetApiKeyResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 20);

/**
 *
 * * IdentitySetConfigurationLink
 *
 * @generated from message olvid.daemon.command.v1.IdentitySetConfigurationLinkRequest
 */
export type IdentitySetConfigurationLinkRequest = Message<"olvid.daemon.command.v1.IdentitySetConfigurationLinkRequest"> & {
  /**
   * @generated from field: string configuration_link = 1;
   */
  configurationLink: string;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentitySetConfigurationLinkRequest.
 * Use `create(IdentitySetConfigurationLinkRequestSchema)` to create a new message.
 */
export const IdentitySetConfigurationLinkRequestSchema: GenMessage<IdentitySetConfigurationLinkRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 21);

/**
 * @generated from message olvid.daemon.command.v1.IdentitySetConfigurationLinkResponse
 */
export type IdentitySetConfigurationLinkResponse = Message<"olvid.daemon.command.v1.IdentitySetConfigurationLinkResponse"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Identity.ApiKey api_key = 1;
   */
  apiKey?: Identity_ApiKey;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentitySetConfigurationLinkResponse.
 * Use `create(IdentitySetConfigurationLinkResponseSchema)` to create a new message.
 */
export const IdentitySetConfigurationLinkResponseSchema: GenMessage<IdentitySetConfigurationLinkResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 22);

