// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file olvid/daemon/command/v1/identity_commands.proto (package olvid.daemon.command.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Identity, Identity_ApiKey, IdentityDetails } from "../../datatypes/v1/identity_pb";
import { file_olvid_daemon_datatypes_v1_identity } from "../../datatypes/v1/identity_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file olvid/daemon/command/v1/identity_commands.proto.
 */
export const file_olvid_daemon_command_v1_identity_commands: GenFile = /*@__PURE__*/
  fileDesc("Ci9vbHZpZC9kYWVtb24vY29tbWFuZC92MS9pZGVudGl0eV9jb21tYW5kcy5wcm90bxIXb2x2aWQuZGFlbW9uLmNvbW1hbmQudjEiFAoSSWRlbnRpdHlHZXRSZXF1ZXN0IkwKE0lkZW50aXR5R2V0UmVzcG9uc2USNQoIaWRlbnRpdHkYASABKAsyIy5vbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxLklkZW50aXR5IiMKIUlkZW50aXR5R2V0Qnl0ZXNJZGVudGlmaWVyUmVxdWVzdCI4CiJJZGVudGl0eUdldEJ5dGVzSWRlbnRpZmllclJlc3BvbnNlEhIKCmlkZW50aWZpZXIYASABKAwiIgogSWRlbnRpdHlHZXRJbnZpdGF0aW9uTGlua1JlcXVlc3QiPAohSWRlbnRpdHlHZXRJbnZpdGF0aW9uTGlua1Jlc3BvbnNlEhcKD2ludml0YXRpb25fbGluaxgBIAEoCSJfChxJZGVudGl0eVVwZGF0ZURldGFpbHNSZXF1ZXN0Ej8KC25ld19kZXRhaWxzGAIgASgLMioub2x2aWQuZGFlbW9uLmRhdGF0eXBlcy52MS5JZGVudGl0eURldGFpbHMiHwodSWRlbnRpdHlVcGRhdGVEZXRhaWxzUmVzcG9uc2UiRgofSWRlbnRpdHlTZXRQaG90b1JlcXVlc3RNZXRhZGF0YRIQCghmaWxlbmFtZRgBIAEoCRIRCglmaWxlX3NpemUYAiABKAQihQEKF0lkZW50aXR5U2V0UGhvdG9SZXF1ZXN0EkwKCG1ldGFkYXRhGAEgASgLMjgub2x2aWQuZGFlbW9uLmNvbW1hbmQudjEuSWRlbnRpdHlTZXRQaG90b1JlcXVlc3RNZXRhZGF0YUgAEhEKB3BheWxvYWQYAiABKAxIAEIJCgdyZXF1ZXN0IhoKGElkZW50aXR5U2V0UGhvdG9SZXNwb25zZSIeChxJZGVudGl0eURvd25sb2FkUGhvdG9SZXF1ZXN0Ii4KHUlkZW50aXR5RG93bmxvYWRQaG90b1Jlc3BvbnNlEg0KBXBob3RvGAEgASgMIhwKGklkZW50aXR5UmVtb3ZlUGhvdG9SZXF1ZXN0Ih0KG0lkZW50aXR5UmVtb3ZlUGhvdG9SZXNwb25zZSIgCh5JZGVudGl0eUdldEFwaUtleVN0YXR1c1JlcXVlc3QiXgofSWRlbnRpdHlHZXRBcGlLZXlTdGF0dXNSZXNwb25zZRI7CgdhcGlfa2V5GAEgASgLMioub2x2aWQuZGFlbW9uLmRhdGF0eXBlcy52MS5JZGVudGl0eS5BcGlLZXkiKwoYSWRlbnRpdHlTZXRBcGlLZXlSZXF1ZXN0Eg8KB2FwaV9rZXkYASABKAkiWAoZSWRlbnRpdHlTZXRBcGlLZXlSZXNwb25zZRI7CgdhcGlfa2V5GAEgASgLMioub2x2aWQuZGFlbW9uLmRhdGF0eXBlcy52MS5JZGVudGl0eS5BcGlLZXkiQQojSWRlbnRpdHlTZXRDb25maWd1cmF0aW9uTGlua1JlcXVlc3QSGgoSY29uZmlndXJhdGlvbl9saW5rGAEgASgJImMKJElkZW50aXR5U2V0Q29uZmlndXJhdGlvbkxpbmtSZXNwb25zZRI7CgdhcGlfa2V5GAEgASgLMioub2x2aWQuZGFlbW9uLmRhdGF0eXBlcy52MS5JZGVudGl0eS5BcGlLZXlCNQogaW8ub2x2aWQuZGVza3RvcC5kYWVtb24ucHJvdG9idWZQAVoPb2x2aWQuaW8vZGFlbW9uYgZwcm90bzM", [file_olvid_daemon_datatypes_v1_identity]);

/**
 *
 * * IdentityGet
 * * Get your identity details.
 * *
 * * **Error codes**:
 * * `UNAUTHENTICATED`: client key is invalid.
 * * `INTERNAL`
 *
 * @generated from message olvid.daemon.command.v1.IdentityGetRequest
 */
export type IdentityGetRequest = Message<"olvid.daemon.command.v1.IdentityGetRequest"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityGetRequest.
 * Use `create(IdentityGetRequestSchema)` to create a new message.
 */
export const IdentityGetRequestSchema: GenMessage<IdentityGetRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 0);

/**
 * @generated from message olvid.daemon.command.v1.IdentityGetResponse
 */
export type IdentityGetResponse = Message<"olvid.daemon.command.v1.IdentityGetResponse"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Identity identity = 1;
   */
  identity?: Identity;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityGetResponse.
 * Use `create(IdentityGetResponseSchema)` to create a new message.
 */
export const IdentityGetResponseSchema: GenMessage<IdentityGetResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 1);

/**
 *
 * * IdentityGetBytesIdentifier
 * * Get your Olvid identity as bytes.
 * * This is useful to have a long term identifier for an identity, backup-proof, and common to any device.
 * *
 * * **Error codes**:
 * * `NOT_FOUND`: identity not found.
 * * `UNAUTHENTICATED`: client key is invalid.
 * * `INTERNAL`
 *
 * @generated from message olvid.daemon.command.v1.IdentityGetBytesIdentifierRequest
 */
export type IdentityGetBytesIdentifierRequest = Message<"olvid.daemon.command.v1.IdentityGetBytesIdentifierRequest"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityGetBytesIdentifierRequest.
 * Use `create(IdentityGetBytesIdentifierRequestSchema)` to create a new message.
 */
export const IdentityGetBytesIdentifierRequestSchema: GenMessage<IdentityGetBytesIdentifierRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 2);

/**
 * @generated from message olvid.daemon.command.v1.IdentityGetBytesIdentifierResponse
 */
export type IdentityGetBytesIdentifierResponse = Message<"olvid.daemon.command.v1.IdentityGetBytesIdentifierResponse"> & {
  /**
   * @generated from field: bytes identifier = 1;
   */
  identifier: Uint8Array;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityGetBytesIdentifierResponse.
 * Use `create(IdentityGetBytesIdentifierResponseSchema)` to create a new message.
 */
export const IdentityGetBytesIdentifierResponseSchema: GenMessage<IdentityGetBytesIdentifierResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 3);

/**
 *
 * * IdentityGetInvitationLink
 * * Get your invitation link. This link can be sent to other Olvid users to let them send you an invitation.
 * * Invitation links can be opened with any Olvid application or opened in a web browser to show a QR code to scan.
 * *
 * * **Error codes**:
 * * `NOT_FOUND`: identity not found.
 * * `UNAUTHENTICATED`: client key is invalid.
 * * `INTERNAL`
 *
 * @generated from message olvid.daemon.command.v1.IdentityGetInvitationLinkRequest
 */
export type IdentityGetInvitationLinkRequest = Message<"olvid.daemon.command.v1.IdentityGetInvitationLinkRequest"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityGetInvitationLinkRequest.
 * Use `create(IdentityGetInvitationLinkRequestSchema)` to create a new message.
 */
export const IdentityGetInvitationLinkRequestSchema: GenMessage<IdentityGetInvitationLinkRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 4);

/**
 * @generated from message olvid.daemon.command.v1.IdentityGetInvitationLinkResponse
 */
export type IdentityGetInvitationLinkResponse = Message<"olvid.daemon.command.v1.IdentityGetInvitationLinkResponse"> & {
  /**
   * @generated from field: string invitation_link = 1;
   */
  invitationLink: string;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityGetInvitationLinkResponse.
 * Use `create(IdentityGetInvitationLinkResponseSchema)` to create a new message.
 */
export const IdentityGetInvitationLinkResponseSchema: GenMessage<IdentityGetInvitationLinkResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 5);

/**
 *
 * * IdentityUpdateDetails
 * * Update your Olvid identity details (first name, last name, company and position).
 * * At least one field in first and last name must be non empty.
 * * Your details will be visible by your contacts, and your display name is computed from these details.
 * * Details for a keycloak managed identity cannot be updated.
 * *
 * * **Error codes**:
 * * `NOT_FOUND`: identity not found.
 * * `INVALID_ARGUMENT`: at least one of first name and last name must be non empty / cannot update a keycloak managed identity.
 * * `UNAUTHENTICATED`: client key is invalid.
 *
 * @generated from message olvid.daemon.command.v1.IdentityUpdateDetailsRequest
 */
export type IdentityUpdateDetailsRequest = Message<"olvid.daemon.command.v1.IdentityUpdateDetailsRequest"> & {
  /**
   * your new identity details
   *
   * @generated from field: olvid.daemon.datatypes.v1.IdentityDetails new_details = 2;
   */
  newDetails?: IdentityDetails;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityUpdateDetailsRequest.
 * Use `create(IdentityUpdateDetailsRequestSchema)` to create a new message.
 */
export const IdentityUpdateDetailsRequestSchema: GenMessage<IdentityUpdateDetailsRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 6);

/**
 * @generated from message olvid.daemon.command.v1.IdentityUpdateDetailsResponse
 */
export type IdentityUpdateDetailsResponse = Message<"olvid.daemon.command.v1.IdentityUpdateDetailsResponse"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityUpdateDetailsResponse.
 * Use `create(IdentityUpdateDetailsResponseSchema)` to create a new message.
 */
export const IdentityUpdateDetailsResponseSchema: GenMessage<IdentityUpdateDetailsResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 7);

/**
 *
 * * IdentitySetPhoto
 * * Set a profile picture for your identity.
 * * This picture will be visible by your contacts.
 * * The photo can be jpeg or png but will be converted to jpeg and resolution will be limited to 1080x1080.
 * *
 * * **Error codes**:
 * * `NOT_FOUND`: identity not found.
 * * `UNAUTHENTICATED`: client key is invalid.
 * * `INTERNAL`
 *
 * @generated from message olvid.daemon.command.v1.IdentitySetPhotoRequestMetadata
 */
export type IdentitySetPhotoRequestMetadata = Message<"olvid.daemon.command.v1.IdentitySetPhotoRequestMetadata"> & {
  /**
   * @generated from field: string filename = 1;
   */
  filename: string;

  /**
   * @generated from field: uint64 file_size = 2;
   */
  fileSize: bigint;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentitySetPhotoRequestMetadata.
 * Use `create(IdentitySetPhotoRequestMetadataSchema)` to create a new message.
 */
export const IdentitySetPhotoRequestMetadataSchema: GenMessage<IdentitySetPhotoRequestMetadata> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 8);

/**
 * @generated from message olvid.daemon.command.v1.IdentitySetPhotoRequest
 */
export type IdentitySetPhotoRequest = Message<"olvid.daemon.command.v1.IdentitySetPhotoRequest"> & {
  /**
   * @generated from oneof olvid.daemon.command.v1.IdentitySetPhotoRequest.request
   */
  request: {
    /**
     * @generated from field: olvid.daemon.command.v1.IdentitySetPhotoRequestMetadata metadata = 1;
     */
    value: IdentitySetPhotoRequestMetadata;
    case: "metadata";
  } | {
    /**
     * @generated from field: bytes payload = 2;
     */
    value: Uint8Array;
    case: "payload";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message olvid.daemon.command.v1.IdentitySetPhotoRequest.
 * Use `create(IdentitySetPhotoRequestSchema)` to create a new message.
 */
export const IdentitySetPhotoRequestSchema: GenMessage<IdentitySetPhotoRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 9);

/**
 * @generated from message olvid.daemon.command.v1.IdentitySetPhotoResponse
 */
export type IdentitySetPhotoResponse = Message<"olvid.daemon.command.v1.IdentitySetPhotoResponse"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentitySetPhotoResponse.
 * Use `create(IdentitySetPhotoResponseSchema)` to create a new message.
 */
export const IdentitySetPhotoResponseSchema: GenMessage<IdentitySetPhotoResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 10);

/**
 *
 * * IdentityDownloadPhoto
 * * Download your current identity picture.
 * * Pictures are always jpeg files with a maximum of 1080x1080 resolution.
 * *
 * * **Error codes**:
 * * `NOT_FOUND`: identity not found.
 * * `UNAUTHENTICATED`: client key is invalid.
 * * `INTERNAL`
 *
 * @generated from message olvid.daemon.command.v1.IdentityDownloadPhotoRequest
 */
export type IdentityDownloadPhotoRequest = Message<"olvid.daemon.command.v1.IdentityDownloadPhotoRequest"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityDownloadPhotoRequest.
 * Use `create(IdentityDownloadPhotoRequestSchema)` to create a new message.
 */
export const IdentityDownloadPhotoRequestSchema: GenMessage<IdentityDownloadPhotoRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 11);

/**
 * @generated from message olvid.daemon.command.v1.IdentityDownloadPhotoResponse
 */
export type IdentityDownloadPhotoResponse = Message<"olvid.daemon.command.v1.IdentityDownloadPhotoResponse"> & {
  /**
   * @generated from field: bytes photo = 1;
   */
  photo: Uint8Array;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityDownloadPhotoResponse.
 * Use `create(IdentityDownloadPhotoResponseSchema)` to create a new message.
 */
export const IdentityDownloadPhotoResponseSchema: GenMessage<IdentityDownloadPhotoResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 12);

/**
 *
 * * IdentityRemovePhoto
 * * Remove your current identity picture.
 * * The automatically generated identity image will be used instead.
 * *
 * * **Error codes**:
 * * `NOT_FOUND`: identity not found.
 * * `UNAUTHENTICATED`: client key is invalid.
 * * `INTERNAL`
 *
 * @generated from message olvid.daemon.command.v1.IdentityRemovePhotoRequest
 */
export type IdentityRemovePhotoRequest = Message<"olvid.daemon.command.v1.IdentityRemovePhotoRequest"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityRemovePhotoRequest.
 * Use `create(IdentityRemovePhotoRequestSchema)` to create a new message.
 */
export const IdentityRemovePhotoRequestSchema: GenMessage<IdentityRemovePhotoRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 13);

/**
 * @generated from message olvid.daemon.command.v1.IdentityRemovePhotoResponse
 */
export type IdentityRemovePhotoResponse = Message<"olvid.daemon.command.v1.IdentityRemovePhotoResponse"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityRemovePhotoResponse.
 * Use `create(IdentityRemovePhotoResponseSchema)` to create a new message.
 */
export const IdentityRemovePhotoResponseSchema: GenMessage<IdentityRemovePhotoResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 14);

/**
 *
 * * IdentityGetApiKeyStatus
 * * Check your current Olvid API key status.
 * * API keys allow an identity to initiate calls or to use multi device.
 * *
 * * **Error codes**:
 * * `UNAUTHENTICATED`: client key is invalid.
 *
 * @generated from message olvid.daemon.command.v1.IdentityGetApiKeyStatusRequest
 */
export type IdentityGetApiKeyStatusRequest = Message<"olvid.daemon.command.v1.IdentityGetApiKeyStatusRequest"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityGetApiKeyStatusRequest.
 * Use `create(IdentityGetApiKeyStatusRequestSchema)` to create a new message.
 */
export const IdentityGetApiKeyStatusRequestSchema: GenMessage<IdentityGetApiKeyStatusRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 15);

/**
 * @generated from message olvid.daemon.command.v1.IdentityGetApiKeyStatusResponse
 */
export type IdentityGetApiKeyStatusResponse = Message<"olvid.daemon.command.v1.IdentityGetApiKeyStatusResponse"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Identity.ApiKey api_key = 1;
   */
  apiKey?: Identity_ApiKey;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentityGetApiKeyStatusResponse.
 * Use `create(IdentityGetApiKeyStatusResponseSchema)` to create a new message.
 */
export const IdentityGetApiKeyStatusResponseSchema: GenMessage<IdentityGetApiKeyStatusResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 16);

/**
 *
 * * IdentitySetApiKey
 * * Manually set an Olvid api key.
 * * Olvid api keys are standard uuids.
 * *
 * * **Error codes**:
 * * `INVALID_ARGUMENT`: api key format is not valid.
 * * `UNAUTHENTICATED`: client key is invalid.
 *
 * @generated from message olvid.daemon.command.v1.IdentitySetApiKeyRequest
 */
export type IdentitySetApiKeyRequest = Message<"olvid.daemon.command.v1.IdentitySetApiKeyRequest"> & {
  /**
   * @generated from field: string api_key = 1;
   */
  apiKey: string;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentitySetApiKeyRequest.
 * Use `create(IdentitySetApiKeyRequestSchema)` to create a new message.
 */
export const IdentitySetApiKeyRequestSchema: GenMessage<IdentitySetApiKeyRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 17);

/**
 * @generated from message olvid.daemon.command.v1.IdentitySetApiKeyResponse
 */
export type IdentitySetApiKeyResponse = Message<"olvid.daemon.command.v1.IdentitySetApiKeyResponse"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Identity.ApiKey api_key = 1;
   */
  apiKey?: Identity_ApiKey;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentitySetApiKeyResponse.
 * Use `create(IdentitySetApiKeyResponseSchema)` to create a new message.
 */
export const IdentitySetApiKeyResponseSchema: GenMessage<IdentitySetApiKeyResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 18);

/**
 *
 * * IdentitySetConfigurationLink
 * * Set an Olvid configuration link with an api key.
 * *
 * * **Error codes**:
 * * `INVALID_ARGUMENT`: configuration link is invalid / configuration link is for another server.
 * * `UNAUTHENTICATED`: client key is invalid.
 *
 * @generated from message olvid.daemon.command.v1.IdentitySetConfigurationLinkRequest
 */
export type IdentitySetConfigurationLinkRequest = Message<"olvid.daemon.command.v1.IdentitySetConfigurationLinkRequest"> & {
  /**
   * @generated from field: string configuration_link = 1;
   */
  configurationLink: string;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentitySetConfigurationLinkRequest.
 * Use `create(IdentitySetConfigurationLinkRequestSchema)` to create a new message.
 */
export const IdentitySetConfigurationLinkRequestSchema: GenMessage<IdentitySetConfigurationLinkRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 19);

/**
 * @generated from message olvid.daemon.command.v1.IdentitySetConfigurationLinkResponse
 */
export type IdentitySetConfigurationLinkResponse = Message<"olvid.daemon.command.v1.IdentitySetConfigurationLinkResponse"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Identity.ApiKey api_key = 1;
   */
  apiKey?: Identity_ApiKey;
};

/**
 * Describes the message olvid.daemon.command.v1.IdentitySetConfigurationLinkResponse.
 * Use `create(IdentitySetConfigurationLinkResponseSchema)` to create a new message.
 */
export const IdentitySetConfigurationLinkResponseSchema: GenMessage<IdentitySetConfigurationLinkResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_identity_commands, 20);

