// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file olvid/daemon/command/v1/invitation_commands.proto (package olvid.daemon.command.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Invitation, InvitationFilter } from "../../datatypes/v1/invitation_pb";
import { file_olvid_daemon_datatypes_v1_invitation } from "../../datatypes/v1/invitation_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file olvid/daemon/command/v1/invitation_commands.proto.
 */
export const file_olvid_daemon_command_v1_invitation_commands: GenFile = /*@__PURE__*/
  fileDesc("CjFvbHZpZC9kYWVtb24vY29tbWFuZC92MS9pbnZpdGF0aW9uX2NvbW1hbmRzLnByb3RvEhdvbHZpZC5kYWVtb24uY29tbWFuZC52MSJkChVJbnZpdGF0aW9uTGlzdFJlcXVlc3QSQAoGZmlsdGVyGAEgASgLMisub2x2aWQuZGFlbW9uLmRhdGF0eXBlcy52MS5JbnZpdGF0aW9uRmlsdGVySACIAQFCCQoHX2ZpbHRlciJUChZJbnZpdGF0aW9uTGlzdFJlc3BvbnNlEjoKC2ludml0YXRpb25zGAEgAygLMiUub2x2aWQuZGFlbW9uLmRhdGF0eXBlcy52MS5JbnZpdGF0aW9uIi0KFEludml0YXRpb25HZXRSZXF1ZXN0EhUKDWludml0YXRpb25faWQYASABKAQiUgoVSW52aXRhdGlvbkdldFJlc3BvbnNlEjkKCmludml0YXRpb24YASABKAsyJS5vbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxLkludml0YXRpb24iLgoUSW52aXRhdGlvbk5ld1JlcXVlc3QSFgoOaW52aXRhdGlvbl91cmwYASABKAkiUgoVSW52aXRhdGlvbk5ld1Jlc3BvbnNlEjkKCmludml0YXRpb24YASABKAsyJS5vbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxLkludml0YXRpb24iMAoXSW52aXRhdGlvbkFjY2VwdFJlcXVlc3QSFQoNaW52aXRhdGlvbl9pZBgBIAEoBCIaChhJbnZpdGF0aW9uQWNjZXB0UmVzcG9uc2UiMQoYSW52aXRhdGlvbkRlY2xpbmVSZXF1ZXN0EhUKDWludml0YXRpb25faWQYASABKAQiGwoZSW52aXRhdGlvbkRlY2xpbmVSZXNwb25zZSI6ChRJbnZpdGF0aW9uU2FzUmVxdWVzdBIVCg1pbnZpdGF0aW9uX2lkGAEgASgEEgsKA3NhcxgCIAEoCSIXChVJbnZpdGF0aW9uU2FzUmVzcG9uc2UiMAoXSW52aXRhdGlvbkRlbGV0ZVJlcXVlc3QSFQoNaW52aXRhdGlvbl9pZBgBIAEoBCIaChhJbnZpdGF0aW9uRGVsZXRlUmVzcG9uc2VCNQogaW8ub2x2aWQuZGVza3RvcC5kYWVtb24ucHJvdG9idWZQAVoPb2x2aWQuaW8vZGFlbW9uYgZwcm90bzM", [file_olvid_daemon_datatypes_v1_invitation]);

/**
 *
 * * InvitationList
 * * List invitations for current identity.
 * * Pass a filter to select only invitations that match specific criteria.
 * *
 * * **Error codes**:
 * * `UNAUTHENTICATED`: client key is invalid.
 * * `INVALID_ARGUMENT`: invalid filter.
 * * `INTERNAL`
 *
 * @generated from message olvid.daemon.command.v1.InvitationListRequest
 */
export type InvitationListRequest = Message<"olvid.daemon.command.v1.InvitationListRequest"> & {
  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.InvitationFilter filter = 1;
   */
  filter?: InvitationFilter;
};

/**
 * Describes the message olvid.daemon.command.v1.InvitationListRequest.
 * Use `create(InvitationListRequestSchema)` to create a new message.
 */
export const InvitationListRequestSchema: GenMessage<InvitationListRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_invitation_commands, 0);

/**
 * @generated from message olvid.daemon.command.v1.InvitationListResponse
 */
export type InvitationListResponse = Message<"olvid.daemon.command.v1.InvitationListResponse"> & {
  /**
   * @generated from field: repeated olvid.daemon.datatypes.v1.Invitation invitations = 1;
   */
  invitations: Invitation[];
};

/**
 * Describes the message olvid.daemon.command.v1.InvitationListResponse.
 * Use `create(InvitationListResponseSchema)` to create a new message.
 */
export const InvitationListResponseSchema: GenMessage<InvitationListResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_invitation_commands, 1);

/**
 *
 * * InvitationGet
 * * Get invitation by id.
 * *
 * * **Error codes**:
 * * `NOT_FOUND`: invitation not found.
 * * `UNAUTHENTICATED`: client key is invalid.
 *
 * @generated from message olvid.daemon.command.v1.InvitationGetRequest
 */
export type InvitationGetRequest = Message<"olvid.daemon.command.v1.InvitationGetRequest"> & {
  /**
   * @generated from field: uint64 invitation_id = 1;
   */
  invitationId: bigint;
};

/**
 * Describes the message olvid.daemon.command.v1.InvitationGetRequest.
 * Use `create(InvitationGetRequestSchema)` to create a new message.
 */
export const InvitationGetRequestSchema: GenMessage<InvitationGetRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_invitation_commands, 2);

/**
 * @generated from message olvid.daemon.command.v1.InvitationGetResponse
 */
export type InvitationGetResponse = Message<"olvid.daemon.command.v1.InvitationGetResponse"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Invitation invitation = 1;
   */
  invitation?: Invitation;
};

/**
 * Describes the message olvid.daemon.command.v1.InvitationGetResponse.
 * Use `create(InvitationGetResponseSchema)` to create a new message.
 */
export const InvitationGetResponseSchema: GenMessage<InvitationGetResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_invitation_commands, 3);

/**
 *
 * * InvitationNew
 * * Send an invitation to another Olvid user using its invitation link.
 * * Invitation links start with https://invitation.olvid.io#.
 * * Sending an invitation will initiate an invitation protocol and create a new Invitation.
 * *
 * * **Error codes**:
 * * `INVALID_ARGUMENT`: you cannot invite yourself / invitation link is invalid.
 * * `UNAUTHENTICATED`: client key is invalid.
 * * `INTERNAL`
 *
 * @generated from message olvid.daemon.command.v1.InvitationNewRequest
 */
export type InvitationNewRequest = Message<"olvid.daemon.command.v1.InvitationNewRequest"> & {
  /**
   * @generated from field: string invitation_url = 1;
   */
  invitationUrl: string;
};

/**
 * Describes the message olvid.daemon.command.v1.InvitationNewRequest.
 * Use `create(InvitationNewRequestSchema)` to create a new message.
 */
export const InvitationNewRequestSchema: GenMessage<InvitationNewRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_invitation_commands, 4);

/**
 * @generated from message olvid.daemon.command.v1.InvitationNewResponse
 */
export type InvitationNewResponse = Message<"olvid.daemon.command.v1.InvitationNewResponse"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Invitation invitation = 1;
   */
  invitation?: Invitation;
};

/**
 * Describes the message olvid.daemon.command.v1.InvitationNewResponse.
 * Use `create(InvitationNewResponseSchema)` to create a new message.
 */
export const InvitationNewResponseSchema: GenMessage<InvitationNewResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_invitation_commands, 5);

/**
 *
 * * InvitationAccept
 * * Accept a pending invitation. This will allow protocol to continue.
 * * This command is only possible if `invitation.status` is one of the following:
 * *  - STATUS_INVITATION_WAIT_YOU_TO_ACCEPT
 * *  - STATUS_INTRODUCTION_WAIT_YOU_TO_ACCEPT
 * *  - STATUS_ONE_TO_ONE_INVITATION_WAIT_YOU_TO_ACCEPT
 * *  - STATUS_GROUP_INVITATION_WAIT_YOU_TO_ACCEPT
 * *
 * * **Error codes**:
 * * `NOT_FOUND`: invitation not found.
 * * `INVALID_ARGUMENT`: cannot accept an invitation with this status.
 * * `UNAUTHENTICATED`: client key is invalid.
 * * `INTERNAL`
 *
 * @generated from message olvid.daemon.command.v1.InvitationAcceptRequest
 */
export type InvitationAcceptRequest = Message<"olvid.daemon.command.v1.InvitationAcceptRequest"> & {
  /**
   * @generated from field: uint64 invitation_id = 1;
   */
  invitationId: bigint;
};

/**
 * Describes the message olvid.daemon.command.v1.InvitationAcceptRequest.
 * Use `create(InvitationAcceptRequestSchema)` to create a new message.
 */
export const InvitationAcceptRequestSchema: GenMessage<InvitationAcceptRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_invitation_commands, 6);

/**
 * @generated from message olvid.daemon.command.v1.InvitationAcceptResponse
 */
export type InvitationAcceptResponse = Message<"olvid.daemon.command.v1.InvitationAcceptResponse"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.InvitationAcceptResponse.
 * Use `create(InvitationAcceptResponseSchema)` to create a new message.
 */
export const InvitationAcceptResponseSchema: GenMessage<InvitationAcceptResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_invitation_commands, 7);

/**
 *
 * * InvitationDecline
 * * Decline a pending invitation. This will abort protocol.
 * * For invitation, introduction and one to one invitation the other user is not notified you declined the invitation.
 * * This command is only possible if `invitation.status` is one of the following:
 * *  - STATUS_INVITATION_WAIT_YOU_TO_ACCEPT
 * *  - STATUS_INTRODUCTION_WAIT_YOU_TO_ACCEPT
 * *  - STATUS_ONE_TO_ONE_INVITATION_WAIT_YOU_TO_ACCEPT
 * *  - STATUS_GROUP_INVITATION_WAIT_YOU_TO_ACCEPT
 * *
 * * **Error codes**:
 * * `NOT_FOUND`: invitation not found.
 * * `UNAUTHENTICATED`: client key is invalid.
 * * `INTERNAL`
 *
 * @generated from message olvid.daemon.command.v1.InvitationDeclineRequest
 */
export type InvitationDeclineRequest = Message<"olvid.daemon.command.v1.InvitationDeclineRequest"> & {
  /**
   * @generated from field: uint64 invitation_id = 1;
   */
  invitationId: bigint;
};

/**
 * Describes the message olvid.daemon.command.v1.InvitationDeclineRequest.
 * Use `create(InvitationDeclineRequestSchema)` to create a new message.
 */
export const InvitationDeclineRequestSchema: GenMessage<InvitationDeclineRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_invitation_commands, 8);

/**
 * @generated from message olvid.daemon.command.v1.InvitationDeclineResponse
 */
export type InvitationDeclineResponse = Message<"olvid.daemon.command.v1.InvitationDeclineResponse"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.InvitationDeclineResponse.
 * Use `create(InvitationDeclineResponseSchema)` to create a new message.
 */
export const InvitationDeclineResponseSchema: GenMessage<InvitationDeclineResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_invitation_commands, 9);

/**
 *
 * * InvitationSas
 * * Only possible if `invitation.status` is equal to STATUS_INVITATION_WAIT_YOU_FOR_SAS_EXCHANGE.
 * * Set the 4 digit code shown on your partner device.
 * *
 * * **Error codes**:
 * * `NOT_FOUND`: invitation not found.
 * * `INVALID_ARGUMENT`: unexpected invitation status.
 * * `UNAUTHENTICATED`: client key is invalid.
 *
 * @generated from message olvid.daemon.command.v1.InvitationSasRequest
 */
export type InvitationSasRequest = Message<"olvid.daemon.command.v1.InvitationSasRequest"> & {
  /**
   * @generated from field: uint64 invitation_id = 1;
   */
  invitationId: bigint;

  /**
   * 4 digit pin code shown on your partner device
   *
   * @generated from field: string sas = 2;
   */
  sas: string;
};

/**
 * Describes the message olvid.daemon.command.v1.InvitationSasRequest.
 * Use `create(InvitationSasRequestSchema)` to create a new message.
 */
export const InvitationSasRequestSchema: GenMessage<InvitationSasRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_invitation_commands, 10);

/**
 * @generated from message olvid.daemon.command.v1.InvitationSasResponse
 */
export type InvitationSasResponse = Message<"olvid.daemon.command.v1.InvitationSasResponse"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.InvitationSasResponse.
 * Use `create(InvitationSasResponseSchema)` to create a new message.
 */
export const InvitationSasResponseSchema: GenMessage<InvitationSasResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_invitation_commands, 11);

/**
 *
 * * InvitationDelete
 * * Abort the protocol associated to any invitation and delete this invitation.
 * *
 * * **Error codes**:
 * * `UNAUTHENTICATED`: client key is invalid.
 *
 * @generated from message olvid.daemon.command.v1.InvitationDeleteRequest
 */
export type InvitationDeleteRequest = Message<"olvid.daemon.command.v1.InvitationDeleteRequest"> & {
  /**
   * @generated from field: uint64 invitation_id = 1;
   */
  invitationId: bigint;
};

/**
 * Describes the message olvid.daemon.command.v1.InvitationDeleteRequest.
 * Use `create(InvitationDeleteRequestSchema)` to create a new message.
 */
export const InvitationDeleteRequestSchema: GenMessage<InvitationDeleteRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_invitation_commands, 12);

/**
 * @generated from message olvid.daemon.command.v1.InvitationDeleteResponse
 */
export type InvitationDeleteResponse = Message<"olvid.daemon.command.v1.InvitationDeleteResponse"> & {
};

/**
 * Describes the message olvid.daemon.command.v1.InvitationDeleteResponse.
 * Use `create(InvitationDeleteResponseSchema)` to create a new message.
 */
export const InvitationDeleteResponseSchema: GenMessage<InvitationDeleteResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_command_v1_invitation_commands, 13);

