// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file olvid/daemon/command/v1/keycloak_commands.proto (package olvid.daemon.command.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { KeycloakUser, KeycloakUserFilter } from "../../datatypes/v1/keycloak_pb.js";

/**
 *
 * * KeycloakUserList
 *
 * @generated from message olvid.daemon.command.v1.KeycloakUserListRequest
 */
export class KeycloakUserListRequest extends Message<KeycloakUserListRequest> {
  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.KeycloakUserFilter filter = 1;
   */
  filter?: KeycloakUserFilter;

  /**
   * @generated from field: optional uint64 last_list_timestamp = 2;
   */
  lastListTimestamp?: bigint;

  constructor(data?: PartialMessage<KeycloakUserListRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.KeycloakUserListRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "filter", kind: "message", T: KeycloakUserFilter, opt: true },
    { no: 2, name: "last_list_timestamp", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): KeycloakUserListRequest {
    return new KeycloakUserListRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): KeycloakUserListRequest {
    return new KeycloakUserListRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): KeycloakUserListRequest {
    return new KeycloakUserListRequest().fromJsonString(jsonString, options);
  }

  static equals(a: KeycloakUserListRequest | PlainMessage<KeycloakUserListRequest> | undefined, b: KeycloakUserListRequest | PlainMessage<KeycloakUserListRequest> | undefined): boolean {
    return proto3.util.equals(KeycloakUserListRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.KeycloakUserListResponse
 */
export class KeycloakUserListResponse extends Message<KeycloakUserListResponse> {
  /**
   * @generated from field: repeated olvid.daemon.datatypes.v1.KeycloakUser users = 1;
   */
  users: KeycloakUser[] = [];

  /**
   * @generated from field: uint64 last_list_timestamp = 2;
   */
  lastListTimestamp = protoInt64.zero;

  constructor(data?: PartialMessage<KeycloakUserListResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.KeycloakUserListResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "users", kind: "message", T: KeycloakUser, repeated: true },
    { no: 2, name: "last_list_timestamp", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): KeycloakUserListResponse {
    return new KeycloakUserListResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): KeycloakUserListResponse {
    return new KeycloakUserListResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): KeycloakUserListResponse {
    return new KeycloakUserListResponse().fromJsonString(jsonString, options);
  }

  static equals(a: KeycloakUserListResponse | PlainMessage<KeycloakUserListResponse> | undefined, b: KeycloakUserListResponse | PlainMessage<KeycloakUserListResponse> | undefined): boolean {
    return proto3.util.equals(KeycloakUserListResponse, a, b);
  }
}

/**
 *
 * * KeycloakAddUserAsContact
 *
 * @generated from message olvid.daemon.command.v1.KeycloakAddUserAsContactRequest
 */
export class KeycloakAddUserAsContactRequest extends Message<KeycloakAddUserAsContactRequest> {
  /**
   * @generated from field: string keycloak_id = 1;
   */
  keycloakId = "";

  constructor(data?: PartialMessage<KeycloakAddUserAsContactRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.KeycloakAddUserAsContactRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "keycloak_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): KeycloakAddUserAsContactRequest {
    return new KeycloakAddUserAsContactRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): KeycloakAddUserAsContactRequest {
    return new KeycloakAddUserAsContactRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): KeycloakAddUserAsContactRequest {
    return new KeycloakAddUserAsContactRequest().fromJsonString(jsonString, options);
  }

  static equals(a: KeycloakAddUserAsContactRequest | PlainMessage<KeycloakAddUserAsContactRequest> | undefined, b: KeycloakAddUserAsContactRequest | PlainMessage<KeycloakAddUserAsContactRequest> | undefined): boolean {
    return proto3.util.equals(KeycloakAddUserAsContactRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.KeycloakAddUserAsContactResponse
 */
export class KeycloakAddUserAsContactResponse extends Message<KeycloakAddUserAsContactResponse> {
  constructor(data?: PartialMessage<KeycloakAddUserAsContactResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.KeycloakAddUserAsContactResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): KeycloakAddUserAsContactResponse {
    return new KeycloakAddUserAsContactResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): KeycloakAddUserAsContactResponse {
    return new KeycloakAddUserAsContactResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): KeycloakAddUserAsContactResponse {
    return new KeycloakAddUserAsContactResponse().fromJsonString(jsonString, options);
  }

  static equals(a: KeycloakAddUserAsContactResponse | PlainMessage<KeycloakAddUserAsContactResponse> | undefined, b: KeycloakAddUserAsContactResponse | PlainMessage<KeycloakAddUserAsContactResponse> | undefined): boolean {
    return proto3.util.equals(KeycloakAddUserAsContactResponse, a, b);
  }
}

