// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file olvid/daemon/command/v1/message_commands.proto (package olvid.daemon.command.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Message as Message$1, MessageEphemerality, MessageFilter, MessageId } from "../../datatypes/v1/message_pb.js";
import { Attachment } from "../../datatypes/v1/attachment_pb.js";

/**
 *
 * * MessageList return all messages for current identity
 *
 * @generated from message olvid.daemon.command.v1.MessageListRequest
 */
export class MessageListRequest extends Message<MessageListRequest> {
  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.MessageFilter filter = 1;
   */
  filter?: MessageFilter;

  /**
   * only list unread messages (messages that have never been listed or sent in a MessageReceived notification)
   *
   * @generated from field: optional bool unread = 2;
   */
  unread?: boolean;

  constructor(data?: PartialMessage<MessageListRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageListRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "filter", kind: "message", T: MessageFilter, opt: true },
    { no: 2, name: "unread", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageListRequest {
    return new MessageListRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageListRequest {
    return new MessageListRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageListRequest {
    return new MessageListRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MessageListRequest | PlainMessage<MessageListRequest> | undefined, b: MessageListRequest | PlainMessage<MessageListRequest> | undefined): boolean {
    return proto3.util.equals(MessageListRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.MessageListResponse
 */
export class MessageListResponse extends Message<MessageListResponse> {
  /**
   * @generated from field: repeated olvid.daemon.datatypes.v1.Message messages = 1;
   */
  messages: Message$1[] = [];

  constructor(data?: PartialMessage<MessageListResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageListResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "messages", kind: "message", T: Message$1, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageListResponse {
    return new MessageListResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageListResponse {
    return new MessageListResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageListResponse {
    return new MessageListResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MessageListResponse | PlainMessage<MessageListResponse> | undefined, b: MessageListResponse | PlainMessage<MessageListResponse> | undefined): boolean {
    return proto3.util.equals(MessageListResponse, a, b);
  }
}

/**
 *
 * * MessageGet
 *
 * @generated from message olvid.daemon.command.v1.MessageGetRequest
 */
export class MessageGetRequest extends Message<MessageGetRequest> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.MessageId message_id = 1;
   */
  messageId?: MessageId;

  constructor(data?: PartialMessage<MessageGetRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageGetRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message_id", kind: "message", T: MessageId },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageGetRequest {
    return new MessageGetRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageGetRequest {
    return new MessageGetRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageGetRequest {
    return new MessageGetRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MessageGetRequest | PlainMessage<MessageGetRequest> | undefined, b: MessageGetRequest | PlainMessage<MessageGetRequest> | undefined): boolean {
    return proto3.util.equals(MessageGetRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.MessageGetResponse
 */
export class MessageGetResponse extends Message<MessageGetResponse> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Message message = 1;
   */
  message?: Message$1;

  constructor(data?: PartialMessage<MessageGetResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageGetResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message", kind: "message", T: Message$1 },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageGetResponse {
    return new MessageGetResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageGetResponse {
    return new MessageGetResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageGetResponse {
    return new MessageGetResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MessageGetResponse | PlainMessage<MessageGetResponse> | undefined, b: MessageGetResponse | PlainMessage<MessageGetResponse> | undefined): boolean {
    return proto3.util.equals(MessageGetResponse, a, b);
  }
}

/**
 *
 * * MessageRefresh force download of messages on the server
 *
 * @generated from message olvid.daemon.command.v1.MessageRefreshRequest
 */
export class MessageRefreshRequest extends Message<MessageRefreshRequest> {
  constructor(data?: PartialMessage<MessageRefreshRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageRefreshRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageRefreshRequest {
    return new MessageRefreshRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageRefreshRequest {
    return new MessageRefreshRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageRefreshRequest {
    return new MessageRefreshRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MessageRefreshRequest | PlainMessage<MessageRefreshRequest> | undefined, b: MessageRefreshRequest | PlainMessage<MessageRefreshRequest> | undefined): boolean {
    return proto3.util.equals(MessageRefreshRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.MessageRefreshResponse
 */
export class MessageRefreshResponse extends Message<MessageRefreshResponse> {
  constructor(data?: PartialMessage<MessageRefreshResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageRefreshResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageRefreshResponse {
    return new MessageRefreshResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageRefreshResponse {
    return new MessageRefreshResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageRefreshResponse {
    return new MessageRefreshResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MessageRefreshResponse | PlainMessage<MessageRefreshResponse> | undefined, b: MessageRefreshResponse | PlainMessage<MessageRefreshResponse> | undefined): boolean {
    return proto3.util.equals(MessageRefreshResponse, a, b);
  }
}

/**
 *
 * * MessageDelete
 *
 * @generated from message olvid.daemon.command.v1.MessageDeleteRequest
 */
export class MessageDeleteRequest extends Message<MessageDeleteRequest> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.MessageId message_id = 1;
   */
  messageId?: MessageId;

  /**
   * @generated from field: optional bool delete_everywhere = 2;
   */
  deleteEverywhere?: boolean;

  constructor(data?: PartialMessage<MessageDeleteRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageDeleteRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message_id", kind: "message", T: MessageId },
    { no: 2, name: "delete_everywhere", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageDeleteRequest {
    return new MessageDeleteRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageDeleteRequest {
    return new MessageDeleteRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageDeleteRequest {
    return new MessageDeleteRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MessageDeleteRequest | PlainMessage<MessageDeleteRequest> | undefined, b: MessageDeleteRequest | PlainMessage<MessageDeleteRequest> | undefined): boolean {
    return proto3.util.equals(MessageDeleteRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.MessageDeleteResponse
 */
export class MessageDeleteResponse extends Message<MessageDeleteResponse> {
  constructor(data?: PartialMessage<MessageDeleteResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageDeleteResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageDeleteResponse {
    return new MessageDeleteResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageDeleteResponse {
    return new MessageDeleteResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageDeleteResponse {
    return new MessageDeleteResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MessageDeleteResponse | PlainMessage<MessageDeleteResponse> | undefined, b: MessageDeleteResponse | PlainMessage<MessageDeleteResponse> | undefined): boolean {
    return proto3.util.equals(MessageDeleteResponse, a, b);
  }
}

/**
 *
 * * MessageSend
 *
 * @generated from message olvid.daemon.command.v1.MessageSendRequest
 */
export class MessageSendRequest extends Message<MessageSendRequest> {
  /**
   * @generated from field: uint64 discussion_id = 1;
   */
  discussionId = protoInt64.zero;

  /**
   * @generated from field: string body = 2;
   */
  body = "";

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.MessageId reply_id = 3;
   */
  replyId?: MessageId;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.MessageEphemerality ephemerality = 4;
   */
  ephemerality?: MessageEphemerality;

  /**
   * @generated from field: optional bool disable_link_preview = 5;
   */
  disableLinkPreview?: boolean;

  constructor(data?: PartialMessage<MessageSendRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageSendRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "discussion_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "body", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "reply_id", kind: "message", T: MessageId, opt: true },
    { no: 4, name: "ephemerality", kind: "message", T: MessageEphemerality, opt: true },
    { no: 5, name: "disable_link_preview", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageSendRequest {
    return new MessageSendRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageSendRequest {
    return new MessageSendRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageSendRequest {
    return new MessageSendRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MessageSendRequest | PlainMessage<MessageSendRequest> | undefined, b: MessageSendRequest | PlainMessage<MessageSendRequest> | undefined): boolean {
    return proto3.util.equals(MessageSendRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.MessageSendResponse
 */
export class MessageSendResponse extends Message<MessageSendResponse> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Message message = 1;
   */
  message?: Message$1;

  constructor(data?: PartialMessage<MessageSendResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageSendResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message", kind: "message", T: Message$1 },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageSendResponse {
    return new MessageSendResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageSendResponse {
    return new MessageSendResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageSendResponse {
    return new MessageSendResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MessageSendResponse | PlainMessage<MessageSendResponse> | undefined, b: MessageSendResponse | PlainMessage<MessageSendResponse> | undefined): boolean {
    return proto3.util.equals(MessageSendResponse, a, b);
  }
}

/**
 *
 * * MessageSendWithAttachments
 *
 * @generated from message olvid.daemon.command.v1.MessageSendWithAttachmentsRequest
 */
export class MessageSendWithAttachmentsRequest extends Message<MessageSendWithAttachmentsRequest> {
  /**
   * @generated from oneof olvid.daemon.command.v1.MessageSendWithAttachmentsRequest.request
   */
  request: {
    /**
     * @generated from field: olvid.daemon.command.v1.MessageSendWithAttachmentsRequestMetadata metadata = 1;
     */
    value: MessageSendWithAttachmentsRequestMetadata;
    case: "metadata";
  } | {
    /**
     * @generated from field: bytes payload = 2;
     */
    value: Uint8Array;
    case: "payload";
  } | {
    /**
     * @generated from field: bool file_delimiter = 3;
     */
    value: boolean;
    case: "fileDelimiter";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<MessageSendWithAttachmentsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageSendWithAttachmentsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "metadata", kind: "message", T: MessageSendWithAttachmentsRequestMetadata, oneof: "request" },
    { no: 2, name: "payload", kind: "scalar", T: 12 /* ScalarType.BYTES */, oneof: "request" },
    { no: 3, name: "file_delimiter", kind: "scalar", T: 8 /* ScalarType.BOOL */, oneof: "request" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageSendWithAttachmentsRequest {
    return new MessageSendWithAttachmentsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageSendWithAttachmentsRequest {
    return new MessageSendWithAttachmentsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageSendWithAttachmentsRequest {
    return new MessageSendWithAttachmentsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MessageSendWithAttachmentsRequest | PlainMessage<MessageSendWithAttachmentsRequest> | undefined, b: MessageSendWithAttachmentsRequest | PlainMessage<MessageSendWithAttachmentsRequest> | undefined): boolean {
    return proto3.util.equals(MessageSendWithAttachmentsRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.MessageSendWithAttachmentsRequestMetadata
 */
export class MessageSendWithAttachmentsRequestMetadata extends Message<MessageSendWithAttachmentsRequestMetadata> {
  /**
   * message
   *
   * @generated from field: uint64 discussion_id = 1;
   */
  discussionId = protoInt64.zero;

  /**
   * @generated from field: optional string body = 2;
   */
  body?: string;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.MessageId reply_id = 3;
   */
  replyId?: MessageId;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.MessageEphemerality ephemerality = 4;
   */
  ephemerality?: MessageEphemerality;

  /**
   * @generated from field: optional bool disable_link_preview = 5;
   */
  disableLinkPreview?: boolean;

  /**
   * @generated from field: repeated olvid.daemon.command.v1.MessageSendWithAttachmentsRequestMetadata.File files = 10;
   */
  files: MessageSendWithAttachmentsRequestMetadata_File[] = [];

  constructor(data?: PartialMessage<MessageSendWithAttachmentsRequestMetadata>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageSendWithAttachmentsRequestMetadata";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "discussion_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "body", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "reply_id", kind: "message", T: MessageId, opt: true },
    { no: 4, name: "ephemerality", kind: "message", T: MessageEphemerality, opt: true },
    { no: 5, name: "disable_link_preview", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 10, name: "files", kind: "message", T: MessageSendWithAttachmentsRequestMetadata_File, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageSendWithAttachmentsRequestMetadata {
    return new MessageSendWithAttachmentsRequestMetadata().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageSendWithAttachmentsRequestMetadata {
    return new MessageSendWithAttachmentsRequestMetadata().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageSendWithAttachmentsRequestMetadata {
    return new MessageSendWithAttachmentsRequestMetadata().fromJsonString(jsonString, options);
  }

  static equals(a: MessageSendWithAttachmentsRequestMetadata | PlainMessage<MessageSendWithAttachmentsRequestMetadata> | undefined, b: MessageSendWithAttachmentsRequestMetadata | PlainMessage<MessageSendWithAttachmentsRequestMetadata> | undefined): boolean {
    return proto3.util.equals(MessageSendWithAttachmentsRequestMetadata, a, b);
  }
}

/**
 * attachments
 *
 * @generated from message olvid.daemon.command.v1.MessageSendWithAttachmentsRequestMetadata.File
 */
export class MessageSendWithAttachmentsRequestMetadata_File extends Message<MessageSendWithAttachmentsRequestMetadata_File> {
  /**
   * @generated from field: string filename = 1;
   */
  filename = "";

  /**
   * @generated from field: uint64 file_size = 2;
   */
  fileSize = protoInt64.zero;

  constructor(data?: PartialMessage<MessageSendWithAttachmentsRequestMetadata_File>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageSendWithAttachmentsRequestMetadata.File";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "file_size", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageSendWithAttachmentsRequestMetadata_File {
    return new MessageSendWithAttachmentsRequestMetadata_File().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageSendWithAttachmentsRequestMetadata_File {
    return new MessageSendWithAttachmentsRequestMetadata_File().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageSendWithAttachmentsRequestMetadata_File {
    return new MessageSendWithAttachmentsRequestMetadata_File().fromJsonString(jsonString, options);
  }

  static equals(a: MessageSendWithAttachmentsRequestMetadata_File | PlainMessage<MessageSendWithAttachmentsRequestMetadata_File> | undefined, b: MessageSendWithAttachmentsRequestMetadata_File | PlainMessage<MessageSendWithAttachmentsRequestMetadata_File> | undefined): boolean {
    return proto3.util.equals(MessageSendWithAttachmentsRequestMetadata_File, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.MessageSendWithAttachmentsResponse
 */
export class MessageSendWithAttachmentsResponse extends Message<MessageSendWithAttachmentsResponse> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Message message = 1;
   */
  message?: Message$1;

  /**
   * @generated from field: repeated olvid.daemon.datatypes.v1.Attachment attachments = 2;
   */
  attachments: Attachment[] = [];

  constructor(data?: PartialMessage<MessageSendWithAttachmentsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageSendWithAttachmentsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message", kind: "message", T: Message$1 },
    { no: 2, name: "attachments", kind: "message", T: Attachment, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageSendWithAttachmentsResponse {
    return new MessageSendWithAttachmentsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageSendWithAttachmentsResponse {
    return new MessageSendWithAttachmentsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageSendWithAttachmentsResponse {
    return new MessageSendWithAttachmentsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MessageSendWithAttachmentsResponse | PlainMessage<MessageSendWithAttachmentsResponse> | undefined, b: MessageSendWithAttachmentsResponse | PlainMessage<MessageSendWithAttachmentsResponse> | undefined): boolean {
    return proto3.util.equals(MessageSendWithAttachmentsResponse, a, b);
  }
}

/**
 *
 * * MessageSendLocation
 *
 * @generated from message olvid.daemon.command.v1.MessageSendLocationRequest
 */
export class MessageSendLocationRequest extends Message<MessageSendLocationRequest> {
  /**
   * @generated from field: uint64 discussion_id = 1;
   */
  discussionId = protoInt64.zero;

  /**
   * @generated from field: double latitude = 2;
   */
  latitude = 0;

  /**
   * @generated from field: double longitude = 3;
   */
  longitude = 0;

  /**
   * @generated from field: optional double altitude = 4;
   */
  altitude?: number;

  /**
   * @generated from field: optional float precision = 5;
   */
  precision?: number;

  /**
   * @generated from field: optional string address = 6;
   */
  address?: string;

  /**
   * preview filename and payload must be set together. Payload might not exceed protobuf max message size.
   *
   * @generated from field: optional string preview_filename = 7;
   */
  previewFilename?: string;

  /**
   * @generated from field: optional bytes preview_payload = 8;
   */
  previewPayload?: Uint8Array;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.MessageEphemerality ephemerality = 9;
   */
  ephemerality?: MessageEphemerality;

  constructor(data?: PartialMessage<MessageSendLocationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageSendLocationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "discussion_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "latitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "longitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "altitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 5, name: "precision", kind: "scalar", T: 2 /* ScalarType.FLOAT */, opt: true },
    { no: 6, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "preview_filename", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 8, name: "preview_payload", kind: "scalar", T: 12 /* ScalarType.BYTES */, opt: true },
    { no: 9, name: "ephemerality", kind: "message", T: MessageEphemerality, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageSendLocationRequest {
    return new MessageSendLocationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageSendLocationRequest {
    return new MessageSendLocationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageSendLocationRequest {
    return new MessageSendLocationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MessageSendLocationRequest | PlainMessage<MessageSendLocationRequest> | undefined, b: MessageSendLocationRequest | PlainMessage<MessageSendLocationRequest> | undefined): boolean {
    return proto3.util.equals(MessageSendLocationRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.MessageSendLocationResponse
 */
export class MessageSendLocationResponse extends Message<MessageSendLocationResponse> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Message message = 1;
   */
  message?: Message$1;

  constructor(data?: PartialMessage<MessageSendLocationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageSendLocationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message", kind: "message", T: Message$1 },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageSendLocationResponse {
    return new MessageSendLocationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageSendLocationResponse {
    return new MessageSendLocationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageSendLocationResponse {
    return new MessageSendLocationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MessageSendLocationResponse | PlainMessage<MessageSendLocationResponse> | undefined, b: MessageSendLocationResponse | PlainMessage<MessageSendLocationResponse> | undefined): boolean {
    return proto3.util.equals(MessageSendLocationResponse, a, b);
  }
}

/**
 *
 * * MessageStartLocationSharing
 *
 * @generated from message olvid.daemon.command.v1.MessageStartLocationSharingRequest
 */
export class MessageStartLocationSharingRequest extends Message<MessageStartLocationSharingRequest> {
  /**
   * @generated from field: uint64 discussion_id = 1;
   */
  discussionId = protoInt64.zero;

  /**
   * @generated from field: double latitude = 2;
   */
  latitude = 0;

  /**
   * @generated from field: double longitude = 3;
   */
  longitude = 0;

  /**
   * @generated from field: optional double altitude = 4;
   */
  altitude?: number;

  /**
   * @generated from field: optional float precision = 5;
   */
  precision?: number;

  constructor(data?: PartialMessage<MessageStartLocationSharingRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageStartLocationSharingRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "discussion_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "latitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "longitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "altitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 5, name: "precision", kind: "scalar", T: 2 /* ScalarType.FLOAT */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageStartLocationSharingRequest {
    return new MessageStartLocationSharingRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageStartLocationSharingRequest {
    return new MessageStartLocationSharingRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageStartLocationSharingRequest {
    return new MessageStartLocationSharingRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MessageStartLocationSharingRequest | PlainMessage<MessageStartLocationSharingRequest> | undefined, b: MessageStartLocationSharingRequest | PlainMessage<MessageStartLocationSharingRequest> | undefined): boolean {
    return proto3.util.equals(MessageStartLocationSharingRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.MessageStartLocationSharingResponse
 */
export class MessageStartLocationSharingResponse extends Message<MessageStartLocationSharingResponse> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Message message = 1;
   */
  message?: Message$1;

  constructor(data?: PartialMessage<MessageStartLocationSharingResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageStartLocationSharingResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message", kind: "message", T: Message$1 },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageStartLocationSharingResponse {
    return new MessageStartLocationSharingResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageStartLocationSharingResponse {
    return new MessageStartLocationSharingResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageStartLocationSharingResponse {
    return new MessageStartLocationSharingResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MessageStartLocationSharingResponse | PlainMessage<MessageStartLocationSharingResponse> | undefined, b: MessageStartLocationSharingResponse | PlainMessage<MessageStartLocationSharingResponse> | undefined): boolean {
    return proto3.util.equals(MessageStartLocationSharingResponse, a, b);
  }
}

/**
 *
 * * MessageUpdateLocationSharing
 *
 * @generated from message olvid.daemon.command.v1.MessageUpdateLocationSharingRequest
 */
export class MessageUpdateLocationSharingRequest extends Message<MessageUpdateLocationSharingRequest> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.MessageId message_id = 1;
   */
  messageId?: MessageId;

  /**
   * @generated from field: double latitude = 2;
   */
  latitude = 0;

  /**
   * @generated from field: double longitude = 3;
   */
  longitude = 0;

  /**
   * @generated from field: optional double altitude = 4;
   */
  altitude?: number;

  /**
   * @generated from field: optional float precision = 5;
   */
  precision?: number;

  constructor(data?: PartialMessage<MessageUpdateLocationSharingRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageUpdateLocationSharingRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message_id", kind: "message", T: MessageId },
    { no: 2, name: "latitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "longitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "altitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 5, name: "precision", kind: "scalar", T: 2 /* ScalarType.FLOAT */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageUpdateLocationSharingRequest {
    return new MessageUpdateLocationSharingRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageUpdateLocationSharingRequest {
    return new MessageUpdateLocationSharingRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageUpdateLocationSharingRequest {
    return new MessageUpdateLocationSharingRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MessageUpdateLocationSharingRequest | PlainMessage<MessageUpdateLocationSharingRequest> | undefined, b: MessageUpdateLocationSharingRequest | PlainMessage<MessageUpdateLocationSharingRequest> | undefined): boolean {
    return proto3.util.equals(MessageUpdateLocationSharingRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.MessageUpdateLocationSharingResponse
 */
export class MessageUpdateLocationSharingResponse extends Message<MessageUpdateLocationSharingResponse> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Message message = 1;
   */
  message?: Message$1;

  constructor(data?: PartialMessage<MessageUpdateLocationSharingResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageUpdateLocationSharingResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message", kind: "message", T: Message$1 },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageUpdateLocationSharingResponse {
    return new MessageUpdateLocationSharingResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageUpdateLocationSharingResponse {
    return new MessageUpdateLocationSharingResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageUpdateLocationSharingResponse {
    return new MessageUpdateLocationSharingResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MessageUpdateLocationSharingResponse | PlainMessage<MessageUpdateLocationSharingResponse> | undefined, b: MessageUpdateLocationSharingResponse | PlainMessage<MessageUpdateLocationSharingResponse> | undefined): boolean {
    return proto3.util.equals(MessageUpdateLocationSharingResponse, a, b);
  }
}

/**
 *
 * * MessageEndLocationSharing
 *
 * @generated from message olvid.daemon.command.v1.MessageEndLocationSharingRequest
 */
export class MessageEndLocationSharingRequest extends Message<MessageEndLocationSharingRequest> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.MessageId message_id = 1;
   */
  messageId?: MessageId;

  constructor(data?: PartialMessage<MessageEndLocationSharingRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageEndLocationSharingRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message_id", kind: "message", T: MessageId },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageEndLocationSharingRequest {
    return new MessageEndLocationSharingRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageEndLocationSharingRequest {
    return new MessageEndLocationSharingRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageEndLocationSharingRequest {
    return new MessageEndLocationSharingRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MessageEndLocationSharingRequest | PlainMessage<MessageEndLocationSharingRequest> | undefined, b: MessageEndLocationSharingRequest | PlainMessage<MessageEndLocationSharingRequest> | undefined): boolean {
    return proto3.util.equals(MessageEndLocationSharingRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.MessageEndLocationSharingResponse
 */
export class MessageEndLocationSharingResponse extends Message<MessageEndLocationSharingResponse> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Message message = 1;
   */
  message?: Message$1;

  constructor(data?: PartialMessage<MessageEndLocationSharingResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageEndLocationSharingResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message", kind: "message", T: Message$1 },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageEndLocationSharingResponse {
    return new MessageEndLocationSharingResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageEndLocationSharingResponse {
    return new MessageEndLocationSharingResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageEndLocationSharingResponse {
    return new MessageEndLocationSharingResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MessageEndLocationSharingResponse | PlainMessage<MessageEndLocationSharingResponse> | undefined, b: MessageEndLocationSharingResponse | PlainMessage<MessageEndLocationSharingResponse> | undefined): boolean {
    return proto3.util.equals(MessageEndLocationSharingResponse, a, b);
  }
}

/**
 *
 * * MessageReact
 *
 * @generated from message olvid.daemon.command.v1.MessageReactRequest
 */
export class MessageReactRequest extends Message<MessageReactRequest> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.MessageId message_id = 1;
   */
  messageId?: MessageId;

  /**
   * @generated from field: string reaction = 2;
   */
  reaction = "";

  constructor(data?: PartialMessage<MessageReactRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageReactRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message_id", kind: "message", T: MessageId },
    { no: 2, name: "reaction", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageReactRequest {
    return new MessageReactRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageReactRequest {
    return new MessageReactRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageReactRequest {
    return new MessageReactRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MessageReactRequest | PlainMessage<MessageReactRequest> | undefined, b: MessageReactRequest | PlainMessage<MessageReactRequest> | undefined): boolean {
    return proto3.util.equals(MessageReactRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.MessageReactResponse
 */
export class MessageReactResponse extends Message<MessageReactResponse> {
  constructor(data?: PartialMessage<MessageReactResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageReactResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageReactResponse {
    return new MessageReactResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageReactResponse {
    return new MessageReactResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageReactResponse {
    return new MessageReactResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MessageReactResponse | PlainMessage<MessageReactResponse> | undefined, b: MessageReactResponse | PlainMessage<MessageReactResponse> | undefined): boolean {
    return proto3.util.equals(MessageReactResponse, a, b);
  }
}

/**
 *
 * * MessageUpdateBody
 *
 * @generated from message olvid.daemon.command.v1.MessageUpdateBodyRequest
 */
export class MessageUpdateBodyRequest extends Message<MessageUpdateBodyRequest> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.MessageId message_id = 1;
   */
  messageId?: MessageId;

  /**
   * @generated from field: string updated_body = 2;
   */
  updatedBody = "";

  constructor(data?: PartialMessage<MessageUpdateBodyRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageUpdateBodyRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message_id", kind: "message", T: MessageId },
    { no: 2, name: "updated_body", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageUpdateBodyRequest {
    return new MessageUpdateBodyRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageUpdateBodyRequest {
    return new MessageUpdateBodyRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageUpdateBodyRequest {
    return new MessageUpdateBodyRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MessageUpdateBodyRequest | PlainMessage<MessageUpdateBodyRequest> | undefined, b: MessageUpdateBodyRequest | PlainMessage<MessageUpdateBodyRequest> | undefined): boolean {
    return proto3.util.equals(MessageUpdateBodyRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.MessageUpdateBodyResponse
 */
export class MessageUpdateBodyResponse extends Message<MessageUpdateBodyResponse> {
  constructor(data?: PartialMessage<MessageUpdateBodyResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageUpdateBodyResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageUpdateBodyResponse {
    return new MessageUpdateBodyResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageUpdateBodyResponse {
    return new MessageUpdateBodyResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageUpdateBodyResponse {
    return new MessageUpdateBodyResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MessageUpdateBodyResponse | PlainMessage<MessageUpdateBodyResponse> | undefined, b: MessageUpdateBodyResponse | PlainMessage<MessageUpdateBodyResponse> | undefined): boolean {
    return proto3.util.equals(MessageUpdateBodyResponse, a, b);
  }
}

/**
 *
 * * MessageSendVoip
 * * ⚠️ deprecated: use CallCommandService instead ⚠️
 *
 * @generated from message olvid.daemon.command.v1.MessageSendVoipRequest
 */
export class MessageSendVoipRequest extends Message<MessageSendVoipRequest> {
  /**
   * @generated from field: uint64 discussion_id = 1;
   */
  discussionId = protoInt64.zero;

  constructor(data?: PartialMessage<MessageSendVoipRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageSendVoipRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "discussion_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageSendVoipRequest {
    return new MessageSendVoipRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageSendVoipRequest {
    return new MessageSendVoipRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageSendVoipRequest {
    return new MessageSendVoipRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MessageSendVoipRequest | PlainMessage<MessageSendVoipRequest> | undefined, b: MessageSendVoipRequest | PlainMessage<MessageSendVoipRequest> | undefined): boolean {
    return proto3.util.equals(MessageSendVoipRequest, a, b);
  }
}

/**
 * @generated from message olvid.daemon.command.v1.MessageSendVoipResponse
 */
export class MessageSendVoipResponse extends Message<MessageSendVoipResponse> {
  constructor(data?: PartialMessage<MessageSendVoipResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.command.v1.MessageSendVoipResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageSendVoipResponse {
    return new MessageSendVoipResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageSendVoipResponse {
    return new MessageSendVoipResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageSendVoipResponse {
    return new MessageSendVoipResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MessageSendVoipResponse | PlainMessage<MessageSendVoipResponse> | undefined, b: MessageSendVoipResponse | PlainMessage<MessageSendVoipResponse> | undefined): boolean {
    return proto3.util.equals(MessageSendVoipResponse, a, b);
  }
}

