// @generated by protoc-gen-es v2.8.0 with parameter "target=ts"
// @generated from file olvid/daemon/admin/v1/identity_admin.proto (package olvid.daemon.admin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Identity, IdentityDetails, IdentityFilter } from "../../datatypes/v1/identity_pb";
import { file_olvid_daemon_datatypes_v1_identity } from "../../datatypes/v1/identity_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file olvid/daemon/admin/v1/identity_admin.proto.
 */
export const file_olvid_daemon_admin_v1_identity_admin: GenFile = /*@__PURE__*/
  fileDesc("CipvbHZpZC9kYWVtb24vYWRtaW4vdjEvaWRlbnRpdHlfYWRtaW4ucHJvdG8SFW9sdmlkLmRhZW1vbi5hZG1pbi52MSJgChNJZGVudGl0eUxpc3RSZXF1ZXN0Ej4KBmZpbHRlchgBIAEoCzIpLm9sdmlkLmRhZW1vbi5kYXRhdHlwZXMudjEuSWRlbnRpdHlGaWx0ZXJIAIgBAUIJCgdfZmlsdGVyIk8KFElkZW50aXR5TGlzdFJlc3BvbnNlEjcKCmlkZW50aXRpZXMYASADKAsyIy5vbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxLklkZW50aXR5Ii4KF0lkZW50aXR5QWRtaW5HZXRSZXF1ZXN0EhMKC2lkZW50aXR5X2lkGAEgASgEIlEKGElkZW50aXR5QWRtaW5HZXRSZXNwb25zZRI1CghpZGVudGl0eRgBIAEoCzIjLm9sdmlkLmRhZW1vbi5kYXRhdHlwZXMudjEuSWRlbnRpdHkiPQomSWRlbnRpdHlBZG1pbkdldEJ5dGVzSWRlbnRpZmllclJlcXVlc3QSEwoLaWRlbnRpdHlfaWQYASABKAQiPQonSWRlbnRpdHlBZG1pbkdldEJ5dGVzSWRlbnRpZmllclJlc3BvbnNlEhIKCmlkZW50aWZpZXIYASABKAwiPAolSWRlbnRpdHlBZG1pbkdldEludml0YXRpb25MaW5rUmVxdWVzdBITCgtpZGVudGl0eV9pZBgBIAEoBCJBCiZJZGVudGl0eUFkbWluR2V0SW52aXRhdGlvbkxpbmtSZXNwb25zZRIXCg9pbnZpdGF0aW9uX2xpbmsYASABKAkiOAohSWRlbnRpdHlBZG1pbkRvd25sb2FkUGhvdG9SZXF1ZXN0EhMKC2lkZW50aXR5X2lkGAEgASgEIjMKIklkZW50aXR5QWRtaW5Eb3dubG9hZFBob3RvUmVzcG9uc2USDQoFcGhvdG8YASABKAwipAEKEklkZW50aXR5TmV3UmVxdWVzdBJEChBpZGVudGl0eV9kZXRhaWxzGAEgASgLMioub2x2aWQuZGFlbW9uLmRhdGF0eXBlcy52MS5JZGVudGl0eURldGFpbHMSFwoKc2VydmVyX3VybBgCIAEoCUgAiAEBEhQKB2FwaV9rZXkYAyABKAlIAYgBAUINCgtfc2VydmVyX3VybEIKCghfYXBpX2tleSJMChNJZGVudGl0eU5ld1Jlc3BvbnNlEjUKCGlkZW50aXR5GAEgASgLMiMub2x2aWQuZGFlbW9uLmRhdGF0eXBlcy52MS5JZGVudGl0eSIsChVJZGVudGl0eURlbGV0ZVJlcXVlc3QSEwoLaWRlbnRpdHlfaWQYASABKAQiGAoWSWRlbnRpdHlEZWxldGVSZXNwb25zZSI4ChpJZGVudGl0eUtleWNsb2FrTmV3UmVxdWVzdBIaChJjb25maWd1cmF0aW9uX2xpbmsYASABKAkiVAobSWRlbnRpdHlLZXljbG9ha05ld1Jlc3BvbnNlEjUKCGlkZW50aXR5GAEgASgLMiMub2x2aWQuZGFlbW9uLmRhdGF0eXBlcy52MS5JZGVudGl0eUI1CiBpby5vbHZpZC5kZXNrdG9wLmRhZW1vbi5wcm90b2J1ZlABWg9vbHZpZC5pby9kYWVtb25iBnByb3RvMw", [file_olvid_daemon_datatypes_v1_identity]);

/**
 *
 * * IdentityList
 *
 * @generated from message olvid.daemon.admin.v1.IdentityListRequest
 */
export type IdentityListRequest = Message<"olvid.daemon.admin.v1.IdentityListRequest"> & {
  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.IdentityFilter filter = 1;
   */
  filter?: IdentityFilter;
};

/**
 * Describes the message olvid.daemon.admin.v1.IdentityListRequest.
 * Use `create(IdentityListRequestSchema)` to create a new message.
 */
export const IdentityListRequestSchema: GenMessage<IdentityListRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_admin_v1_identity_admin, 0);

/**
 * @generated from message olvid.daemon.admin.v1.IdentityListResponse
 */
export type IdentityListResponse = Message<"olvid.daemon.admin.v1.IdentityListResponse"> & {
  /**
   * @generated from field: repeated olvid.daemon.datatypes.v1.Identity identities = 1;
   */
  identities: Identity[];
};

/**
 * Describes the message olvid.daemon.admin.v1.IdentityListResponse.
 * Use `create(IdentityListResponseSchema)` to create a new message.
 */
export const IdentityListResponseSchema: GenMessage<IdentityListResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_admin_v1_identity_admin, 1);

/**
 *
 * * IdentityAdminGet
 *
 * @generated from message olvid.daemon.admin.v1.IdentityAdminGetRequest
 */
export type IdentityAdminGetRequest = Message<"olvid.daemon.admin.v1.IdentityAdminGetRequest"> & {
  /**
   * @generated from field: uint64 identity_id = 1;
   */
  identityId: bigint;
};

/**
 * Describes the message olvid.daemon.admin.v1.IdentityAdminGetRequest.
 * Use `create(IdentityAdminGetRequestSchema)` to create a new message.
 */
export const IdentityAdminGetRequestSchema: GenMessage<IdentityAdminGetRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_admin_v1_identity_admin, 2);

/**
 * @generated from message olvid.daemon.admin.v1.IdentityAdminGetResponse
 */
export type IdentityAdminGetResponse = Message<"olvid.daemon.admin.v1.IdentityAdminGetResponse"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Identity identity = 1;
   */
  identity?: Identity;
};

/**
 * Describes the message olvid.daemon.admin.v1.IdentityAdminGetResponse.
 * Use `create(IdentityAdminGetResponseSchema)` to create a new message.
 */
export const IdentityAdminGetResponseSchema: GenMessage<IdentityAdminGetResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_admin_v1_identity_admin, 3);

/**
 *
 * * IdentityAdminGetBytesIdentifier
 *
 * @generated from message olvid.daemon.admin.v1.IdentityAdminGetBytesIdentifierRequest
 */
export type IdentityAdminGetBytesIdentifierRequest = Message<"olvid.daemon.admin.v1.IdentityAdminGetBytesIdentifierRequest"> & {
  /**
   * @generated from field: uint64 identity_id = 1;
   */
  identityId: bigint;
};

/**
 * Describes the message olvid.daemon.admin.v1.IdentityAdminGetBytesIdentifierRequest.
 * Use `create(IdentityAdminGetBytesIdentifierRequestSchema)` to create a new message.
 */
export const IdentityAdminGetBytesIdentifierRequestSchema: GenMessage<IdentityAdminGetBytesIdentifierRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_admin_v1_identity_admin, 4);

/**
 * @generated from message olvid.daemon.admin.v1.IdentityAdminGetBytesIdentifierResponse
 */
export type IdentityAdminGetBytesIdentifierResponse = Message<"olvid.daemon.admin.v1.IdentityAdminGetBytesIdentifierResponse"> & {
  /**
   * @generated from field: bytes identifier = 1;
   */
  identifier: Uint8Array;
};

/**
 * Describes the message olvid.daemon.admin.v1.IdentityAdminGetBytesIdentifierResponse.
 * Use `create(IdentityAdminGetBytesIdentifierResponseSchema)` to create a new message.
 */
export const IdentityAdminGetBytesIdentifierResponseSchema: GenMessage<IdentityAdminGetBytesIdentifierResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_admin_v1_identity_admin, 5);

/**
 *
 * * IdentityAdminGetInvitationLink
 *
 * @generated from message olvid.daemon.admin.v1.IdentityAdminGetInvitationLinkRequest
 */
export type IdentityAdminGetInvitationLinkRequest = Message<"olvid.daemon.admin.v1.IdentityAdminGetInvitationLinkRequest"> & {
  /**
   * @generated from field: uint64 identity_id = 1;
   */
  identityId: bigint;
};

/**
 * Describes the message olvid.daemon.admin.v1.IdentityAdminGetInvitationLinkRequest.
 * Use `create(IdentityAdminGetInvitationLinkRequestSchema)` to create a new message.
 */
export const IdentityAdminGetInvitationLinkRequestSchema: GenMessage<IdentityAdminGetInvitationLinkRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_admin_v1_identity_admin, 6);

/**
 * @generated from message olvid.daemon.admin.v1.IdentityAdminGetInvitationLinkResponse
 */
export type IdentityAdminGetInvitationLinkResponse = Message<"olvid.daemon.admin.v1.IdentityAdminGetInvitationLinkResponse"> & {
  /**
   * @generated from field: string invitation_link = 1;
   */
  invitationLink: string;
};

/**
 * Describes the message olvid.daemon.admin.v1.IdentityAdminGetInvitationLinkResponse.
 * Use `create(IdentityAdminGetInvitationLinkResponseSchema)` to create a new message.
 */
export const IdentityAdminGetInvitationLinkResponseSchema: GenMessage<IdentityAdminGetInvitationLinkResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_admin_v1_identity_admin, 7);

/**
 *
 * * IdentityAdminDownloadPhoto
 *
 * @generated from message olvid.daemon.admin.v1.IdentityAdminDownloadPhotoRequest
 */
export type IdentityAdminDownloadPhotoRequest = Message<"olvid.daemon.admin.v1.IdentityAdminDownloadPhotoRequest"> & {
  /**
   * @generated from field: uint64 identity_id = 1;
   */
  identityId: bigint;
};

/**
 * Describes the message olvid.daemon.admin.v1.IdentityAdminDownloadPhotoRequest.
 * Use `create(IdentityAdminDownloadPhotoRequestSchema)` to create a new message.
 */
export const IdentityAdminDownloadPhotoRequestSchema: GenMessage<IdentityAdminDownloadPhotoRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_admin_v1_identity_admin, 8);

/**
 * @generated from message olvid.daemon.admin.v1.IdentityAdminDownloadPhotoResponse
 */
export type IdentityAdminDownloadPhotoResponse = Message<"olvid.daemon.admin.v1.IdentityAdminDownloadPhotoResponse"> & {
  /**
   * @generated from field: bytes photo = 1;
   */
  photo: Uint8Array;
};

/**
 * Describes the message olvid.daemon.admin.v1.IdentityAdminDownloadPhotoResponse.
 * Use `create(IdentityAdminDownloadPhotoResponseSchema)` to create a new message.
 */
export const IdentityAdminDownloadPhotoResponseSchema: GenMessage<IdentityAdminDownloadPhotoResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_admin_v1_identity_admin, 9);

/**
 *
 * * IdentityNew
 *
 * @generated from message olvid.daemon.admin.v1.IdentityNewRequest
 */
export type IdentityNewRequest = Message<"olvid.daemon.admin.v1.IdentityNewRequest"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.IdentityDetails identity_details = 1;
   */
  identityDetails?: IdentityDetails;

  /**
   * @generated from field: optional string server_url = 2;
   */
  serverUrl?: string;

  /**
   * @generated from field: optional string api_key = 3;
   */
  apiKey?: string;
};

/**
 * Describes the message olvid.daemon.admin.v1.IdentityNewRequest.
 * Use `create(IdentityNewRequestSchema)` to create a new message.
 */
export const IdentityNewRequestSchema: GenMessage<IdentityNewRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_admin_v1_identity_admin, 10);

/**
 * @generated from message olvid.daemon.admin.v1.IdentityNewResponse
 */
export type IdentityNewResponse = Message<"olvid.daemon.admin.v1.IdentityNewResponse"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Identity identity = 1;
   */
  identity?: Identity;
};

/**
 * Describes the message olvid.daemon.admin.v1.IdentityNewResponse.
 * Use `create(IdentityNewResponseSchema)` to create a new message.
 */
export const IdentityNewResponseSchema: GenMessage<IdentityNewResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_admin_v1_identity_admin, 11);

/**
 *
 * * IdentityDelete
 *
 * @generated from message olvid.daemon.admin.v1.IdentityDeleteRequest
 */
export type IdentityDeleteRequest = Message<"olvid.daemon.admin.v1.IdentityDeleteRequest"> & {
  /**
   * @generated from field: uint64 identity_id = 1;
   */
  identityId: bigint;
};

/**
 * Describes the message olvid.daemon.admin.v1.IdentityDeleteRequest.
 * Use `create(IdentityDeleteRequestSchema)` to create a new message.
 */
export const IdentityDeleteRequestSchema: GenMessage<IdentityDeleteRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_admin_v1_identity_admin, 12);

/**
 * @generated from message olvid.daemon.admin.v1.IdentityDeleteResponse
 */
export type IdentityDeleteResponse = Message<"olvid.daemon.admin.v1.IdentityDeleteResponse"> & {
};

/**
 * Describes the message olvid.daemon.admin.v1.IdentityDeleteResponse.
 * Use `create(IdentityDeleteResponseSchema)` to create a new message.
 */
export const IdentityDeleteResponseSchema: GenMessage<IdentityDeleteResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_admin_v1_identity_admin, 13);

/**
 *
 * * IdentityKeycloakNew
 *
 * @generated from message olvid.daemon.admin.v1.IdentityKeycloakNewRequest
 */
export type IdentityKeycloakNewRequest = Message<"olvid.daemon.admin.v1.IdentityKeycloakNewRequest"> & {
  /**
   * @generated from field: string configuration_link = 1;
   */
  configurationLink: string;
};

/**
 * Describes the message olvid.daemon.admin.v1.IdentityKeycloakNewRequest.
 * Use `create(IdentityKeycloakNewRequestSchema)` to create a new message.
 */
export const IdentityKeycloakNewRequestSchema: GenMessage<IdentityKeycloakNewRequest> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_admin_v1_identity_admin, 14);

/**
 * @generated from message olvid.daemon.admin.v1.IdentityKeycloakNewResponse
 */
export type IdentityKeycloakNewResponse = Message<"olvid.daemon.admin.v1.IdentityKeycloakNewResponse"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Identity identity = 1;
   */
  identity?: Identity;
};

/**
 * Describes the message olvid.daemon.admin.v1.IdentityKeycloakNewResponse.
 * Use `create(IdentityKeycloakNewResponseSchema)` to create a new message.
 */
export const IdentityKeycloakNewResponseSchema: GenMessage<IdentityKeycloakNewResponse> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_admin_v1_identity_admin, 15);

