// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file olvid/daemon/notification/v1/attachment_notifications.proto (package olvid.daemon.notification.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Attachment, AttachmentFilter, AttachmentId } from "../../datatypes/v1/attachment_pb";
import { file_olvid_daemon_datatypes_v1_attachment } from "../../datatypes/v1/attachment_pb";
import type { MessageId } from "../../datatypes/v1/message_pb";
import { file_olvid_daemon_datatypes_v1_message } from "../../datatypes/v1/message_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file olvid/daemon/notification/v1/attachment_notifications.proto.
 */
export const file_olvid_daemon_notification_v1_attachment_notifications: GenFile = /*@__PURE__*/
  fileDesc("CjtvbHZpZC9kYWVtb24vbm90aWZpY2F0aW9uL3YxL2F0dGFjaG1lbnRfbm90aWZpY2F0aW9ucy5wcm90bxIcb2x2aWQuZGFlbW9uLm5vdGlmaWNhdGlvbi52MSKWAQopU3Vic2NyaWJlVG9BdHRhY2htZW50UmVjZWl2ZWROb3RpZmljYXRpb24SEgoFY291bnQYASABKARIAIgBARJACgZmaWx0ZXIYAiABKAsyKy5vbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxLkF0dGFjaG1lbnRGaWx0ZXJIAYgBAUIICgZfY291bnRCCQoHX2ZpbHRlciJbCh5BdHRhY2htZW50UmVjZWl2ZWROb3RpZmljYXRpb24SOQoKYXR0YWNobWVudBgBIAEoCzIlLm9sdmlkLmRhZW1vbi5kYXRhdHlwZXMudjEuQXR0YWNobWVudCKSAgopU3Vic2NyaWJlVG9BdHRhY2htZW50VXBsb2FkZWROb3RpZmljYXRpb24SEgoFY291bnQYASABKARIAIgBARJACgZmaWx0ZXIYAiABKAsyKy5vbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxLkF0dGFjaG1lbnRGaWx0ZXJIAYgBARI5CgttZXNzYWdlX2lkcxgDIAMoCzIkLm9sdmlkLmRhZW1vbi5kYXRhdHlwZXMudjEuTWVzc2FnZUlkEj8KDmF0dGFjaG1lbnRfaWRzGAQgAygLMicub2x2aWQuZGFlbW9uLmRhdGF0eXBlcy52MS5BdHRhY2htZW50SWRCCAoGX2NvdW50QgkKB19maWx0ZXIiWwoeQXR0YWNobWVudFVwbG9hZGVkTm90aWZpY2F0aW9uEjkKCmF0dGFjaG1lbnQYASABKAsyJS5vbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxLkF0dGFjaG1lbnRCNQogaW8ub2x2aWQuZGVza3RvcC5kYWVtb24ucHJvdG9idWZQAVoPb2x2aWQuaW8vZGFlbW9uYgZwcm90bzM", [file_olvid_daemon_datatypes_v1_attachment, file_olvid_daemon_datatypes_v1_message]);

/**
 *
 * * AttachmentReceived
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToAttachmentReceivedNotification
 */
export type SubscribeToAttachmentReceivedNotification = Message<"olvid.daemon.notification.v1.SubscribeToAttachmentReceivedNotification"> & {
  /**
   * @generated from field: optional uint64 count = 1;
   */
  count?: bigint;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.AttachmentFilter filter = 2;
   */
  filter?: AttachmentFilter;
};

/**
 * Describes the message olvid.daemon.notification.v1.SubscribeToAttachmentReceivedNotification.
 * Use `create(SubscribeToAttachmentReceivedNotificationSchema)` to create a new message.
 */
export const SubscribeToAttachmentReceivedNotificationSchema: GenMessage<SubscribeToAttachmentReceivedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_attachment_notifications, 0);

/**
 * @generated from message olvid.daemon.notification.v1.AttachmentReceivedNotification
 */
export type AttachmentReceivedNotification = Message<"olvid.daemon.notification.v1.AttachmentReceivedNotification"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Attachment attachment = 1;
   */
  attachment?: Attachment;
};

/**
 * Describes the message olvid.daemon.notification.v1.AttachmentReceivedNotification.
 * Use `create(AttachmentReceivedNotificationSchema)` to create a new message.
 */
export const AttachmentReceivedNotificationSchema: GenMessage<AttachmentReceivedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_attachment_notifications, 1);

/**
 *
 * * AttachmentUploaded
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToAttachmentUploadedNotification
 */
export type SubscribeToAttachmentUploadedNotification = Message<"olvid.daemon.notification.v1.SubscribeToAttachmentUploadedNotification"> & {
  /**
   * @generated from field: optional uint64 count = 1;
   */
  count?: bigint;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.AttachmentFilter filter = 2;
   */
  filter?: AttachmentFilter;

  /**
   * @generated from field: repeated olvid.daemon.datatypes.v1.MessageId message_ids = 3;
   */
  messageIds: MessageId[];

  /**
   * @generated from field: repeated olvid.daemon.datatypes.v1.AttachmentId attachment_ids = 4;
   */
  attachmentIds: AttachmentId[];
};

/**
 * Describes the message olvid.daemon.notification.v1.SubscribeToAttachmentUploadedNotification.
 * Use `create(SubscribeToAttachmentUploadedNotificationSchema)` to create a new message.
 */
export const SubscribeToAttachmentUploadedNotificationSchema: GenMessage<SubscribeToAttachmentUploadedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_attachment_notifications, 2);

/**
 * @generated from message olvid.daemon.notification.v1.AttachmentUploadedNotification
 */
export type AttachmentUploadedNotification = Message<"olvid.daemon.notification.v1.AttachmentUploadedNotification"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Attachment attachment = 1;
   */
  attachment?: Attachment;
};

/**
 * Describes the message olvid.daemon.notification.v1.AttachmentUploadedNotification.
 * Use `create(AttachmentUploadedNotificationSchema)` to create a new message.
 */
export const AttachmentUploadedNotificationSchema: GenMessage<AttachmentUploadedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_attachment_notifications, 3);

