// @generated by protoc-gen-es v2.6.0 with parameter "target=ts"
// @generated from file olvid/daemon/notification/v1/attachment_notifications.proto (package olvid.daemon.notification.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Attachment } from "../../datatypes/v1/attachment_pb";
import { file_olvid_daemon_datatypes_v1_attachment } from "../../datatypes/v1/attachment_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file olvid/daemon/notification/v1/attachment_notifications.proto.
 */
export const file_olvid_daemon_notification_v1_attachment_notifications: GenFile = /*@__PURE__*/
  fileDesc("CjtvbHZpZC9kYWVtb24vbm90aWZpY2F0aW9uL3YxL2F0dGFjaG1lbnRfbm90aWZpY2F0aW9ucy5wcm90bxIcb2x2aWQuZGFlbW9uLm5vdGlmaWNhdGlvbi52MSIrCilTdWJzY3JpYmVUb0F0dGFjaG1lbnRSZWNlaXZlZE5vdGlmaWNhdGlvbiJbCh5BdHRhY2htZW50UmVjZWl2ZWROb3RpZmljYXRpb24SOQoKYXR0YWNobWVudBgBIAEoCzIlLm9sdmlkLmRhZW1vbi5kYXRhdHlwZXMudjEuQXR0YWNobWVudCIrCilTdWJzY3JpYmVUb0F0dGFjaG1lbnRVcGxvYWRlZE5vdGlmaWNhdGlvbiJbCh5BdHRhY2htZW50VXBsb2FkZWROb3RpZmljYXRpb24SOQoKYXR0YWNobWVudBgBIAEoCzIlLm9sdmlkLmRhZW1vbi5kYXRhdHlwZXMudjEuQXR0YWNobWVudEI1CiBpby5vbHZpZC5kZXNrdG9wLmRhZW1vbi5wcm90b2J1ZlABWg9vbHZpZC5pby9kYWVtb25iBnByb3RvMw", [file_olvid_daemon_datatypes_v1_attachment]);

/**
 *
 * * AttachmentReceived
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToAttachmentReceivedNotification
 */
export type SubscribeToAttachmentReceivedNotification = Message<"olvid.daemon.notification.v1.SubscribeToAttachmentReceivedNotification"> & {
};

/**
 * Describes the message olvid.daemon.notification.v1.SubscribeToAttachmentReceivedNotification.
 * Use `create(SubscribeToAttachmentReceivedNotificationSchema)` to create a new message.
 */
export const SubscribeToAttachmentReceivedNotificationSchema: GenMessage<SubscribeToAttachmentReceivedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_attachment_notifications, 0);

/**
 * @generated from message olvid.daemon.notification.v1.AttachmentReceivedNotification
 */
export type AttachmentReceivedNotification = Message<"olvid.daemon.notification.v1.AttachmentReceivedNotification"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Attachment attachment = 1;
   */
  attachment?: Attachment;
};

/**
 * Describes the message olvid.daemon.notification.v1.AttachmentReceivedNotification.
 * Use `create(AttachmentReceivedNotificationSchema)` to create a new message.
 */
export const AttachmentReceivedNotificationSchema: GenMessage<AttachmentReceivedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_attachment_notifications, 1);

/**
 *
 * * AttachmentUploaded
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToAttachmentUploadedNotification
 */
export type SubscribeToAttachmentUploadedNotification = Message<"olvid.daemon.notification.v1.SubscribeToAttachmentUploadedNotification"> & {
};

/**
 * Describes the message olvid.daemon.notification.v1.SubscribeToAttachmentUploadedNotification.
 * Use `create(SubscribeToAttachmentUploadedNotificationSchema)` to create a new message.
 */
export const SubscribeToAttachmentUploadedNotificationSchema: GenMessage<SubscribeToAttachmentUploadedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_attachment_notifications, 2);

/**
 * @generated from message olvid.daemon.notification.v1.AttachmentUploadedNotification
 */
export type AttachmentUploadedNotification = Message<"olvid.daemon.notification.v1.AttachmentUploadedNotification"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Attachment attachment = 1;
   */
  attachment?: Attachment;
};

/**
 * Describes the message olvid.daemon.notification.v1.AttachmentUploadedNotification.
 * Use `create(AttachmentUploadedNotificationSchema)` to create a new message.
 */
export const AttachmentUploadedNotificationSchema: GenMessage<AttachmentUploadedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_attachment_notifications, 3);

