// @generated by protoc-gen-es v2.8.0 with parameter "target=ts"
// @generated from file olvid/daemon/notification/v1/contact_notifications.proto (package olvid.daemon.notification.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Contact, ContactFilter } from "../../datatypes/v1/contact_pb";
import { file_olvid_daemon_datatypes_v1_contact } from "../../datatypes/v1/contact_pb";
import type { IdentityDetails } from "../../datatypes/v1/identity_pb";
import { file_olvid_daemon_datatypes_v1_identity } from "../../datatypes/v1/identity_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file olvid/daemon/notification/v1/contact_notifications.proto.
 */
export const file_olvid_daemon_notification_v1_contact_notifications: GenFile = /*@__PURE__*/
  fileDesc("CjhvbHZpZC9kYWVtb24vbm90aWZpY2F0aW9uL3YxL2NvbnRhY3Rfbm90aWZpY2F0aW9ucy5wcm90bxIcb2x2aWQuZGFlbW9uLm5vdGlmaWNhdGlvbi52MSKLAQohU3Vic2NyaWJlVG9Db250YWN0TmV3Tm90aWZpY2F0aW9uEhIKBWNvdW50GAEgASgESACIAQESPQoGZmlsdGVyGAIgASgLMigub2x2aWQuZGFlbW9uLmRhdGF0eXBlcy52MS5Db250YWN0RmlsdGVySAGIAQFCCAoGX2NvdW50QgkKB19maWx0ZXIiTQoWQ29udGFjdE5ld05vdGlmaWNhdGlvbhIzCgdjb250YWN0GAEgASgLMiIub2x2aWQuZGFlbW9uLmRhdGF0eXBlcy52MS5Db250YWN0IqQBCiVTdWJzY3JpYmVUb0NvbnRhY3REZWxldGVkTm90aWZpY2F0aW9uEhIKBWNvdW50GAEgASgESACIAQESPQoGZmlsdGVyGAIgASgLMigub2x2aWQuZGFlbW9uLmRhdGF0eXBlcy52MS5Db250YWN0RmlsdGVySAGIAQESEwoLY29udGFjdF9pZHMYAyADKARCCAoGX2NvdW50QgkKB19maWx0ZXIiUQoaQ29udGFjdERlbGV0ZWROb3RpZmljYXRpb24SMwoHY29udGFjdBgBIAEoCzIiLm9sdmlkLmRhZW1vbi5kYXRhdHlwZXMudjEuQ29udGFjdCKrAQosU3Vic2NyaWJlVG9Db250YWN0RGV0YWlsc1VwZGF0ZWROb3RpZmljYXRpb24SEgoFY291bnQYASABKARIAIgBARI9CgZmaWx0ZXIYAiABKAsyKC5vbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxLkNvbnRhY3RGaWx0ZXJIAYgBARITCgtjb250YWN0X2lkcxgDIAMoBEIICgZfY291bnRCCQoHX2ZpbHRlciKeAQohQ29udGFjdERldGFpbHNVcGRhdGVkTm90aWZpY2F0aW9uEjMKB2NvbnRhY3QYASABKAsyIi5vbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxLkNvbnRhY3QSRAoQcHJldmlvdXNfZGV0YWlscxgCIAEoCzIqLm9sdmlkLmRhZW1vbi5kYXRhdHlwZXMudjEuSWRlbnRpdHlEZXRhaWxzIqkBCipTdWJzY3JpYmVUb0NvbnRhY3RQaG90b1VwZGF0ZWROb3RpZmljYXRpb24SEgoFY291bnQYASABKARIAIgBARI9CgZmaWx0ZXIYAiABKAsyKC5vbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxLkNvbnRhY3RGaWx0ZXJIAYgBARITCgtjb250YWN0X2lkcxgDIAMoBEIICgZfY291bnRCCQoHX2ZpbHRlciJWCh9Db250YWN0UGhvdG9VcGRhdGVkTm90aWZpY2F0aW9uEjMKB2NvbnRhY3QYASABKAsyIi5vbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxLkNvbnRhY3RCNQogaW8ub2x2aWQuZGVza3RvcC5kYWVtb24ucHJvdG9idWZQAVoPb2x2aWQuaW8vZGFlbW9uYgZwcm90bzM", [file_olvid_daemon_datatypes_v1_contact, file_olvid_daemon_datatypes_v1_identity]);

/**
 *
 * * ContactNew
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToContactNewNotification
 */
export type SubscribeToContactNewNotification = Message<"olvid.daemon.notification.v1.SubscribeToContactNewNotification"> & {
  /**
   * @generated from field: optional uint64 count = 1;
   */
  count?: bigint;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.ContactFilter filter = 2;
   */
  filter?: ContactFilter;
};

/**
 * Describes the message olvid.daemon.notification.v1.SubscribeToContactNewNotification.
 * Use `create(SubscribeToContactNewNotificationSchema)` to create a new message.
 */
export const SubscribeToContactNewNotificationSchema: GenMessage<SubscribeToContactNewNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_contact_notifications, 0);

/**
 * @generated from message olvid.daemon.notification.v1.ContactNewNotification
 */
export type ContactNewNotification = Message<"olvid.daemon.notification.v1.ContactNewNotification"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Contact contact = 1;
   */
  contact?: Contact;
};

/**
 * Describes the message olvid.daemon.notification.v1.ContactNewNotification.
 * Use `create(ContactNewNotificationSchema)` to create a new message.
 */
export const ContactNewNotificationSchema: GenMessage<ContactNewNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_contact_notifications, 1);

/**
 *
 * * ContactDeleted
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToContactDeletedNotification
 */
export type SubscribeToContactDeletedNotification = Message<"olvid.daemon.notification.v1.SubscribeToContactDeletedNotification"> & {
  /**
   * @generated from field: optional uint64 count = 1;
   */
  count?: bigint;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.ContactFilter filter = 2;
   */
  filter?: ContactFilter;

  /**
   * @generated from field: repeated uint64 contact_ids = 3;
   */
  contactIds: bigint[];
};

/**
 * Describes the message olvid.daemon.notification.v1.SubscribeToContactDeletedNotification.
 * Use `create(SubscribeToContactDeletedNotificationSchema)` to create a new message.
 */
export const SubscribeToContactDeletedNotificationSchema: GenMessage<SubscribeToContactDeletedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_contact_notifications, 2);

/**
 * @generated from message olvid.daemon.notification.v1.ContactDeletedNotification
 */
export type ContactDeletedNotification = Message<"olvid.daemon.notification.v1.ContactDeletedNotification"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Contact contact = 1;
   */
  contact?: Contact;
};

/**
 * Describes the message olvid.daemon.notification.v1.ContactDeletedNotification.
 * Use `create(ContactDeletedNotificationSchema)` to create a new message.
 */
export const ContactDeletedNotificationSchema: GenMessage<ContactDeletedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_contact_notifications, 3);

/**
 *
 * * ContactDetailsUpdated
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToContactDetailsUpdatedNotification
 */
export type SubscribeToContactDetailsUpdatedNotification = Message<"olvid.daemon.notification.v1.SubscribeToContactDetailsUpdatedNotification"> & {
  /**
   * @generated from field: optional uint64 count = 1;
   */
  count?: bigint;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.ContactFilter filter = 2;
   */
  filter?: ContactFilter;

  /**
   * @generated from field: repeated uint64 contact_ids = 3;
   */
  contactIds: bigint[];
};

/**
 * Describes the message olvid.daemon.notification.v1.SubscribeToContactDetailsUpdatedNotification.
 * Use `create(SubscribeToContactDetailsUpdatedNotificationSchema)` to create a new message.
 */
export const SubscribeToContactDetailsUpdatedNotificationSchema: GenMessage<SubscribeToContactDetailsUpdatedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_contact_notifications, 4);

/**
 * @generated from message olvid.daemon.notification.v1.ContactDetailsUpdatedNotification
 */
export type ContactDetailsUpdatedNotification = Message<"olvid.daemon.notification.v1.ContactDetailsUpdatedNotification"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Contact contact = 1;
   */
  contact?: Contact;

  /**
   * @generated from field: olvid.daemon.datatypes.v1.IdentityDetails previous_details = 2;
   */
  previousDetails?: IdentityDetails;
};

/**
 * Describes the message olvid.daemon.notification.v1.ContactDetailsUpdatedNotification.
 * Use `create(ContactDetailsUpdatedNotificationSchema)` to create a new message.
 */
export const ContactDetailsUpdatedNotificationSchema: GenMessage<ContactDetailsUpdatedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_contact_notifications, 5);

/**
 *
 * * ContactPhotoUpdated
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToContactPhotoUpdatedNotification
 */
export type SubscribeToContactPhotoUpdatedNotification = Message<"olvid.daemon.notification.v1.SubscribeToContactPhotoUpdatedNotification"> & {
  /**
   * @generated from field: optional uint64 count = 1;
   */
  count?: bigint;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.ContactFilter filter = 2;
   */
  filter?: ContactFilter;

  /**
   * @generated from field: repeated uint64 contact_ids = 3;
   */
  contactIds: bigint[];
};

/**
 * Describes the message olvid.daemon.notification.v1.SubscribeToContactPhotoUpdatedNotification.
 * Use `create(SubscribeToContactPhotoUpdatedNotificationSchema)` to create a new message.
 */
export const SubscribeToContactPhotoUpdatedNotificationSchema: GenMessage<SubscribeToContactPhotoUpdatedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_contact_notifications, 6);

/**
 * @generated from message olvid.daemon.notification.v1.ContactPhotoUpdatedNotification
 */
export type ContactPhotoUpdatedNotification = Message<"olvid.daemon.notification.v1.ContactPhotoUpdatedNotification"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Contact contact = 1;
   */
  contact?: Contact;
};

/**
 * Describes the message olvid.daemon.notification.v1.ContactPhotoUpdatedNotification.
 * Use `create(ContactPhotoUpdatedNotificationSchema)` to create a new message.
 */
export const ContactPhotoUpdatedNotificationSchema: GenMessage<ContactPhotoUpdatedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_contact_notifications, 7);

