// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file olvid/daemon/notification/v1/discussion_notifications.proto (package olvid.daemon.notification.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Discussion, DiscussionFilter } from "../../datatypes/v1/discussion_pb";
import { file_olvid_daemon_datatypes_v1_discussion } from "../../datatypes/v1/discussion_pb";
import type { DiscussionSettings } from "../../datatypes/v1/settings_pb";
import { file_olvid_daemon_datatypes_v1_settings } from "../../datatypes/v1/settings_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file olvid/daemon/notification/v1/discussion_notifications.proto.
 */
export const file_olvid_daemon_notification_v1_discussion_notifications: GenFile = /*@__PURE__*/
  fileDesc("CjtvbHZpZC9kYWVtb24vbm90aWZpY2F0aW9uL3YxL2Rpc2N1c3Npb25fbm90aWZpY2F0aW9ucy5wcm90bxIcb2x2aWQuZGFlbW9uLm5vdGlmaWNhdGlvbi52MSKRAQokU3Vic2NyaWJlVG9EaXNjdXNzaW9uTmV3Tm90aWZpY2F0aW9uEhIKBWNvdW50GAEgASgESACIAQESQAoGZmlsdGVyGAIgASgLMisub2x2aWQuZGFlbW9uLmRhdGF0eXBlcy52MS5EaXNjdXNzaW9uRmlsdGVySAGIAQFCCAoGX2NvdW50QgkKB19maWx0ZXIiVgoZRGlzY3Vzc2lvbk5ld05vdGlmaWNhdGlvbhI5CgpkaXNjdXNzaW9uGAEgASgLMiUub2x2aWQuZGFlbW9uLmRhdGF0eXBlcy52MS5EaXNjdXNzaW9uIqwBCidTdWJzY3JpYmVUb0Rpc2N1c3Npb25Mb2NrZWROb3RpZmljYXRpb24SEgoFY291bnQYASABKARIAIgBARJACgZmaWx0ZXIYAiABKAsyKy5vbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxLkRpc2N1c3Npb25GaWx0ZXJIAYgBARIWCg5kaXNjdXNzaW9uX2lkcxgDIAMoBEIICgZfY291bnRCCQoHX2ZpbHRlciJZChxEaXNjdXNzaW9uTG9ja2VkTm90aWZpY2F0aW9uEjkKCmRpc2N1c3Npb24YASABKAsyJS5vbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxLkRpc2N1c3Npb24isgEKLVN1YnNjcmliZVRvRGlzY3Vzc2lvblRpdGxlVXBkYXRlZE5vdGlmaWNhdGlvbhISCgVjb3VudBgBIAEoBEgAiAEBEkAKBmZpbHRlchgCIAEoCzIrLm9sdmlkLmRhZW1vbi5kYXRhdHlwZXMudjEuRGlzY3Vzc2lvbkZpbHRlckgBiAEBEhYKDmRpc2N1c3Npb25faWRzGAMgAygEQggKBl9jb3VudEIJCgdfZmlsdGVyIncKIkRpc2N1c3Npb25UaXRsZVVwZGF0ZWROb3RpZmljYXRpb24SOQoKZGlzY3Vzc2lvbhgBIAEoCzIlLm9sdmlkLmRhZW1vbi5kYXRhdHlwZXMudjEuRGlzY3Vzc2lvbhIWCg5wcmV2aW91c190aXRsZRgCIAEoCSK1AQowU3Vic2NyaWJlVG9EaXNjdXNzaW9uU2V0dGluZ3NVcGRhdGVkTm90aWZpY2F0aW9uEhIKBWNvdW50GAEgASgESACIAQESQAoGZmlsdGVyGAIgASgLMisub2x2aWQuZGFlbW9uLmRhdGF0eXBlcy52MS5EaXNjdXNzaW9uRmlsdGVySAGIAQESFgoOZGlzY3Vzc2lvbl9pZHMYAyADKARCCAoGX2NvdW50QgkKB19maWx0ZXIi8QEKJURpc2N1c3Npb25TZXR0aW5nc1VwZGF0ZWROb3RpZmljYXRpb24SOQoKZGlzY3Vzc2lvbhgBIAEoCzIlLm9sdmlkLmRhZW1vbi5kYXRhdHlwZXMudjEuRGlzY3Vzc2lvbhJDCgxuZXdfc2V0dGluZ3MYAiABKAsyLS5vbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxLkRpc2N1c3Npb25TZXR0aW5ncxJIChFwcmV2aW91c19zZXR0aW5ncxgDIAEoCzItLm9sdmlkLmRhZW1vbi5kYXRhdHlwZXMudjEuRGlzY3Vzc2lvblNldHRpbmdzQjUKIGlvLm9sdmlkLmRlc2t0b3AuZGFlbW9uLnByb3RvYnVmUAFaD29sdmlkLmlvL2RhZW1vbmIGcHJvdG8z", [file_olvid_daemon_datatypes_v1_discussion, file_olvid_daemon_datatypes_v1_settings]);

/**
 *
 * * DiscussionNew
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToDiscussionNewNotification
 */
export type SubscribeToDiscussionNewNotification = Message<"olvid.daemon.notification.v1.SubscribeToDiscussionNewNotification"> & {
  /**
   * @generated from field: optional uint64 count = 1;
   */
  count?: bigint;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.DiscussionFilter filter = 2;
   */
  filter?: DiscussionFilter;
};

/**
 * Describes the message olvid.daemon.notification.v1.SubscribeToDiscussionNewNotification.
 * Use `create(SubscribeToDiscussionNewNotificationSchema)` to create a new message.
 */
export const SubscribeToDiscussionNewNotificationSchema: GenMessage<SubscribeToDiscussionNewNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_discussion_notifications, 0);

/**
 * @generated from message olvid.daemon.notification.v1.DiscussionNewNotification
 */
export type DiscussionNewNotification = Message<"olvid.daemon.notification.v1.DiscussionNewNotification"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Discussion discussion = 1;
   */
  discussion?: Discussion;
};

/**
 * Describes the message olvid.daemon.notification.v1.DiscussionNewNotification.
 * Use `create(DiscussionNewNotificationSchema)` to create a new message.
 */
export const DiscussionNewNotificationSchema: GenMessage<DiscussionNewNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_discussion_notifications, 1);

/**
 *
 * * DiscussionLocked
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToDiscussionLockedNotification
 */
export type SubscribeToDiscussionLockedNotification = Message<"olvid.daemon.notification.v1.SubscribeToDiscussionLockedNotification"> & {
  /**
   * @generated from field: optional uint64 count = 1;
   */
  count?: bigint;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.DiscussionFilter filter = 2;
   */
  filter?: DiscussionFilter;

  /**
   * @generated from field: repeated uint64 discussion_ids = 3;
   */
  discussionIds: bigint[];
};

/**
 * Describes the message olvid.daemon.notification.v1.SubscribeToDiscussionLockedNotification.
 * Use `create(SubscribeToDiscussionLockedNotificationSchema)` to create a new message.
 */
export const SubscribeToDiscussionLockedNotificationSchema: GenMessage<SubscribeToDiscussionLockedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_discussion_notifications, 2);

/**
 * @generated from message olvid.daemon.notification.v1.DiscussionLockedNotification
 */
export type DiscussionLockedNotification = Message<"olvid.daemon.notification.v1.DiscussionLockedNotification"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Discussion discussion = 1;
   */
  discussion?: Discussion;
};

/**
 * Describes the message olvid.daemon.notification.v1.DiscussionLockedNotification.
 * Use `create(DiscussionLockedNotificationSchema)` to create a new message.
 */
export const DiscussionLockedNotificationSchema: GenMessage<DiscussionLockedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_discussion_notifications, 3);

/**
 *
 * * DiscussionTitleUpdated
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToDiscussionTitleUpdatedNotification
 */
export type SubscribeToDiscussionTitleUpdatedNotification = Message<"olvid.daemon.notification.v1.SubscribeToDiscussionTitleUpdatedNotification"> & {
  /**
   * @generated from field: optional uint64 count = 1;
   */
  count?: bigint;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.DiscussionFilter filter = 2;
   */
  filter?: DiscussionFilter;

  /**
   * @generated from field: repeated uint64 discussion_ids = 3;
   */
  discussionIds: bigint[];
};

/**
 * Describes the message olvid.daemon.notification.v1.SubscribeToDiscussionTitleUpdatedNotification.
 * Use `create(SubscribeToDiscussionTitleUpdatedNotificationSchema)` to create a new message.
 */
export const SubscribeToDiscussionTitleUpdatedNotificationSchema: GenMessage<SubscribeToDiscussionTitleUpdatedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_discussion_notifications, 4);

/**
 * @generated from message olvid.daemon.notification.v1.DiscussionTitleUpdatedNotification
 */
export type DiscussionTitleUpdatedNotification = Message<"olvid.daemon.notification.v1.DiscussionTitleUpdatedNotification"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Discussion discussion = 1;
   */
  discussion?: Discussion;

  /**
   * @generated from field: string previous_title = 2;
   */
  previousTitle: string;
};

/**
 * Describes the message olvid.daemon.notification.v1.DiscussionTitleUpdatedNotification.
 * Use `create(DiscussionTitleUpdatedNotificationSchema)` to create a new message.
 */
export const DiscussionTitleUpdatedNotificationSchema: GenMessage<DiscussionTitleUpdatedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_discussion_notifications, 5);

/**
 *
 * * DiscussionSettingsUpdated
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToDiscussionSettingsUpdatedNotification
 */
export type SubscribeToDiscussionSettingsUpdatedNotification = Message<"olvid.daemon.notification.v1.SubscribeToDiscussionSettingsUpdatedNotification"> & {
  /**
   * @generated from field: optional uint64 count = 1;
   */
  count?: bigint;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.DiscussionFilter filter = 2;
   */
  filter?: DiscussionFilter;

  /**
   * @generated from field: repeated uint64 discussion_ids = 3;
   */
  discussionIds: bigint[];
};

/**
 * Describes the message olvid.daemon.notification.v1.SubscribeToDiscussionSettingsUpdatedNotification.
 * Use `create(SubscribeToDiscussionSettingsUpdatedNotificationSchema)` to create a new message.
 */
export const SubscribeToDiscussionSettingsUpdatedNotificationSchema: GenMessage<SubscribeToDiscussionSettingsUpdatedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_discussion_notifications, 6);

/**
 * @generated from message olvid.daemon.notification.v1.DiscussionSettingsUpdatedNotification
 */
export type DiscussionSettingsUpdatedNotification = Message<"olvid.daemon.notification.v1.DiscussionSettingsUpdatedNotification"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Discussion discussion = 1;
   */
  discussion?: Discussion;

  /**
   * @generated from field: olvid.daemon.datatypes.v1.DiscussionSettings new_settings = 2;
   */
  newSettings?: DiscussionSettings;

  /**
   * @generated from field: olvid.daemon.datatypes.v1.DiscussionSettings previous_settings = 3;
   */
  previousSettings?: DiscussionSettings;
};

/**
 * Describes the message olvid.daemon.notification.v1.DiscussionSettingsUpdatedNotification.
 * Use `create(DiscussionSettingsUpdatedNotificationSchema)` to create a new message.
 */
export const DiscussionSettingsUpdatedNotificationSchema: GenMessage<DiscussionSettingsUpdatedNotification> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_notification_v1_discussion_notifications, 7);

