// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file olvid/daemon/notification/v1/group_notifications.proto (package olvid.daemon.notification.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Group, GroupMember, GroupMemberPermissions, PendingGroupMember } from "../../datatypes/v1/group_pb.js";

/**
 *
 * * GroupNew
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToGroupNewNotification
 */
export class SubscribeToGroupNewNotification extends Message<SubscribeToGroupNewNotification> {
  constructor(data?: PartialMessage<SubscribeToGroupNewNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.SubscribeToGroupNewNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscribeToGroupNewNotification {
    return new SubscribeToGroupNewNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscribeToGroupNewNotification {
    return new SubscribeToGroupNewNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscribeToGroupNewNotification {
    return new SubscribeToGroupNewNotification().fromJsonString(jsonString, options);
  }

  static equals(a: SubscribeToGroupNewNotification | PlainMessage<SubscribeToGroupNewNotification> | undefined, b: SubscribeToGroupNewNotification | PlainMessage<SubscribeToGroupNewNotification> | undefined): boolean {
    return proto3.util.equals(SubscribeToGroupNewNotification, a, b);
  }
}

/**
 * @generated from message olvid.daemon.notification.v1.GroupNewNotification
 */
export class GroupNewNotification extends Message<GroupNewNotification> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Group group = 1;
   */
  group?: Group;

  constructor(data?: PartialMessage<GroupNewNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.GroupNewNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group", kind: "message", T: Group },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GroupNewNotification {
    return new GroupNewNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GroupNewNotification {
    return new GroupNewNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GroupNewNotification {
    return new GroupNewNotification().fromJsonString(jsonString, options);
  }

  static equals(a: GroupNewNotification | PlainMessage<GroupNewNotification> | undefined, b: GroupNewNotification | PlainMessage<GroupNewNotification> | undefined): boolean {
    return proto3.util.equals(GroupNewNotification, a, b);
  }
}

/**
 *
 * * GroupDeleted
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToGroupDeletedNotification
 */
export class SubscribeToGroupDeletedNotification extends Message<SubscribeToGroupDeletedNotification> {
  constructor(data?: PartialMessage<SubscribeToGroupDeletedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.SubscribeToGroupDeletedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscribeToGroupDeletedNotification {
    return new SubscribeToGroupDeletedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscribeToGroupDeletedNotification {
    return new SubscribeToGroupDeletedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscribeToGroupDeletedNotification {
    return new SubscribeToGroupDeletedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: SubscribeToGroupDeletedNotification | PlainMessage<SubscribeToGroupDeletedNotification> | undefined, b: SubscribeToGroupDeletedNotification | PlainMessage<SubscribeToGroupDeletedNotification> | undefined): boolean {
    return proto3.util.equals(SubscribeToGroupDeletedNotification, a, b);
  }
}

/**
 * @generated from message olvid.daemon.notification.v1.GroupDeletedNotification
 */
export class GroupDeletedNotification extends Message<GroupDeletedNotification> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Group group = 1;
   */
  group?: Group;

  constructor(data?: PartialMessage<GroupDeletedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.GroupDeletedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group", kind: "message", T: Group },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GroupDeletedNotification {
    return new GroupDeletedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GroupDeletedNotification {
    return new GroupDeletedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GroupDeletedNotification {
    return new GroupDeletedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: GroupDeletedNotification | PlainMessage<GroupDeletedNotification> | undefined, b: GroupDeletedNotification | PlainMessage<GroupDeletedNotification> | undefined): boolean {
    return proto3.util.equals(GroupDeletedNotification, a, b);
  }
}

/**
 *
 * * GroupNameUpdated
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToGroupNameUpdatedNotification
 */
export class SubscribeToGroupNameUpdatedNotification extends Message<SubscribeToGroupNameUpdatedNotification> {
  constructor(data?: PartialMessage<SubscribeToGroupNameUpdatedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.SubscribeToGroupNameUpdatedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscribeToGroupNameUpdatedNotification {
    return new SubscribeToGroupNameUpdatedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscribeToGroupNameUpdatedNotification {
    return new SubscribeToGroupNameUpdatedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscribeToGroupNameUpdatedNotification {
    return new SubscribeToGroupNameUpdatedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: SubscribeToGroupNameUpdatedNotification | PlainMessage<SubscribeToGroupNameUpdatedNotification> | undefined, b: SubscribeToGroupNameUpdatedNotification | PlainMessage<SubscribeToGroupNameUpdatedNotification> | undefined): boolean {
    return proto3.util.equals(SubscribeToGroupNameUpdatedNotification, a, b);
  }
}

/**
 * @generated from message olvid.daemon.notification.v1.GroupNameUpdatedNotification
 */
export class GroupNameUpdatedNotification extends Message<GroupNameUpdatedNotification> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Group group = 1;
   */
  group?: Group;

  /**
   * @generated from field: string previous_name = 2;
   */
  previousName = "";

  constructor(data?: PartialMessage<GroupNameUpdatedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.GroupNameUpdatedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group", kind: "message", T: Group },
    { no: 2, name: "previous_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GroupNameUpdatedNotification {
    return new GroupNameUpdatedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GroupNameUpdatedNotification {
    return new GroupNameUpdatedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GroupNameUpdatedNotification {
    return new GroupNameUpdatedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: GroupNameUpdatedNotification | PlainMessage<GroupNameUpdatedNotification> | undefined, b: GroupNameUpdatedNotification | PlainMessage<GroupNameUpdatedNotification> | undefined): boolean {
    return proto3.util.equals(GroupNameUpdatedNotification, a, b);
  }
}

/**
 *
 * * GroupPhotoUpdated
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToGroupPhotoUpdatedNotification
 */
export class SubscribeToGroupPhotoUpdatedNotification extends Message<SubscribeToGroupPhotoUpdatedNotification> {
  constructor(data?: PartialMessage<SubscribeToGroupPhotoUpdatedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.SubscribeToGroupPhotoUpdatedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscribeToGroupPhotoUpdatedNotification {
    return new SubscribeToGroupPhotoUpdatedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscribeToGroupPhotoUpdatedNotification {
    return new SubscribeToGroupPhotoUpdatedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscribeToGroupPhotoUpdatedNotification {
    return new SubscribeToGroupPhotoUpdatedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: SubscribeToGroupPhotoUpdatedNotification | PlainMessage<SubscribeToGroupPhotoUpdatedNotification> | undefined, b: SubscribeToGroupPhotoUpdatedNotification | PlainMessage<SubscribeToGroupPhotoUpdatedNotification> | undefined): boolean {
    return proto3.util.equals(SubscribeToGroupPhotoUpdatedNotification, a, b);
  }
}

/**
 * @generated from message olvid.daemon.notification.v1.GroupPhotoUpdatedNotification
 */
export class GroupPhotoUpdatedNotification extends Message<GroupPhotoUpdatedNotification> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Group group = 1;
   */
  group?: Group;

  constructor(data?: PartialMessage<GroupPhotoUpdatedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.GroupPhotoUpdatedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group", kind: "message", T: Group },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GroupPhotoUpdatedNotification {
    return new GroupPhotoUpdatedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GroupPhotoUpdatedNotification {
    return new GroupPhotoUpdatedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GroupPhotoUpdatedNotification {
    return new GroupPhotoUpdatedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: GroupPhotoUpdatedNotification | PlainMessage<GroupPhotoUpdatedNotification> | undefined, b: GroupPhotoUpdatedNotification | PlainMessage<GroupPhotoUpdatedNotification> | undefined): boolean {
    return proto3.util.equals(GroupPhotoUpdatedNotification, a, b);
  }
}

/**
 *
 * * GroupDescriptionUpdated
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToGroupDescriptionUpdatedNotification
 */
export class SubscribeToGroupDescriptionUpdatedNotification extends Message<SubscribeToGroupDescriptionUpdatedNotification> {
  constructor(data?: PartialMessage<SubscribeToGroupDescriptionUpdatedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.SubscribeToGroupDescriptionUpdatedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscribeToGroupDescriptionUpdatedNotification {
    return new SubscribeToGroupDescriptionUpdatedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscribeToGroupDescriptionUpdatedNotification {
    return new SubscribeToGroupDescriptionUpdatedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscribeToGroupDescriptionUpdatedNotification {
    return new SubscribeToGroupDescriptionUpdatedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: SubscribeToGroupDescriptionUpdatedNotification | PlainMessage<SubscribeToGroupDescriptionUpdatedNotification> | undefined, b: SubscribeToGroupDescriptionUpdatedNotification | PlainMessage<SubscribeToGroupDescriptionUpdatedNotification> | undefined): boolean {
    return proto3.util.equals(SubscribeToGroupDescriptionUpdatedNotification, a, b);
  }
}

/**
 * @generated from message olvid.daemon.notification.v1.GroupDescriptionUpdatedNotification
 */
export class GroupDescriptionUpdatedNotification extends Message<GroupDescriptionUpdatedNotification> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Group group = 1;
   */
  group?: Group;

  /**
   * @generated from field: string previous_description = 2;
   */
  previousDescription = "";

  constructor(data?: PartialMessage<GroupDescriptionUpdatedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.GroupDescriptionUpdatedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group", kind: "message", T: Group },
    { no: 2, name: "previous_description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GroupDescriptionUpdatedNotification {
    return new GroupDescriptionUpdatedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GroupDescriptionUpdatedNotification {
    return new GroupDescriptionUpdatedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GroupDescriptionUpdatedNotification {
    return new GroupDescriptionUpdatedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: GroupDescriptionUpdatedNotification | PlainMessage<GroupDescriptionUpdatedNotification> | undefined, b: GroupDescriptionUpdatedNotification | PlainMessage<GroupDescriptionUpdatedNotification> | undefined): boolean {
    return proto3.util.equals(GroupDescriptionUpdatedNotification, a, b);
  }
}

/**
 *
 * * GroupPendingMemberAdded
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToGroupPendingMemberAddedNotification
 */
export class SubscribeToGroupPendingMemberAddedNotification extends Message<SubscribeToGroupPendingMemberAddedNotification> {
  constructor(data?: PartialMessage<SubscribeToGroupPendingMemberAddedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.SubscribeToGroupPendingMemberAddedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscribeToGroupPendingMemberAddedNotification {
    return new SubscribeToGroupPendingMemberAddedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscribeToGroupPendingMemberAddedNotification {
    return new SubscribeToGroupPendingMemberAddedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscribeToGroupPendingMemberAddedNotification {
    return new SubscribeToGroupPendingMemberAddedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: SubscribeToGroupPendingMemberAddedNotification | PlainMessage<SubscribeToGroupPendingMemberAddedNotification> | undefined, b: SubscribeToGroupPendingMemberAddedNotification | PlainMessage<SubscribeToGroupPendingMemberAddedNotification> | undefined): boolean {
    return proto3.util.equals(SubscribeToGroupPendingMemberAddedNotification, a, b);
  }
}

/**
 * @generated from message olvid.daemon.notification.v1.GroupPendingMemberAddedNotification
 */
export class GroupPendingMemberAddedNotification extends Message<GroupPendingMemberAddedNotification> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Group group = 1;
   */
  group?: Group;

  /**
   * @generated from field: olvid.daemon.datatypes.v1.PendingGroupMember pending_member = 2;
   */
  pendingMember?: PendingGroupMember;

  constructor(data?: PartialMessage<GroupPendingMemberAddedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.GroupPendingMemberAddedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group", kind: "message", T: Group },
    { no: 2, name: "pending_member", kind: "message", T: PendingGroupMember },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GroupPendingMemberAddedNotification {
    return new GroupPendingMemberAddedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GroupPendingMemberAddedNotification {
    return new GroupPendingMemberAddedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GroupPendingMemberAddedNotification {
    return new GroupPendingMemberAddedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: GroupPendingMemberAddedNotification | PlainMessage<GroupPendingMemberAddedNotification> | undefined, b: GroupPendingMemberAddedNotification | PlainMessage<GroupPendingMemberAddedNotification> | undefined): boolean {
    return proto3.util.equals(GroupPendingMemberAddedNotification, a, b);
  }
}

/**
 *
 * * GroupPendingMemberRemoved
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToGroupPendingMemberRemovedNotification
 */
export class SubscribeToGroupPendingMemberRemovedNotification extends Message<SubscribeToGroupPendingMemberRemovedNotification> {
  constructor(data?: PartialMessage<SubscribeToGroupPendingMemberRemovedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.SubscribeToGroupPendingMemberRemovedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscribeToGroupPendingMemberRemovedNotification {
    return new SubscribeToGroupPendingMemberRemovedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscribeToGroupPendingMemberRemovedNotification {
    return new SubscribeToGroupPendingMemberRemovedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscribeToGroupPendingMemberRemovedNotification {
    return new SubscribeToGroupPendingMemberRemovedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: SubscribeToGroupPendingMemberRemovedNotification | PlainMessage<SubscribeToGroupPendingMemberRemovedNotification> | undefined, b: SubscribeToGroupPendingMemberRemovedNotification | PlainMessage<SubscribeToGroupPendingMemberRemovedNotification> | undefined): boolean {
    return proto3.util.equals(SubscribeToGroupPendingMemberRemovedNotification, a, b);
  }
}

/**
 * @generated from message olvid.daemon.notification.v1.GroupPendingMemberRemovedNotification
 */
export class GroupPendingMemberRemovedNotification extends Message<GroupPendingMemberRemovedNotification> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Group group = 1;
   */
  group?: Group;

  /**
   * @generated from field: olvid.daemon.datatypes.v1.PendingGroupMember pending_member = 2;
   */
  pendingMember?: PendingGroupMember;

  constructor(data?: PartialMessage<GroupPendingMemberRemovedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.GroupPendingMemberRemovedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group", kind: "message", T: Group },
    { no: 2, name: "pending_member", kind: "message", T: PendingGroupMember },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GroupPendingMemberRemovedNotification {
    return new GroupPendingMemberRemovedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GroupPendingMemberRemovedNotification {
    return new GroupPendingMemberRemovedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GroupPendingMemberRemovedNotification {
    return new GroupPendingMemberRemovedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: GroupPendingMemberRemovedNotification | PlainMessage<GroupPendingMemberRemovedNotification> | undefined, b: GroupPendingMemberRemovedNotification | PlainMessage<GroupPendingMemberRemovedNotification> | undefined): boolean {
    return proto3.util.equals(GroupPendingMemberRemovedNotification, a, b);
  }
}

/**
 *
 * * GroupMemberJoined
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToGroupMemberJoinedNotification
 */
export class SubscribeToGroupMemberJoinedNotification extends Message<SubscribeToGroupMemberJoinedNotification> {
  constructor(data?: PartialMessage<SubscribeToGroupMemberJoinedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.SubscribeToGroupMemberJoinedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscribeToGroupMemberJoinedNotification {
    return new SubscribeToGroupMemberJoinedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscribeToGroupMemberJoinedNotification {
    return new SubscribeToGroupMemberJoinedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscribeToGroupMemberJoinedNotification {
    return new SubscribeToGroupMemberJoinedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: SubscribeToGroupMemberJoinedNotification | PlainMessage<SubscribeToGroupMemberJoinedNotification> | undefined, b: SubscribeToGroupMemberJoinedNotification | PlainMessage<SubscribeToGroupMemberJoinedNotification> | undefined): boolean {
    return proto3.util.equals(SubscribeToGroupMemberJoinedNotification, a, b);
  }
}

/**
 * @generated from message olvid.daemon.notification.v1.GroupMemberJoinedNotification
 */
export class GroupMemberJoinedNotification extends Message<GroupMemberJoinedNotification> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Group group = 1;
   */
  group?: Group;

  /**
   * @generated from field: olvid.daemon.datatypes.v1.GroupMember member = 2;
   */
  member?: GroupMember;

  constructor(data?: PartialMessage<GroupMemberJoinedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.GroupMemberJoinedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group", kind: "message", T: Group },
    { no: 2, name: "member", kind: "message", T: GroupMember },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GroupMemberJoinedNotification {
    return new GroupMemberJoinedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GroupMemberJoinedNotification {
    return new GroupMemberJoinedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GroupMemberJoinedNotification {
    return new GroupMemberJoinedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: GroupMemberJoinedNotification | PlainMessage<GroupMemberJoinedNotification> | undefined, b: GroupMemberJoinedNotification | PlainMessage<GroupMemberJoinedNotification> | undefined): boolean {
    return proto3.util.equals(GroupMemberJoinedNotification, a, b);
  }
}

/**
 *
 * * GroupMemberLeft
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToGroupMemberLeftNotification
 */
export class SubscribeToGroupMemberLeftNotification extends Message<SubscribeToGroupMemberLeftNotification> {
  constructor(data?: PartialMessage<SubscribeToGroupMemberLeftNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.SubscribeToGroupMemberLeftNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscribeToGroupMemberLeftNotification {
    return new SubscribeToGroupMemberLeftNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscribeToGroupMemberLeftNotification {
    return new SubscribeToGroupMemberLeftNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscribeToGroupMemberLeftNotification {
    return new SubscribeToGroupMemberLeftNotification().fromJsonString(jsonString, options);
  }

  static equals(a: SubscribeToGroupMemberLeftNotification | PlainMessage<SubscribeToGroupMemberLeftNotification> | undefined, b: SubscribeToGroupMemberLeftNotification | PlainMessage<SubscribeToGroupMemberLeftNotification> | undefined): boolean {
    return proto3.util.equals(SubscribeToGroupMemberLeftNotification, a, b);
  }
}

/**
 * @generated from message olvid.daemon.notification.v1.GroupMemberLeftNotification
 */
export class GroupMemberLeftNotification extends Message<GroupMemberLeftNotification> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Group group = 1;
   */
  group?: Group;

  /**
   * @generated from field: olvid.daemon.datatypes.v1.GroupMember member = 2;
   */
  member?: GroupMember;

  constructor(data?: PartialMessage<GroupMemberLeftNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.GroupMemberLeftNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group", kind: "message", T: Group },
    { no: 2, name: "member", kind: "message", T: GroupMember },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GroupMemberLeftNotification {
    return new GroupMemberLeftNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GroupMemberLeftNotification {
    return new GroupMemberLeftNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GroupMemberLeftNotification {
    return new GroupMemberLeftNotification().fromJsonString(jsonString, options);
  }

  static equals(a: GroupMemberLeftNotification | PlainMessage<GroupMemberLeftNotification> | undefined, b: GroupMemberLeftNotification | PlainMessage<GroupMemberLeftNotification> | undefined): boolean {
    return proto3.util.equals(GroupMemberLeftNotification, a, b);
  }
}

/**
 *
 * * GroupPermissionsUpdated
 * * triggered when your permissions are updated
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToGroupOwnPermissionsUpdatedNotification
 */
export class SubscribeToGroupOwnPermissionsUpdatedNotification extends Message<SubscribeToGroupOwnPermissionsUpdatedNotification> {
  constructor(data?: PartialMessage<SubscribeToGroupOwnPermissionsUpdatedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.SubscribeToGroupOwnPermissionsUpdatedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscribeToGroupOwnPermissionsUpdatedNotification {
    return new SubscribeToGroupOwnPermissionsUpdatedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscribeToGroupOwnPermissionsUpdatedNotification {
    return new SubscribeToGroupOwnPermissionsUpdatedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscribeToGroupOwnPermissionsUpdatedNotification {
    return new SubscribeToGroupOwnPermissionsUpdatedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: SubscribeToGroupOwnPermissionsUpdatedNotification | PlainMessage<SubscribeToGroupOwnPermissionsUpdatedNotification> | undefined, b: SubscribeToGroupOwnPermissionsUpdatedNotification | PlainMessage<SubscribeToGroupOwnPermissionsUpdatedNotification> | undefined): boolean {
    return proto3.util.equals(SubscribeToGroupOwnPermissionsUpdatedNotification, a, b);
  }
}

/**
 * @generated from message olvid.daemon.notification.v1.GroupOwnPermissionsUpdatedNotification
 */
export class GroupOwnPermissionsUpdatedNotification extends Message<GroupOwnPermissionsUpdatedNotification> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Group group = 1;
   */
  group?: Group;

  /**
   * @generated from field: olvid.daemon.datatypes.v1.GroupMemberPermissions permissions = 2;
   */
  permissions?: GroupMemberPermissions;

  /**
   * @generated from field: olvid.daemon.datatypes.v1.GroupMemberPermissions previous_permissions = 3;
   */
  previousPermissions?: GroupMemberPermissions;

  constructor(data?: PartialMessage<GroupOwnPermissionsUpdatedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.GroupOwnPermissionsUpdatedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group", kind: "message", T: Group },
    { no: 2, name: "permissions", kind: "message", T: GroupMemberPermissions },
    { no: 3, name: "previous_permissions", kind: "message", T: GroupMemberPermissions },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GroupOwnPermissionsUpdatedNotification {
    return new GroupOwnPermissionsUpdatedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GroupOwnPermissionsUpdatedNotification {
    return new GroupOwnPermissionsUpdatedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GroupOwnPermissionsUpdatedNotification {
    return new GroupOwnPermissionsUpdatedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: GroupOwnPermissionsUpdatedNotification | PlainMessage<GroupOwnPermissionsUpdatedNotification> | undefined, b: GroupOwnPermissionsUpdatedNotification | PlainMessage<GroupOwnPermissionsUpdatedNotification> | undefined): boolean {
    return proto3.util.equals(GroupOwnPermissionsUpdatedNotification, a, b);
  }
}

/**
 *
 * * GroupMemberPermissionsUpdated
 * * triggered when permissions of a group member are updated
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToGroupMemberPermissionsUpdatedNotification
 */
export class SubscribeToGroupMemberPermissionsUpdatedNotification extends Message<SubscribeToGroupMemberPermissionsUpdatedNotification> {
  constructor(data?: PartialMessage<SubscribeToGroupMemberPermissionsUpdatedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.SubscribeToGroupMemberPermissionsUpdatedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscribeToGroupMemberPermissionsUpdatedNotification {
    return new SubscribeToGroupMemberPermissionsUpdatedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscribeToGroupMemberPermissionsUpdatedNotification {
    return new SubscribeToGroupMemberPermissionsUpdatedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscribeToGroupMemberPermissionsUpdatedNotification {
    return new SubscribeToGroupMemberPermissionsUpdatedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: SubscribeToGroupMemberPermissionsUpdatedNotification | PlainMessage<SubscribeToGroupMemberPermissionsUpdatedNotification> | undefined, b: SubscribeToGroupMemberPermissionsUpdatedNotification | PlainMessage<SubscribeToGroupMemberPermissionsUpdatedNotification> | undefined): boolean {
    return proto3.util.equals(SubscribeToGroupMemberPermissionsUpdatedNotification, a, b);
  }
}

/**
 * @generated from message olvid.daemon.notification.v1.GroupMemberPermissionsUpdatedNotification
 */
export class GroupMemberPermissionsUpdatedNotification extends Message<GroupMemberPermissionsUpdatedNotification> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.Group group = 1;
   */
  group?: Group;

  /**
   * not set if your permissions were updated
   *
   * @generated from field: olvid.daemon.datatypes.v1.GroupMember member = 2;
   */
  member?: GroupMember;

  /**
   * @generated from field: olvid.daemon.datatypes.v1.GroupMemberPermissions previous_permissions = 3;
   */
  previousPermissions?: GroupMemberPermissions;

  constructor(data?: PartialMessage<GroupMemberPermissionsUpdatedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.GroupMemberPermissionsUpdatedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group", kind: "message", T: Group },
    { no: 2, name: "member", kind: "message", T: GroupMember },
    { no: 3, name: "previous_permissions", kind: "message", T: GroupMemberPermissions },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GroupMemberPermissionsUpdatedNotification {
    return new GroupMemberPermissionsUpdatedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GroupMemberPermissionsUpdatedNotification {
    return new GroupMemberPermissionsUpdatedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GroupMemberPermissionsUpdatedNotification {
    return new GroupMemberPermissionsUpdatedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: GroupMemberPermissionsUpdatedNotification | PlainMessage<GroupMemberPermissionsUpdatedNotification> | undefined, b: GroupMemberPermissionsUpdatedNotification | PlainMessage<GroupMemberPermissionsUpdatedNotification> | undefined): boolean {
    return proto3.util.equals(GroupMemberPermissionsUpdatedNotification, a, b);
  }
}

/**
 * deprecated
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToGroupUpdateInProgressNotification
 */
export class SubscribeToGroupUpdateInProgressNotification extends Message<SubscribeToGroupUpdateInProgressNotification> {
  constructor(data?: PartialMessage<SubscribeToGroupUpdateInProgressNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.SubscribeToGroupUpdateInProgressNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscribeToGroupUpdateInProgressNotification {
    return new SubscribeToGroupUpdateInProgressNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscribeToGroupUpdateInProgressNotification {
    return new SubscribeToGroupUpdateInProgressNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscribeToGroupUpdateInProgressNotification {
    return new SubscribeToGroupUpdateInProgressNotification().fromJsonString(jsonString, options);
  }

  static equals(a: SubscribeToGroupUpdateInProgressNotification | PlainMessage<SubscribeToGroupUpdateInProgressNotification> | undefined, b: SubscribeToGroupUpdateInProgressNotification | PlainMessage<SubscribeToGroupUpdateInProgressNotification> | undefined): boolean {
    return proto3.util.equals(SubscribeToGroupUpdateInProgressNotification, a, b);
  }
}

/**
 * @generated from message olvid.daemon.notification.v1.GroupUpdateInProgressNotification
 */
export class GroupUpdateInProgressNotification extends Message<GroupUpdateInProgressNotification> {
  /**
   * @generated from field: uint64 group_id = 1;
   */
  groupId = protoInt64.zero;

  constructor(data?: PartialMessage<GroupUpdateInProgressNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.GroupUpdateInProgressNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GroupUpdateInProgressNotification {
    return new GroupUpdateInProgressNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GroupUpdateInProgressNotification {
    return new GroupUpdateInProgressNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GroupUpdateInProgressNotification {
    return new GroupUpdateInProgressNotification().fromJsonString(jsonString, options);
  }

  static equals(a: GroupUpdateInProgressNotification | PlainMessage<GroupUpdateInProgressNotification> | undefined, b: GroupUpdateInProgressNotification | PlainMessage<GroupUpdateInProgressNotification> | undefined): boolean {
    return proto3.util.equals(GroupUpdateInProgressNotification, a, b);
  }
}

/**
 * deprecated
 *
 * @generated from message olvid.daemon.notification.v1.SubscribeToGroupUpdateFinishedNotification
 */
export class SubscribeToGroupUpdateFinishedNotification extends Message<SubscribeToGroupUpdateFinishedNotification> {
  constructor(data?: PartialMessage<SubscribeToGroupUpdateFinishedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.SubscribeToGroupUpdateFinishedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscribeToGroupUpdateFinishedNotification {
    return new SubscribeToGroupUpdateFinishedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscribeToGroupUpdateFinishedNotification {
    return new SubscribeToGroupUpdateFinishedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscribeToGroupUpdateFinishedNotification {
    return new SubscribeToGroupUpdateFinishedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: SubscribeToGroupUpdateFinishedNotification | PlainMessage<SubscribeToGroupUpdateFinishedNotification> | undefined, b: SubscribeToGroupUpdateFinishedNotification | PlainMessage<SubscribeToGroupUpdateFinishedNotification> | undefined): boolean {
    return proto3.util.equals(SubscribeToGroupUpdateFinishedNotification, a, b);
  }
}

/**
 * @generated from message olvid.daemon.notification.v1.GroupUpdateFinishedNotification
 */
export class GroupUpdateFinishedNotification extends Message<GroupUpdateFinishedNotification> {
  /**
   * @generated from field: uint64 group_id = 1;
   */
  groupId = protoInt64.zero;

  constructor(data?: PartialMessage<GroupUpdateFinishedNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.notification.v1.GroupUpdateFinishedNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GroupUpdateFinishedNotification {
    return new GroupUpdateFinishedNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GroupUpdateFinishedNotification {
    return new GroupUpdateFinishedNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GroupUpdateFinishedNotification {
    return new GroupUpdateFinishedNotification().fromJsonString(jsonString, options);
  }

  static equals(a: GroupUpdateFinishedNotification | PlainMessage<GroupUpdateFinishedNotification> | undefined, b: GroupUpdateFinishedNotification | PlainMessage<GroupUpdateFinishedNotification> | undefined): boolean {
    return proto3.util.equals(GroupUpdateFinishedNotification, a, b);
  }
}

