// noinspection ExceptionCaughtLocallyJS

import {
	createEcmaScriptPlugin,
	runNodeJs,
	type Schema,
} from '@bufbuild/protoplugin';
import { generateAction } from './nodes/actions/generateAction';
import { overrideActionFile, overrideTriggerFile } from './nodes/overrideFile';
import { generateActionProperties } from './nodes/actions/generateActionProperties';
import { generateTrigger } from './nodes/triggers/generateTrigger';
import { generateTriggerProperties } from './nodes/triggers/generateTriggerProperties';
import { generateTriggerMap } from './nodes/triggers/generateTriggerMap';
// @ts-ignore
import type { DescFile, DescService, DescMethod, } from "@bufbuild/protobuf/dist/cjs/descriptors"
import { generateActionMap } from './nodes/actions/generateActionMap';

// noinspection JSUnusedGlobalSymbols
const plugin = createEcmaScriptPlugin({
	name: 'protoc-gen-advanced-node',
	version: 'v1',
	generateTs(schema: Schema) {
		try {
			const preamble = `// @generated by ${this.name} ${this.version} with parameter "target=ts"`;
			const actionServices: DescService[] = schema.files.flatMap((f: DescFile) => f.services).filter(s => s.name.endsWith('CommandService'));
			const actionMethods: DescMethod[] = actionServices.flatMap((s: DescService) => s.methods);
			const triggerServices: DescService[] = schema.files.flatMap(f => f.services).filter(s => s.name.endsWith('NotificationService'));
			const triggerMethods: DescMethod[] = triggerServices.flatMap(s => s.methods);

			// check there is not an unknown service type
			const unknownServices = schema.files.flatMap(f => f.services).filter(s => !s.name.endsWith('CommandService') && !s.name.endsWith('NotificationService') && !s.name.endsWith('AdminService'));
			if (unknownServices.length > 0) {
				throw new Error(`#--# GENERATION ERROR: Unrecognized service type for ${unknownServices}`);
			}

			/*
			** Actions generation
			 */
			// generate actions
			if (actionServices.length > 0) {
				for (const method of actionMethods) {
					// generate action handler and properties if not already in an override file
					const isOverwritten = overrideActionFile(schema, method);
					if (!isOverwritten) {
						generateAction(schema, method, false);
					}
				}

				// generate actions properties
				const triggerResourceDescriptionFile = schema.generateFile('actions/generatedProperties.ts');
				triggerResourceDescriptionFile.print(preamble);
				generateActionProperties(triggerResourceDescriptionFile, actionServices);

				// generate action router map
				const routerMapFile = schema.generateFile('actions/routerMap.ts');
				routerMapFile.print(preamble);
				generateActionMap(routerMapFile, actionServices);
			}

			/*
			** Triggers generation
			 */
			// generate triggers
			if (triggerServices.length > 0) {
				// generate trigger handler and properties
				for (const method of triggerMethods) {
					const isOverwritten = overrideTriggerFile(schema, method);
					if (!isOverwritten) {
						generateTrigger(schema, method, false);
					}
				}

				// generate trigger structure nodes
				// Trigger Resource Description
				const triggerResourceDescriptionFile = schema.generateFile('triggers/generatedProperties.ts');
				triggerResourceDescriptionFile.print(preamble);
				generateTriggerProperties(triggerResourceDescriptionFile, triggerServices);

				// generate trigger router map
				const routerMapFile = schema.generateFile('triggers/routerMap.ts');
				routerMapFile.print(preamble);
				generateTriggerMap(routerMapFile, triggerMethods);
			}
		}
		catch (e) {
			console.error(e);
			throw e
		}
	},
});

// Reads the schema from stdin, runs the plugin, and writes the generated nodes to stdout.
runNodeJs(plugin);
