// noinspection ExceptionCaughtLocallyJS

import {
	createEcmaScriptPlugin,
	runNodeJs,
	type Schema,
} from '@bufbuild/protoplugin';
import type { DescFile, DescService, } from "@bufbuild/protobuf"
import generateTriggers from './nodes/triggers/generateTriggers';
import generateActions from './nodes/actions/generateActions';

// noinspection JSUnusedGlobalSymbols
const plugin = createEcmaScriptPlugin({
	name: 'protoc-gen-advanced-node',
	version: 'v1',
	generateTs(schema: Schema<PluginOptions>) {
		try {
			const preamble = `// @generated by ${this.name} ${this.version}`;

			let actionServices: DescService[];
			let triggerServices: DescService[];
			if (schema.options.admin) {
				actionServices = schema.files.flatMap((f: DescFile) => f.services).filter(s => s.name.endsWith('AdminService'));
				triggerServices = schema.files.flatMap(f => f.services).filter(s => s.name.endsWith('AdminNotificationService'));
			}
			else {
				actionServices = schema.files.flatMap((f: DescFile) => f.services).filter(s => s.name.endsWith('CommandService'));
				triggerServices = schema.files.flatMap(f => f.services).filter(s => s.name.endsWith('NotificationService'));
			}

			// check if there is an unexpected service type
			const unknownServices = schema.files.flatMap(f => f.services).filter(s => !s.name.endsWith('CommandService') && !s.name.endsWith('NotificationService') && !s.name.endsWith('AdminService') && !s.name.endsWith('AdminNotificationService'));
			if (unknownServices.length > 0) {
				throw new Error(`#--# GENERATION ERROR: Unrecognized service type for ${unknownServices}`);
			}

			// generateAction actions
			if (actionServices.length > 0) {
				generateActions(schema, actionServices, preamble, schema.options.admin);
			}

			// generateAction triggers
			if (triggerServices.length > 0) {
				generateTriggers(schema, triggerServices, preamble, schema.options.admin);
			}
		}
		catch (e) {
			console.error(e);
			throw e
		}
	},
	parseOptions(rawOptions: {key: string, value: string}[]): PluginOptions {
		let admin: boolean = false;
		for (const {key, value} of rawOptions) {
			if (key === "admin") {
				if (!["true", "false"].includes(value)) {
					throw "Invalid admin option value";
				}
				admin = value === "true";
			}
			else {
				throw new Error(`Invalid option: ${key}`)
			}
		}
		return {admin: admin};
	},
});

interface PluginOptions {
	admin: boolean;
}
// Reads the schema from stdin, runs the plugin, and writes the generated nodes to stdout.
runNodeJs(plugin);
