// noinspection ExceptionCaughtLocallyJS

import {
	createEcmaScriptPlugin,
	runNodeJs,
	type Schema,
} from '@bufbuild/protoplugin';
import { generateAction } from './nodes/actions/generateAction';
import { overrideActionFile } from './nodes/overrideFile';
import { generateActionProperties } from './nodes/actions/generateActionProperties';
// @ts-ignore
import type { DescFile, DescService, DescMethod, } from "@bufbuild/protobuf/dist/cjs/descriptors"
import { generateActionMap } from './nodes/actions/generateActionMap';

const plugin = createEcmaScriptPlugin({
	name: 'protoc-gen-ava-actions',
	version: 'v1',
	generateTs(schema: Schema) {
		try {
			const preamble = `// @generated by ${this.name} ${this.version} with parameter "target=ts"`;
			const adminActionServices: DescService[] = schema.files.flatMap((f: DescFile) => f.services).filter(s => s.name.endsWith('AdminService'));
			const adminActionMethods: DescMethod[] = adminActionServices.flatMap((s: DescService) => s.methods);

			/*
			** Admin Actions generation
			 */
			if (adminActionServices.length > 0) {
				for (const method of adminActionMethods) {
					// generate action handler and properties if not already in an override file
					const isOverwritten = overrideActionFile(schema, method);
					if (!isOverwritten) {
						generateAction(schema, method, true);
					}
				}

				// generate actions properties
				const triggerResourceDescriptionFile = schema.generateFile('actions/generatedProperties.ts');
				triggerResourceDescriptionFile.print(preamble);
				generateActionProperties(triggerResourceDescriptionFile, adminActionServices);

				// generate action router map
				const routerMapFile = schema.generateFile('actions/routerMap.ts');
				routerMapFile.print(preamble);
				generateActionMap(routerMapFile, adminActionServices, true);
			}
		}
		catch (e) {
			console.error(e);
			throw e
		}
	},
});

// Reads the schema from stdin, runs the plugin, and writes the generated nodes to stdout.
runNodeJs(plugin);
