// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file olvid/daemon/datatypes/v1/attachment.proto (package olvid.daemon.datatypes.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { MessageId } from "./message_pb.js";

/**
 * @generated from message olvid.daemon.datatypes.v1.AttachmentId
 */
export class AttachmentId extends Message<AttachmentId> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.AttachmentId.Type type = 1;
   */
  type = AttachmentId_Type.UNSPECIFIED;

  /**
   * @generated from field: uint64 id = 2;
   */
  id = protoInt64.zero;

  constructor(data?: PartialMessage<AttachmentId>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.datatypes.v1.AttachmentId";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type", kind: "enum", T: proto3.getEnumType(AttachmentId_Type) },
    { no: 2, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AttachmentId {
    return new AttachmentId().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AttachmentId {
    return new AttachmentId().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AttachmentId {
    return new AttachmentId().fromJsonString(jsonString, options);
  }

  static equals(a: AttachmentId | PlainMessage<AttachmentId> | undefined, b: AttachmentId | PlainMessage<AttachmentId> | undefined): boolean {
    return proto3.util.equals(AttachmentId, a, b);
  }
}

/**
 * @generated from enum olvid.daemon.datatypes.v1.AttachmentId.Type
 */
export enum AttachmentId_Type {
  /**
   * @generated from enum value: TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TYPE_INBOUND = 1;
   */
  INBOUND = 1,

  /**
   * @generated from enum value: TYPE_OUTBOUND = 2;
   */
  OUTBOUND = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(AttachmentId_Type)
proto3.util.setEnumType(AttachmentId_Type, "olvid.daemon.datatypes.v1.AttachmentId.Type", [
  { no: 0, name: "TYPE_UNSPECIFIED" },
  { no: 1, name: "TYPE_INBOUND" },
  { no: 2, name: "TYPE_OUTBOUND" },
]);

/**
 * @generated from message olvid.daemon.datatypes.v1.Attachment
 */
export class Attachment extends Message<Attachment> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.AttachmentId id = 1;
   */
  id?: AttachmentId;

  /**
   * @generated from field: uint64 discussion_id = 2;
   */
  discussionId = protoInt64.zero;

  /**
   * @generated from field: olvid.daemon.datatypes.v1.MessageId message_id = 3;
   */
  messageId?: MessageId;

  /**
   * @generated from field: string file_name = 4;
   */
  fileName = "";

  /**
   * @generated from field: string mime_type = 5;
   */
  mimeType = "";

  /**
   * @generated from field: uint64 size = 6;
   */
  size = protoInt64.zero;

  constructor(data?: PartialMessage<Attachment>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.datatypes.v1.Attachment";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: AttachmentId },
    { no: 2, name: "discussion_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "message_id", kind: "message", T: MessageId },
    { no: 4, name: "file_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "mime_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "size", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Attachment {
    return new Attachment().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Attachment {
    return new Attachment().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Attachment {
    return new Attachment().fromJsonString(jsonString, options);
  }

  static equals(a: Attachment | PlainMessage<Attachment> | undefined, b: Attachment | PlainMessage<Attachment> | undefined): boolean {
    return proto3.util.equals(Attachment, a, b);
  }
}

/**
 * @generated from message olvid.daemon.datatypes.v1.AttachmentFilter
 */
export class AttachmentFilter extends Message<AttachmentFilter> {
  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.AttachmentId.Type type = 1;
   */
  type?: AttachmentId_Type;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.AttachmentFilter.FileType file_type = 2;
   */
  fileType?: AttachmentFilter_FileType;

  /**
   * @generated from field: optional uint64 discussion_id = 3;
   */
  discussionId?: bigint;

  /**
   *  optional uint64 contact_id = 4; not implementable now
   *
   * @generated from field: optional olvid.daemon.datatypes.v1.MessageId message_id = 5;
   */
  messageId?: MessageId;

  /**
   * @generated from field: optional string filename_search = 6;
   */
  filenameSearch?: string;

  /**
   * @generated from field: optional string mime_type_search = 7;
   */
  mimeTypeSearch?: string;

  /**
   * @generated from field: optional uint64 min_size = 8;
   */
  minSize?: bigint;

  /**
   * @generated from field: optional uint64 max_size = 9;
   */
  maxSize?: bigint;

  constructor(data?: PartialMessage<AttachmentFilter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.datatypes.v1.AttachmentFilter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type", kind: "enum", T: proto3.getEnumType(AttachmentId_Type), opt: true },
    { no: 2, name: "file_type", kind: "enum", T: proto3.getEnumType(AttachmentFilter_FileType), opt: true },
    { no: 3, name: "discussion_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 5, name: "message_id", kind: "message", T: MessageId, opt: true },
    { no: 6, name: "filename_search", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "mime_type_search", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 8, name: "min_size", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 9, name: "max_size", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AttachmentFilter {
    return new AttachmentFilter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AttachmentFilter {
    return new AttachmentFilter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AttachmentFilter {
    return new AttachmentFilter().fromJsonString(jsonString, options);
  }

  static equals(a: AttachmentFilter | PlainMessage<AttachmentFilter> | undefined, b: AttachmentFilter | PlainMessage<AttachmentFilter> | undefined): boolean {
    return proto3.util.equals(AttachmentFilter, a, b);
  }
}

/**
 * @generated from enum olvid.daemon.datatypes.v1.AttachmentFilter.FileType
 */
export enum AttachmentFilter_FileType {
  /**
   * @generated from enum value: FILE_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: FILE_TYPE_IMAGE = 3;
   */
  IMAGE = 3,

  /**
   * @generated from enum value: FILE_TYPE_VIDEO = 4;
   */
  VIDEO = 4,

  /**
   * @generated from enum value: FILE_TYPE_IMAGE_VIDEO = 5;
   */
  IMAGE_VIDEO = 5,

  /**
   * @generated from enum value: FILE_TYPE_AUDIO = 6;
   */
  AUDIO = 6,

  /**
   * @generated from enum value: FILE_TYPE_LINK_PREVIEW = 7;
   */
  LINK_PREVIEW = 7,

  /**
   * @generated from enum value: FILE_TYPE_NOT_LINK_PREVIEW = 8;
   */
  NOT_LINK_PREVIEW = 8,
}
// Retrieve enum metadata with: proto3.getEnumType(AttachmentFilter_FileType)
proto3.util.setEnumType(AttachmentFilter_FileType, "olvid.daemon.datatypes.v1.AttachmentFilter.FileType", [
  { no: 0, name: "FILE_TYPE_UNSPECIFIED" },
  { no: 3, name: "FILE_TYPE_IMAGE" },
  { no: 4, name: "FILE_TYPE_VIDEO" },
  { no: 5, name: "FILE_TYPE_IMAGE_VIDEO" },
  { no: 6, name: "FILE_TYPE_AUDIO" },
  { no: 7, name: "FILE_TYPE_LINK_PREVIEW" },
  { no: 8, name: "FILE_TYPE_NOT_LINK_PREVIEW" },
]);

