// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file olvid/daemon/datatypes/v1/call.proto (package olvid.daemon.datatypes.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message olvid.daemon.datatypes.v1.CallParticipantId
 */
export class CallParticipantId extends Message<CallParticipantId> {
  /**
   * @generated from oneof olvid.daemon.datatypes.v1.CallParticipantId.id
   */
  id: {
    /**
     * @generated from field: uint64 contact_id = 1;
     */
    value: bigint;
    case: "contactId";
  } | {
    /**
     * @generated from field: string participant_id = 2;
     */
    value: string;
    case: "participantId";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<CallParticipantId>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.datatypes.v1.CallParticipantId";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "contact_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, oneof: "id" },
    { no: 2, name: "participant_id", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "id" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CallParticipantId {
    return new CallParticipantId().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CallParticipantId {
    return new CallParticipantId().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CallParticipantId {
    return new CallParticipantId().fromJsonString(jsonString, options);
  }

  static equals(a: CallParticipantId | PlainMessage<CallParticipantId> | undefined, b: CallParticipantId | PlainMessage<CallParticipantId> | undefined): boolean {
    return proto3.util.equals(CallParticipantId, a, b);
  }
}

