// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file olvid/daemon/datatypes/v1/client_key.proto (package olvid.daemon.datatypes.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file olvid/daemon/datatypes/v1/client_key.proto.
 */
export const file_olvid_daemon_datatypes_v1_client_key: GenFile = /*@__PURE__*/
  fileDesc("CipvbHZpZC9kYWVtb24vZGF0YXR5cGVzL3YxL2NsaWVudF9rZXkucHJvdG8SGW9sdmlkLmRhZW1vbi5kYXRhdHlwZXMudjEiOwoJQ2xpZW50S2V5EgwKBG5hbWUYASABKAkSCwoDa2V5GAIgASgJEhMKC2lkZW50aXR5X2lkGAMgASgEIo0BCg9DbGllbnRLZXlGaWx0ZXISEwoJYWRtaW5fa2V5GAEgASgISAASFQoLaWRlbnRpdHlfaWQYAiABKARIABIYCgtuYW1lX3NlYXJjaBgDIAEoCUgBiAEBEhAKA2tleRgEIAEoCUgCiAEBQgoKCGlkZW50aXR5Qg4KDF9uYW1lX3NlYXJjaEIGCgRfa2V5QjUKIGlvLm9sdmlkLmRlc2t0b3AuZGFlbW9uLnByb3RvYnVmUABaD29sdmlkLmlvL2RhZW1vbmIGcHJvdG8z");

/**
 * @generated from message olvid.daemon.datatypes.v1.ClientKey
 */
export type ClientKey = Message<"olvid.daemon.datatypes.v1.ClientKey"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string key = 2;
   */
  key: string;

  /**
   * 0 if an admin key
   *
   * @generated from field: uint64 identity_id = 3;
   */
  identityId: bigint;
};

/**
 * Describes the message olvid.daemon.datatypes.v1.ClientKey.
 * Use `create(ClientKeySchema)` to create a new message.
 */
export const ClientKeySchema: GenMessage<ClientKey> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_datatypes_v1_client_key, 0);

/**
 * @generated from message olvid.daemon.datatypes.v1.ClientKeyFilter
 */
export type ClientKeyFilter = Message<"olvid.daemon.datatypes.v1.ClientKeyFilter"> & {
  /**
   * @generated from oneof olvid.daemon.datatypes.v1.ClientKeyFilter.identity
   */
  identity: {
    /**
     * @generated from field: bool admin_key = 1;
     */
    value: boolean;
    case: "adminKey";
  } | {
    /**
     * @generated from field: uint64 identity_id = 2;
     */
    value: bigint;
    case: "identityId";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: optional string name_search = 3;
   */
  nameSearch?: string;

  /**
   * @generated from field: optional string key = 4;
   */
  key?: string;
};

/**
 * Describes the message olvid.daemon.datatypes.v1.ClientKeyFilter.
 * Use `create(ClientKeyFilterSchema)` to create a new message.
 */
export const ClientKeyFilterSchema: GenMessage<ClientKeyFilter> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_datatypes_v1_client_key, 1);

