// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file olvid/daemon/datatypes/v1/keycloak.proto (package olvid.daemon.datatypes.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { IdentityDetails } from "./identity_pb";
import { file_olvid_daemon_datatypes_v1_identity } from "./identity_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file olvid/daemon/datatypes/v1/keycloak.proto.
 */
export const file_olvid_daemon_datatypes_v1_keycloak: GenFile = /*@__PURE__*/
  fileDesc("CihvbHZpZC9kYWVtb24vZGF0YXR5cGVzL3YxL2tleWNsb2FrLnByb3RvEhlvbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxIp4BCgxLZXljbG9ha1VzZXISEwoLa2V5Y2xvYWtfaWQYASABKAkSFAoMZGlzcGxheV9uYW1lGAIgASgJEjsKB2RldGFpbHMYAyABKAsyKi5vbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxLklkZW50aXR5RGV0YWlscxIXCgpjb250YWN0X2lkGAQgASgESACIAQFCDQoLX2NvbnRhY3RfaWQiywIKEktleWNsb2FrVXNlckZpbHRlchJLCgdjb250YWN0GAEgASgOMjUub2x2aWQuZGFlbW9uLmRhdGF0eXBlcy52MS5LZXljbG9ha1VzZXJGaWx0ZXIuQ29udGFjdEgAiAEBEiAKE2Rpc3BsYXlfbmFtZV9zZWFyY2gYAiABKAlIAYgBARJHCg5kZXRhaWxzX3NlYXJjaBgDIAEoCzIqLm9sdmlkLmRhZW1vbi5kYXRhdHlwZXMudjEuSWRlbnRpdHlEZXRhaWxzSAKIAQEiRgoHQ29udGFjdBIXChNDT05UQUNUX1VOU1BFQ0lGSUVEEAASDgoKQ09OVEFDVF9JUxABEhIKDkNPTlRBQ1RfSVNfTk9UEAJCCgoIX2NvbnRhY3RCFgoUX2Rpc3BsYXlfbmFtZV9zZWFyY2hCEQoPX2RldGFpbHNfc2VhcmNoQjUKIGlvLm9sdmlkLmRlc2t0b3AuZGFlbW9uLnByb3RvYnVmUABaD29sdmlkLmlvL2RhZW1vbmIGcHJvdG8z", [file_olvid_daemon_datatypes_v1_identity]);

/**
 * @generated from message olvid.daemon.datatypes.v1.KeycloakUser
 */
export type KeycloakUser = Message<"olvid.daemon.datatypes.v1.KeycloakUser"> & {
  /**
   * @generated from field: string keycloak_id = 1;
   */
  keycloakId: string;

  /**
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * @generated from field: olvid.daemon.datatypes.v1.IdentityDetails details = 3;
   */
  details?: IdentityDetails;

  /**
   * @generated from field: optional uint64 contact_id = 4;
   */
  contactId?: bigint;
};

/**
 * Describes the message olvid.daemon.datatypes.v1.KeycloakUser.
 * Use `create(KeycloakUserSchema)` to create a new message.
 */
export const KeycloakUserSchema: GenMessage<KeycloakUser> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_datatypes_v1_keycloak, 0);

/**
 * @generated from message olvid.daemon.datatypes.v1.KeycloakUserFilter
 */
export type KeycloakUserFilter = Message<"olvid.daemon.datatypes.v1.KeycloakUserFilter"> & {
  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.KeycloakUserFilter.Contact contact = 1;
   */
  contact?: KeycloakUserFilter_Contact;

  /**
   * @generated from field: optional string display_name_search = 2;
   */
  displayNameSearch?: string;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.IdentityDetails details_search = 3;
   */
  detailsSearch?: IdentityDetails;
};

/**
 * Describes the message olvid.daemon.datatypes.v1.KeycloakUserFilter.
 * Use `create(KeycloakUserFilterSchema)` to create a new message.
 */
export const KeycloakUserFilterSchema: GenMessage<KeycloakUserFilter> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_datatypes_v1_keycloak, 1);

/**
 * @generated from enum olvid.daemon.datatypes.v1.KeycloakUserFilter.Contact
 */
export enum KeycloakUserFilter_Contact {
  /**
   * @generated from enum value: CONTACT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CONTACT_IS = 1;
   */
  IS = 1,

  /**
   * @generated from enum value: CONTACT_IS_NOT = 2;
   */
  IS_NOT = 2,
}

/**
 * Describes the enum olvid.daemon.datatypes.v1.KeycloakUserFilter.Contact.
 */
export const KeycloakUserFilter_ContactSchema: GenEnum<KeycloakUserFilter_Contact> = /*@__PURE__*/
  enumDesc(file_olvid_daemon_datatypes_v1_keycloak, 1, 0);

