// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file olvid/daemon/datatypes/v1/message.proto (package olvid.daemon.datatypes.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message as Message$1, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message olvid.daemon.datatypes.v1.MessageId
 */
export class MessageId extends Message$1<MessageId> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.MessageId.Type type = 1;
   */
  type = MessageId_Type.UNSPECIFIED;

  /**
   * @generated from field: uint64 id = 2;
   */
  id = protoInt64.zero;

  constructor(data?: PartialMessage<MessageId>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.datatypes.v1.MessageId";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type", kind: "enum", T: proto3.getEnumType(MessageId_Type) },
    { no: 2, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageId {
    return new MessageId().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageId {
    return new MessageId().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageId {
    return new MessageId().fromJsonString(jsonString, options);
  }

  static equals(a: MessageId | PlainMessage<MessageId> | undefined, b: MessageId | PlainMessage<MessageId> | undefined): boolean {
    return proto3.util.equals(MessageId, a, b);
  }
}

/**
 * @generated from enum olvid.daemon.datatypes.v1.MessageId.Type
 */
export enum MessageId_Type {
  /**
   * @generated from enum value: TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TYPE_INBOUND = 1;
   */
  INBOUND = 1,

  /**
   * @generated from enum value: TYPE_OUTBOUND = 2;
   */
  OUTBOUND = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(MessageId_Type)
proto3.util.setEnumType(MessageId_Type, "olvid.daemon.datatypes.v1.MessageId.Type", [
  { no: 0, name: "TYPE_UNSPECIFIED" },
  { no: 1, name: "TYPE_INBOUND" },
  { no: 2, name: "TYPE_OUTBOUND" },
]);

/**
 * @generated from message olvid.daemon.datatypes.v1.Message
 */
export class Message extends Message$1<Message> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.MessageId id = 1;
   */
  id?: MessageId;

  /**
   * @generated from field: uint64 discussion_id = 2;
   */
  discussionId = protoInt64.zero;

  /**
   * 0 if you sent the message
   *
   * @generated from field: uint64 sender_id = 3;
   */
  senderId = protoInt64.zero;

  /**
   * @generated from field: string body = 4;
   */
  body = "";

  /**
   * @generated from field: double sort_index = 5;
   */
  sortIndex = 0;

  /**
   * @generated from field: uint64 timestamp = 6;
   */
  timestamp = protoInt64.zero;

  /**
   * @generated from field: uint64 attachments_count = 7;
   */
  attachmentsCount = protoInt64.zero;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.MessageId replied_message_id = 8;
   */
  repliedMessageId?: MessageId;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.MessageLocation message_location = 10;
   */
  messageLocation?: MessageLocation;

  /**
   * @generated from field: repeated olvid.daemon.datatypes.v1.MessageReaction reactions = 11;
   */
  reactions: MessageReaction[] = [];

  /**
   * @generated from field: bool forwarded = 12;
   */
  forwarded = false;

  /**
   * @generated from field: bool edited_body = 13;
   */
  editedBody = false;

  constructor(data?: PartialMessage<Message>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.datatypes.v1.Message";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: MessageId },
    { no: 2, name: "discussion_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "sender_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "body", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "sort_index", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 6, name: "timestamp", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 7, name: "attachments_count", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 8, name: "replied_message_id", kind: "message", T: MessageId, opt: true },
    { no: 10, name: "message_location", kind: "message", T: MessageLocation, opt: true },
    { no: 11, name: "reactions", kind: "message", T: MessageReaction, repeated: true },
    { no: 12, name: "forwarded", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 13, name: "edited_body", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Message {
    return new Message().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Message {
    return new Message().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Message {
    return new Message().fromJsonString(jsonString, options);
  }

  static equals(a: Message | PlainMessage<Message> | undefined, b: Message | PlainMessage<Message> | undefined): boolean {
    return proto3.util.equals(Message, a, b);
  }
}

/**
 * @generated from message olvid.daemon.datatypes.v1.MessageEphemerality
 */
export class MessageEphemerality extends Message$1<MessageEphemerality> {
  /**
   * @generated from field: bool read_once = 1;
   */
  readOnce = false;

  /**
   * seconds
   *
   * @generated from field: uint64 existence_duration = 2;
   */
  existenceDuration = protoInt64.zero;

  /**
   * seconds
   *
   * @generated from field: uint64 visibility_duration = 3;
   */
  visibilityDuration = protoInt64.zero;

  constructor(data?: PartialMessage<MessageEphemerality>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.datatypes.v1.MessageEphemerality";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "read_once", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "existence_duration", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "visibility_duration", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageEphemerality {
    return new MessageEphemerality().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageEphemerality {
    return new MessageEphemerality().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageEphemerality {
    return new MessageEphemerality().fromJsonString(jsonString, options);
  }

  static equals(a: MessageEphemerality | PlainMessage<MessageEphemerality> | undefined, b: MessageEphemerality | PlainMessage<MessageEphemerality> | undefined): boolean {
    return proto3.util.equals(MessageEphemerality, a, b);
  }
}

/**
 * @generated from message olvid.daemon.datatypes.v1.MessageReaction
 */
export class MessageReaction extends Message$1<MessageReaction> {
  /**
   * id == 0 if own reaction
   *
   * @generated from field: uint64 contact_id = 1;
   */
  contactId = protoInt64.zero;

  /**
   * @generated from field: string reaction = 2;
   */
  reaction = "";

  /**
   * @generated from field: uint64 timestamp = 3;
   */
  timestamp = protoInt64.zero;

  constructor(data?: PartialMessage<MessageReaction>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.datatypes.v1.MessageReaction";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "contact_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "reaction", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "timestamp", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageReaction {
    return new MessageReaction().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageReaction {
    return new MessageReaction().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageReaction {
    return new MessageReaction().fromJsonString(jsonString, options);
  }

  static equals(a: MessageReaction | PlainMessage<MessageReaction> | undefined, b: MessageReaction | PlainMessage<MessageReaction> | undefined): boolean {
    return proto3.util.equals(MessageReaction, a, b);
  }
}

/**
 * @generated from message olvid.daemon.datatypes.v1.MessageLocation
 */
export class MessageLocation extends Message$1<MessageLocation> {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.MessageLocation.LocationType type = 1;
   */
  type = MessageLocation_LocationType.UNSPECIFIED;

  /**
   * @generated from field: uint64 timestamp = 2;
   */
  timestamp = protoInt64.zero;

  /**
   * @generated from field: double latitude = 3;
   */
  latitude = 0;

  /**
   * @generated from field: double longitude = 4;
   */
  longitude = 0;

  /**
   * @generated from field: optional double altitude = 5;
   */
  altitude?: number;

  /**
   * @generated from field: optional float precision = 6;
   */
  precision?: number;

  /**
   * @generated from field: optional string address = 7;
   */
  address?: string;

  constructor(data?: PartialMessage<MessageLocation>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.datatypes.v1.MessageLocation";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type", kind: "enum", T: proto3.getEnumType(MessageLocation_LocationType) },
    { no: 2, name: "timestamp", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "latitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "longitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "altitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 6, name: "precision", kind: "scalar", T: 2 /* ScalarType.FLOAT */, opt: true },
    { no: 7, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageLocation {
    return new MessageLocation().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageLocation {
    return new MessageLocation().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageLocation {
    return new MessageLocation().fromJsonString(jsonString, options);
  }

  static equals(a: MessageLocation | PlainMessage<MessageLocation> | undefined, b: MessageLocation | PlainMessage<MessageLocation> | undefined): boolean {
    return proto3.util.equals(MessageLocation, a, b);
  }
}

/**
 * @generated from enum olvid.daemon.datatypes.v1.MessageLocation.LocationType
 */
export enum MessageLocation_LocationType {
  /**
   * @generated from enum value: LOCATION_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: LOCATION_TYPE_SEND = 1;
   */
  SEND = 1,

  /**
   * @generated from enum value: LOCATION_TYPE_SHARING = 2;
   */
  SHARING = 2,

  /**
   * @generated from enum value: LOCATION_TYPE_SHARING_FINISHED = 3;
   */
  SHARING_FINISHED = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(MessageLocation_LocationType)
proto3.util.setEnumType(MessageLocation_LocationType, "olvid.daemon.datatypes.v1.MessageLocation.LocationType", [
  { no: 0, name: "LOCATION_TYPE_UNSPECIFIED" },
  { no: 1, name: "LOCATION_TYPE_SEND" },
  { no: 2, name: "LOCATION_TYPE_SHARING" },
  { no: 3, name: "LOCATION_TYPE_SHARING_FINISHED" },
]);

/**
 * @generated from message olvid.daemon.datatypes.v1.MessageFilter
 */
export class MessageFilter extends Message$1<MessageFilter> {
  /**
   * sender and recipient
   *
   * @generated from field: optional olvid.daemon.datatypes.v1.MessageId.Type type = 1;
   */
  type?: MessageId_Type;

  /**
   * @generated from field: optional uint64 discussion_id = 2;
   */
  discussionId?: bigint;

  /**
   * @generated from field: optional uint64 sender_contact_id = 3;
   */
  senderContactId?: bigint;

  /**
   * content
   *
   * @generated from field: optional string body_search = 5;
   */
  bodySearch?: string;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.MessageFilter.Attachment attachment = 6;
   */
  attachment?: MessageFilter_Attachment;

  /**
   * @generated from field: optional olvid.daemon.datatypes.v1.MessageFilter.Location location = 7;
   */
  location?: MessageFilter_Location;

  /**
   * @generated from field: optional uint64 min_timestamp = 8;
   */
  minTimestamp?: bigint;

  /**
   * @generated from field: optional uint64 max_timestamp = 9;
   */
  maxTimestamp?: bigint;

  /**
   * reactions
   *
   * @generated from field: optional olvid.daemon.datatypes.v1.MessageFilter.Reaction reaction = 10;
   */
  reaction?: MessageFilter_Reaction;

  /**
   * @generated from field: repeated olvid.daemon.datatypes.v1.ReactionFilter reactions_filter = 11;
   */
  reactionsFilter: ReactionFilter[] = [];

  /**
   * message reply
   *
   * @generated from oneof olvid.daemon.datatypes.v1.MessageFilter.reply
   */
  reply: {
    /**
     * @generated from field: bool reply_to_a_message = 13;
     */
    value: boolean;
    case: "replyToAMessage";
  } | {
    /**
     * @generated from field: bool do_not_reply_to_a_message = 14;
     */
    value: boolean;
    case: "doNotReplyToAMessage";
  } | {
    /**
     * @generated from field: olvid.daemon.datatypes.v1.MessageId replied_message_id = 15;
     */
    value: MessageId;
    case: "repliedMessageId";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<MessageFilter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.datatypes.v1.MessageFilter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type", kind: "enum", T: proto3.getEnumType(MessageId_Type), opt: true },
    { no: 2, name: "discussion_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 3, name: "sender_contact_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 5, name: "body_search", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "attachment", kind: "enum", T: proto3.getEnumType(MessageFilter_Attachment), opt: true },
    { no: 7, name: "location", kind: "enum", T: proto3.getEnumType(MessageFilter_Location), opt: true },
    { no: 8, name: "min_timestamp", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 9, name: "max_timestamp", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 10, name: "reaction", kind: "enum", T: proto3.getEnumType(MessageFilter_Reaction), opt: true },
    { no: 11, name: "reactions_filter", kind: "message", T: ReactionFilter, repeated: true },
    { no: 13, name: "reply_to_a_message", kind: "scalar", T: 8 /* ScalarType.BOOL */, oneof: "reply" },
    { no: 14, name: "do_not_reply_to_a_message", kind: "scalar", T: 8 /* ScalarType.BOOL */, oneof: "reply" },
    { no: 15, name: "replied_message_id", kind: "message", T: MessageId, oneof: "reply" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageFilter {
    return new MessageFilter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageFilter {
    return new MessageFilter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageFilter {
    return new MessageFilter().fromJsonString(jsonString, options);
  }

  static equals(a: MessageFilter | PlainMessage<MessageFilter> | undefined, b: MessageFilter | PlainMessage<MessageFilter> | undefined): boolean {
    return proto3.util.equals(MessageFilter, a, b);
  }
}

/**
 * @generated from enum olvid.daemon.datatypes.v1.MessageFilter.Attachment
 */
export enum MessageFilter_Attachment {
  /**
   * @generated from enum value: ATTACHMENT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ATTACHMENT_HAVE = 1;
   */
  HAVE = 1,

  /**
   * currently not implementable
   *    ATTACHMENT_HAVE_IMAGE = 3;
   *    ATTACHMENT_HAVE_VIDEO = 4;
   *    ATTACHMENT_HAVE_IMAGE_VIDEO = 5;
   *    ATTACHMENT_HAVE_AUDIO = 6;
   *
   * @generated from enum value: ATTACHMENT_HAVE_NOT = 2;
   */
  HAVE_NOT = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(MessageFilter_Attachment)
proto3.util.setEnumType(MessageFilter_Attachment, "olvid.daemon.datatypes.v1.MessageFilter.Attachment", [
  { no: 0, name: "ATTACHMENT_UNSPECIFIED" },
  { no: 1, name: "ATTACHMENT_HAVE" },
  { no: 2, name: "ATTACHMENT_HAVE_NOT" },
]);

/**
 * @generated from enum olvid.daemon.datatypes.v1.MessageFilter.Location
 */
export enum MessageFilter_Location {
  /**
   * @generated from enum value: LOCATION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: LOCATION_HAVE = 1;
   */
  HAVE = 1,

  /**
   * @generated from enum value: LOCATION_HAVE_NOT = 2;
   */
  HAVE_NOT = 2,

  /**
   * @generated from enum value: LOCATION_IS_SEND = 3;
   */
  IS_SEND = 3,

  /**
   * @generated from enum value: LOCATION_IS_SHARING = 5;
   */
  IS_SHARING = 5,

  /**
   * @generated from enum value: LOCATION_IS_SHARING_FINISHED = 6;
   */
  IS_SHARING_FINISHED = 6,
}
// Retrieve enum metadata with: proto3.getEnumType(MessageFilter_Location)
proto3.util.setEnumType(MessageFilter_Location, "olvid.daemon.datatypes.v1.MessageFilter.Location", [
  { no: 0, name: "LOCATION_UNSPECIFIED" },
  { no: 1, name: "LOCATION_HAVE" },
  { no: 2, name: "LOCATION_HAVE_NOT" },
  { no: 3, name: "LOCATION_IS_SEND" },
  { no: 5, name: "LOCATION_IS_SHARING" },
  { no: 6, name: "LOCATION_IS_SHARING_FINISHED" },
]);

/**
 * @generated from enum olvid.daemon.datatypes.v1.MessageFilter.Reaction
 */
export enum MessageFilter_Reaction {
  /**
   * @generated from enum value: REACTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: REACTION_HAS = 1;
   */
  HAS = 1,

  /**
   * @generated from enum value: REACTION_HAS_NOT = 2;
   */
  HAS_NOT = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(MessageFilter_Reaction)
proto3.util.setEnumType(MessageFilter_Reaction, "olvid.daemon.datatypes.v1.MessageFilter.Reaction", [
  { no: 0, name: "REACTION_UNSPECIFIED" },
  { no: 1, name: "REACTION_HAS" },
  { no: 2, name: "REACTION_HAS_NOT" },
]);

/**
 * @generated from message olvid.daemon.datatypes.v1.ReactionFilter
 */
export class ReactionFilter extends Message$1<ReactionFilter> {
  /**
   * @generated from oneof olvid.daemon.datatypes.v1.ReactionFilter.reacted_by
   */
  reactedBy: {
    /**
     * @generated from field: bool reacted_by_me = 10;
     */
    value: boolean;
    case: "reactedByMe";
  } | {
    /**
     * @generated from field: uint64 reacted_by_contact_id = 11;
     */
    value: bigint;
    case: "reactedByContactId";
  } | { case: undefined; value?: undefined } = { case: undefined };

  /**
   * contains this reaction emoji (combined with reacted_by parameter)
   *
   * @generated from field: optional string reaction = 12;
   */
  reaction?: string;

  constructor(data?: PartialMessage<ReactionFilter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "olvid.daemon.datatypes.v1.ReactionFilter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 10, name: "reacted_by_me", kind: "scalar", T: 8 /* ScalarType.BOOL */, oneof: "reacted_by" },
    { no: 11, name: "reacted_by_contact_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, oneof: "reacted_by" },
    { no: 12, name: "reaction", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReactionFilter {
    return new ReactionFilter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReactionFilter {
    return new ReactionFilter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReactionFilter {
    return new ReactionFilter().fromJsonString(jsonString, options);
  }

  static equals(a: ReactionFilter | PlainMessage<ReactionFilter> | undefined, b: ReactionFilter | PlainMessage<ReactionFilter> | undefined): boolean {
    return proto3.util.equals(ReactionFilter, a, b);
  }
}

