// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file olvid/daemon/datatypes/v1/settings.proto (package olvid.daemon.datatypes.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file olvid/daemon/datatypes/v1/settings.proto.
 */
export const file_olvid_daemon_datatypes_v1_settings: GenFile = /*@__PURE__*/
  fileDesc("CihvbHZpZC9kYWVtb24vZGF0YXR5cGVzL3YxL3NldHRpbmdzLnByb3RvEhlvbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxIv4EChBJZGVudGl0eVNldHRpbmdzElQKCmludml0YXRpb24YASABKAsyQC5vbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxLklkZW50aXR5U2V0dGluZ3MuQXV0b0FjY2VwdEludml0YXRpb24SVwoRbWVzc2FnZV9yZXRlbnRpb24YAiABKAsyPC5vbHZpZC5kYWVtb24uZGF0YXR5cGVzLnYxLklkZW50aXR5U2V0dGluZ3MuTWVzc2FnZVJldGVudGlvbhJGCghrZXljbG9haxgDIAEoCzI0Lm9sdmlkLmRhZW1vbi5kYXRhdHlwZXMudjEuSWRlbnRpdHlTZXR0aW5ncy5LZXljbG9haxqTAQoUQXV0b0FjY2VwdEludml0YXRpb24SIAoYYXV0b19hY2NlcHRfaW50cm9kdWN0aW9uGAEgASgIEhkKEWF1dG9fYWNjZXB0X2dyb3VwGAIgASgIEh4KFmF1dG9fYWNjZXB0X29uZV90b19vbmUYAyABKAgSHgoWYXV0b19hY2NlcHRfaW52aXRhdGlvbhgEIAEoCBqvAQoQTWVzc2FnZVJldGVudGlvbhIaChJleGlzdGVuY2VfZHVyYXRpb24YASABKAQSGAoQZGlzY3Vzc2lvbl9jb3VudBgCIAEoBBIUCgxnbG9iYWxfY291bnQYAyABKAQSIAoYY2xlYW5fbG9ja2VkX2Rpc2N1c3Npb25zGAQgASgIEi0KJXByZXNlcnZlX2lzX3NoYXJpbmdfbG9jYXRpb25fbWVzc2FnZXMYBSABKAgaKwoIS2V5Y2xvYWsSHwoXYXV0b19pbnZpdGVfbmV3X21lbWJlcnMYASABKAgidwoSRGlzY3Vzc2lvblNldHRpbmdzEhUKDWRpc2N1c3Npb25faWQYASABKAQSEQoJcmVhZF9vbmNlGAIgASgIEhoKEmV4aXN0ZW5jZV9kdXJhdGlvbhgDIAEoBBIbChN2aXNpYmlsaXR5X2R1cmF0aW9uGAQgASgEQjUKIGlvLm9sdmlkLmRlc2t0b3AuZGFlbW9uLnByb3RvYnVmUABaD29sdmlkLmlvL2RhZW1vbmIGcHJvdG8z");

/**
 * @generated from message olvid.daemon.datatypes.v1.IdentitySettings
 */
export type IdentitySettings = Message<"olvid.daemon.datatypes.v1.IdentitySettings"> & {
  /**
   * @generated from field: olvid.daemon.datatypes.v1.IdentitySettings.AutoAcceptInvitation invitation = 1;
   */
  invitation?: IdentitySettings_AutoAcceptInvitation;

  /**
   * @generated from field: olvid.daemon.datatypes.v1.IdentitySettings.MessageRetention message_retention = 2;
   */
  messageRetention?: IdentitySettings_MessageRetention;

  /**
   * @generated from field: olvid.daemon.datatypes.v1.IdentitySettings.Keycloak keycloak = 3;
   */
  keycloak?: IdentitySettings_Keycloak;
};

/**
 * Describes the message olvid.daemon.datatypes.v1.IdentitySettings.
 * Use `create(IdentitySettingsSchema)` to create a new message.
 */
export const IdentitySettingsSchema: GenMessage<IdentitySettings> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_datatypes_v1_settings, 0);

/**
 * @generated from message olvid.daemon.datatypes.v1.IdentitySettings.AutoAcceptInvitation
 */
export type IdentitySettings_AutoAcceptInvitation = Message<"olvid.daemon.datatypes.v1.IdentitySettings.AutoAcceptInvitation"> & {
  /**
   * @generated from field: bool auto_accept_introduction = 1;
   */
  autoAcceptIntroduction: boolean;

  /**
   * @generated from field: bool auto_accept_group = 2;
   */
  autoAcceptGroup: boolean;

  /**
   * @generated from field: bool auto_accept_one_to_one = 3;
   */
  autoAcceptOneToOne: boolean;

  /**
   * @generated from field: bool auto_accept_invitation = 4;
   */
  autoAcceptInvitation: boolean;
};

/**
 * Describes the message olvid.daemon.datatypes.v1.IdentitySettings.AutoAcceptInvitation.
 * Use `create(IdentitySettings_AutoAcceptInvitationSchema)` to create a new message.
 */
export const IdentitySettings_AutoAcceptInvitationSchema: GenMessage<IdentitySettings_AutoAcceptInvitation> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_datatypes_v1_settings, 0, 0);

/**
 * @generated from message olvid.daemon.datatypes.v1.IdentitySettings.MessageRetention
 */
export type IdentitySettings_MessageRetention = Message<"olvid.daemon.datatypes.v1.IdentitySettings.MessageRetention"> & {
  /**
   * 0 -> disabled (seconds)
   *
   * @generated from field: uint64 existence_duration = 1;
   */
  existenceDuration: bigint;

  /**
   * 0 -> disabled
   *
   * @generated from field: uint64 discussion_count = 2;
   */
  discussionCount: bigint;

  /**
   * 0 -> disabled
   *
   * @generated from field: uint64 global_count = 3;
   */
  globalCount: bigint;

  /**
   * @generated from field: bool clean_locked_discussions = 4;
   */
  cleanLockedDiscussions: boolean;

  /**
   * @generated from field: bool preserve_is_sharing_location_messages = 5;
   */
  preserveIsSharingLocationMessages: boolean;
};

/**
 * Describes the message olvid.daemon.datatypes.v1.IdentitySettings.MessageRetention.
 * Use `create(IdentitySettings_MessageRetentionSchema)` to create a new message.
 */
export const IdentitySettings_MessageRetentionSchema: GenMessage<IdentitySettings_MessageRetention> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_datatypes_v1_settings, 0, 1);

/**
 * @generated from message olvid.daemon.datatypes.v1.IdentitySettings.Keycloak
 */
export type IdentitySettings_Keycloak = Message<"olvid.daemon.datatypes.v1.IdentitySettings.Keycloak"> & {
  /**
   * @generated from field: bool auto_invite_new_members = 1;
   */
  autoInviteNewMembers: boolean;
};

/**
 * Describes the message olvid.daemon.datatypes.v1.IdentitySettings.Keycloak.
 * Use `create(IdentitySettings_KeycloakSchema)` to create a new message.
 */
export const IdentitySettings_KeycloakSchema: GenMessage<IdentitySettings_Keycloak> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_datatypes_v1_settings, 0, 2);

/**
 * @generated from message olvid.daemon.datatypes.v1.DiscussionSettings
 */
export type DiscussionSettings = Message<"olvid.daemon.datatypes.v1.DiscussionSettings"> & {
  /**
   * @generated from field: uint64 discussion_id = 1;
   */
  discussionId: bigint;

  /**
   * message ephemerality settings (does not use a proper message for legacy reasons)
   *
   * @generated from field: bool read_once = 2;
   */
  readOnce: boolean;

  /**
   * 0 -> disabled (seconds)
   *
   * @generated from field: uint64 existence_duration = 3;
   */
  existenceDuration: bigint;

  /**
   * 0 -> disabled (seconds)
   *
   * @generated from field: uint64 visibility_duration = 4;
   */
  visibilityDuration: bigint;
};

/**
 * Describes the message olvid.daemon.datatypes.v1.DiscussionSettings.
 * Use `create(DiscussionSettingsSchema)` to create a new message.
 */
export const DiscussionSettingsSchema: GenMessage<DiscussionSettings> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_datatypes_v1_settings, 1);

