// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file olvid/daemon/datatypes/v1/storage.proto (package olvid.daemon.datatypes.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file olvid/daemon/datatypes/v1/storage.proto.
 */
export const file_olvid_daemon_datatypes_v1_storage: GenFile = /*@__PURE__*/
  fileDesc("CidvbHZpZC9kYWVtb24vZGF0YXR5cGVzL3YxL3N0b3JhZ2UucHJvdG8SGW9sdmlkLmRhZW1vbi5kYXRhdHlwZXMudjEiLAoOU3RvcmFnZUVsZW1lbnQSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJImoKFFN0b3JhZ2VFbGVtZW50RmlsdGVyEhcKCmtleV9zZWFyY2gYASABKAlIAIgBARIZCgx2YWx1ZV9zZWFyY2gYAiABKAlIAYgBAUINCgtfa2V5X3NlYXJjaEIPCg1fdmFsdWVfc2VhcmNoQjUKIGlvLm9sdmlkLmRlc2t0b3AuZGFlbW9uLnByb3RvYnVmUABaD29sdmlkLmlvL2RhZW1vbmIGcHJvdG8z");

/**
 * @generated from message olvid.daemon.datatypes.v1.StorageElement
 */
export type StorageElement = Message<"olvid.daemon.datatypes.v1.StorageElement"> & {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;
};

/**
 * Describes the message olvid.daemon.datatypes.v1.StorageElement.
 * Use `create(StorageElementSchema)` to create a new message.
 */
export const StorageElementSchema: GenMessage<StorageElement> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_datatypes_v1_storage, 0);

/**
 * @generated from message olvid.daemon.datatypes.v1.StorageElementFilter
 */
export type StorageElementFilter = Message<"olvid.daemon.datatypes.v1.StorageElementFilter"> & {
  /**
   * @generated from field: optional string key_search = 1;
   */
  keySearch?: string;

  /**
   * @generated from field: optional string value_search = 2;
   */
  valueSearch?: string;
};

/**
 * Describes the message olvid.daemon.datatypes.v1.StorageElementFilter.
 * Use `create(StorageElementFilterSchema)` to create a new message.
 */
export const StorageElementFilterSchema: GenMessage<StorageElementFilter> = /*@__PURE__*/
  messageDesc(file_olvid_daemon_datatypes_v1_storage, 1);

