// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file olvid/daemon/services/v1/admin_service.proto (package olvid.daemon.services.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ClientKeyDeleteRequest, ClientKeyDeleteResponse, ClientKeyGetRequest, ClientKeyGetResponse, ClientKeyListRequest, ClientKeyListResponse, ClientKeyNewRequest, ClientKeyNewResponse } from "../../admin/v1/client_key_admin_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { IdentityAdminDownloadPhotoRequest, IdentityAdminDownloadPhotoResponse, IdentityAdminGetBytesIdentifierRequest, IdentityAdminGetBytesIdentifierResponse, IdentityAdminGetInvitationLinkRequest, IdentityAdminGetInvitationLinkResponse, IdentityAdminGetRequest, IdentityAdminGetResponse, IdentityDeleteRequest, IdentityDeleteResponse, IdentityKeycloakNewRequest, IdentityKeycloakNewResponse, IdentityListRequest, IdentityListResponse, IdentityNewRequest, IdentityNewResponse } from "../../admin/v1/identity_admin_pb.js";

/**
 * ClientKey
 *
 * @generated from service olvid.daemon.services.v1.ClientKeyAdminService
 */
export const ClientKeyAdminService = {
  typeName: "olvid.daemon.services.v1.ClientKeyAdminService",
  methods: {
    /**
     * @generated from rpc olvid.daemon.services.v1.ClientKeyAdminService.ClientKeyList
     */
    clientKeyList: {
      name: "ClientKeyList",
      I: ClientKeyListRequest,
      O: ClientKeyListResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc olvid.daemon.services.v1.ClientKeyAdminService.ClientKeyGet
     */
    clientKeyGet: {
      name: "ClientKeyGet",
      I: ClientKeyGetRequest,
      O: ClientKeyGetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc olvid.daemon.services.v1.ClientKeyAdminService.ClientKeyNew
     */
    clientKeyNew: {
      name: "ClientKeyNew",
      I: ClientKeyNewRequest,
      O: ClientKeyNewResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc olvid.daemon.services.v1.ClientKeyAdminService.ClientKeyDelete
     */
    clientKeyDelete: {
      name: "ClientKeyDelete",
      I: ClientKeyDeleteRequest,
      O: ClientKeyDeleteResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * Identity
 *
 * @generated from service olvid.daemon.services.v1.IdentityAdminService
 */
export const IdentityAdminService = {
  typeName: "olvid.daemon.services.v1.IdentityAdminService",
  methods: {
    /**
     * @generated from rpc olvid.daemon.services.v1.IdentityAdminService.IdentityList
     */
    identityList: {
      name: "IdentityList",
      I: IdentityListRequest,
      O: IdentityListResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc olvid.daemon.services.v1.IdentityAdminService.IdentityAdminGet
     */
    identityAdminGet: {
      name: "IdentityAdminGet",
      I: IdentityAdminGetRequest,
      O: IdentityAdminGetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc olvid.daemon.services.v1.IdentityAdminService.IdentityAdminGetBytesIdentifier
     */
    identityAdminGetBytesIdentifier: {
      name: "IdentityAdminGetBytesIdentifier",
      I: IdentityAdminGetBytesIdentifierRequest,
      O: IdentityAdminGetBytesIdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc olvid.daemon.services.v1.IdentityAdminService.IdentityAdminGetInvitationLink
     */
    identityAdminGetInvitationLink: {
      name: "IdentityAdminGetInvitationLink",
      I: IdentityAdminGetInvitationLinkRequest,
      O: IdentityAdminGetInvitationLinkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc olvid.daemon.services.v1.IdentityAdminService.IdentityAdminDownloadPhoto
     */
    identityAdminDownloadPhoto: {
      name: "IdentityAdminDownloadPhoto",
      I: IdentityAdminDownloadPhotoRequest,
      O: IdentityAdminDownloadPhotoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc olvid.daemon.services.v1.IdentityAdminService.IdentityDelete
     */
    identityDelete: {
      name: "IdentityDelete",
      I: IdentityDeleteRequest,
      O: IdentityDeleteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc olvid.daemon.services.v1.IdentityAdminService.IdentityNew
     */
    identityNew: {
      name: "IdentityNew",
      I: IdentityNewRequest,
      O: IdentityNewResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc olvid.daemon.services.v1.IdentityAdminService.IdentityKeycloakNew
     */
    identityKeycloakNew: {
      name: "IdentityKeycloakNew",
      I: IdentityKeycloakNewRequest,
      O: IdentityKeycloakNewResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

